/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AspectSetData.h
	Last generated: Fri Oct 22 13:43:56 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AspectSetData_included
#define AspectSetData_included

#include <qwidget.h>
#include <qchkbox.h>
#include "myLineEdit.h"
#include "tr.h"

class AspectSetData : public QWidget
{
    Q_OBJECT

public:

    AspectSetData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AspectSetData();

public slots:


protected slots:

    virtual void orbslot();
    virtual void influenceslot();
    virtual void aspnameslot();
    virtual void angleslot();

protected:
    myLineEdit* Orb;
    myLineEdit* Angle;
    myLineEdit* Influence;
    QCheckBox* AspName;

};

#endif // AspectSetData_included
