/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AspectSetData.cpp
	Last generated: Fri Oct 22 13:43:56 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AspectSetData.h"
#include "tr.h"

#define Inherited QWidget


AspectSetData::AspectSetData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	Orb = new myLineEdit( this, "LineEdit_1" );
	Orb->setGeometry( 130, 10, 40, 20 );
	Orb->setMinimumSize( 0, 0 );
	Orb->setMaximumSize( 32767, 32767 );
	connect( Orb, SIGNAL(returnPressed()), SLOT(orbslot()) );
	Orb->setFocusPolicy( QWidget::StrongFocus );
	Orb->setBackgroundMode( QWidget::PaletteBase );
	Orb->setFontPropagation( QWidget::NoChildren );
	Orb->setPalettePropagation( QWidget::NoChildren );
	Orb->setText( "" );
	Orb->setMaxLength( 32767 );
	Orb->setEchoMode( myLineEdit::Normal );
	Orb->setFrame( TRUE );

	Angle = new myLineEdit( this, "LineEdit_2" );
	Angle->setGeometry( 180, 10, 50, 20 );
	Angle->setMinimumSize( 0, 0 );
	Angle->setMaximumSize( 32767, 32767 );
	connect( Angle, SIGNAL(returnPressed()), SLOT(angleslot()) );
	Angle->setFocusPolicy( QWidget::StrongFocus );
	Angle->setBackgroundMode( QWidget::PaletteBase );
	Angle->setFontPropagation( QWidget::NoChildren );
	Angle->setPalettePropagation( QWidget::NoChildren );
	Angle->setText( "" );
	Angle->setMaxLength( 32767 );
	Angle->setEchoMode( myLineEdit::Normal );
	Angle->setFrame( TRUE );

	Influence = new myLineEdit( this, "LineEdit_3" );
	Influence->setGeometry( 240, 10, 30, 20 );
	Influence->setMinimumSize( 0, 0 );
	Influence->setMaximumSize( 32767, 32767 );
	connect( Influence, SIGNAL(returnPressed()), SLOT(influenceslot()) );
	Influence->setFocusPolicy( QWidget::StrongFocus );
	Influence->setBackgroundMode( QWidget::PaletteBase );
	Influence->setFontPropagation( QWidget::NoChildren );
	Influence->setPalettePropagation( QWidget::NoChildren );
	Influence->setText( "" );
	Influence->setMaxLength( 32767 );
	Influence->setEchoMode( myLineEdit::Normal );
	Influence->setFrame( TRUE );

	AspName = new QCheckBox( this, "CheckBox_1" );
	AspName->setGeometry( 10, 10, 110, 20 );
	AspName->setMinimumSize( 0, 0 );
	AspName->setMaximumSize( 32767, 32767 );
	connect( AspName, SIGNAL(clicked()), SLOT(aspnameslot()) );
	AspName->setFocusPolicy( QWidget::TabFocus );
	AspName->setBackgroundMode( QWidget::PaletteBackground );
	AspName->setFontPropagation( QWidget::NoChildren );
	AspName->setPalettePropagation( QWidget::NoChildren );
	AspName->setText( "" );
	AspName->setAutoRepeat( FALSE );
	AspName->setAutoResize( FALSE );

	resize( 280,40 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


AspectSetData::~AspectSetData()
{
}
void AspectSetData::orbslot()
{
}
void AspectSetData::angleslot()
{
}
void AspectSetData::influenceslot()
{
}
void AspectSetData::aspnameslot()
{
}
