/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroInfoData.cpp
	Last generated: Mon Aug 28 14:52:53 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AstroInfoData.h"
#include "tr.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

AstroInfoData::AstroInfoData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	monthlabel = new QLabel( this, "Label_22" );
	monthlabel->setGeometry( 10, 10, 80, 30 );
	monthlabel->setMinimumSize( 0, 0 );
	monthlabel->setMaximumSize( 32767, 32767 );
	monthlabel->setFocusPolicy( QWidget::NoFocus );
	monthlabel->setBackgroundMode( QWidget::PaletteBackground );
	monthlabel->setFontPropagation( QWidget::NoChildren );
	monthlabel->setPalettePropagation( QWidget::NoChildren );
	monthlabel->setText( transl("Month:") );
	monthlabel->setAlignment( 289 );
	monthlabel->setMargin( -1 );

	daylabel = new QLabel( this, "Label_23" );
	daylabel->setGeometry( 10, 40, 80, 30 );
	daylabel->setMinimumSize( 0, 0 );
	daylabel->setMaximumSize( 32767, 32767 );
	daylabel->setFocusPolicy( QWidget::NoFocus );
	daylabel->setBackgroundMode( QWidget::PaletteBackground );
	daylabel->setFontPropagation( QWidget::NoChildren );
	daylabel->setPalettePropagation( QWidget::NoChildren );
	daylabel->setText( transl("Day:") );
	daylabel->setAlignment( 289 );
	daylabel->setMargin( -1 );

	yearlabel = new QLabel( this, "Label_24" );
	yearlabel->setGeometry( 10, 70, 80, 30 );
	yearlabel->setMinimumSize( 0, 0 );
	yearlabel->setMaximumSize( 32767, 32767 );
	yearlabel->setFocusPolicy( QWidget::NoFocus );
	yearlabel->setBackgroundMode( QWidget::PaletteBackground );
	yearlabel->setFontPropagation( QWidget::NoChildren );
	yearlabel->setPalettePropagation( QWidget::NoChildren );
	yearlabel->setText( transl("Year:") );
	yearlabel->setAlignment( 289 );
	yearlabel->setMargin( -1 );

	timelabel = new QLabel( this, "Label_25" );
	timelabel->setGeometry( 10, 100, 80, 30 );
	timelabel->setMinimumSize( 0, 0 );
	timelabel->setMaximumSize( 32767, 32767 );
	timelabel->setFocusPolicy( QWidget::NoFocus );
	timelabel->setBackgroundMode( QWidget::PaletteBackground );
	timelabel->setFontPropagation( QWidget::NoChildren );
	timelabel->setPalettePropagation( QWidget::NoChildren );
	timelabel->setText( transl("Time:") );
	timelabel->setAlignment( 289 );
	timelabel->setMargin( -1 );

	QLabel* qtarch_Label_26;
	qtarch_Label_26 = new QLabel( this, "Label_26" );
	qtarch_Label_26->setGeometry( 10, 130, 80, 30 );
	qtarch_Label_26->setMinimumSize( 0, 0 );
	qtarch_Label_26->setMaximumSize( 32767, 32767 );
	qtarch_Label_26->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_26->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_26->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_26->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_26->setText( transl("DayLight:") );
	qtarch_Label_26->setAlignment( 289 );
	qtarch_Label_26->setMargin( -1 );

	QLabel* qtarch_Label_35;
	qtarch_Label_35 = new QLabel( this, "Label_35" );
	qtarch_Label_35->setGeometry( 110, 130, 70, 30 );
	qtarch_Label_35->setMinimumSize( 0, 0 );
	qtarch_Label_35->setMaximumSize( 32767, 32767 );
	qtarch_Label_35->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_35->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_35->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_35->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_35->setText( transl("Long.HMS:") );
	qtarch_Label_35->setAlignment( 289 );
	qtarch_Label_35->setMargin( -1 );

	QLabel* qtarch_Label_27;
	qtarch_Label_27 = new QLabel( this, "Label_27" );
	qtarch_Label_27->setGeometry( 10, 160, 80, 30 );
	qtarch_Label_27->setMinimumSize( 0, 0 );
	qtarch_Label_27->setMaximumSize( 32767, 32767 );
	qtarch_Label_27->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_27->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_27->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_27->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_27->setText( transl("Time zone:") );
	qtarch_Label_27->setAlignment( 289 );
	qtarch_Label_27->setMargin( -1 );

	QLabel* qtarch_Label_28;
	qtarch_Label_28 = new QLabel( this, "Label_28" );
	qtarch_Label_28->setGeometry( 10, 190, 80, 30 );
	qtarch_Label_28->setMinimumSize( 0, 0 );
	qtarch_Label_28->setMaximumSize( 32767, 32767 );
	qtarch_Label_28->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_28->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_28->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_28->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_28->setText( transl("Longitude:") );
	qtarch_Label_28->setAlignment( 289 );
	qtarch_Label_28->setMargin( -1 );

	QLabel* qtarch_Label_29;
	qtarch_Label_29 = new QLabel( this, "Label_29" );
	qtarch_Label_29->setGeometry( 10, 220, 80, 30 );
	qtarch_Label_29->setMinimumSize( 0, 0 );
	qtarch_Label_29->setMaximumSize( 32767, 32767 );
	qtarch_Label_29->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_29->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_29->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_29->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_29->setText( transl("Latitude:") );
	qtarch_Label_29->setAlignment( 289 );
	qtarch_Label_29->setMargin( -1 );

	namelabel = new QLabel( this, "Label_30" );
	namelabel->setGeometry( 10, 250, 80, 30 );
	namelabel->setMinimumSize( 0, 0 );
	namelabel->setMaximumSize( 32767, 32767 );
	namelabel->setFocusPolicy( QWidget::NoFocus );
	namelabel->setBackgroundMode( QWidget::PaletteBackground );
	namelabel->setFontPropagation( QWidget::NoChildren );
	namelabel->setPalettePropagation( QWidget::NoChildren );
	namelabel->setText( transl("Name:") );
	namelabel->setAlignment( 289 );
	namelabel->setMargin( -1 );

	localtionlabel = new QLabel( this, "Label_31" );
	localtionlabel->setGeometry( 10, 280, 80, 30 );
	localtionlabel->setMinimumSize( 0, 0 );
	localtionlabel->setMaximumSize( 32767, 32767 );
	localtionlabel->setFocusPolicy( QWidget::NoFocus );
	localtionlabel->setBackgroundMode( QWidget::PaletteBackground );
	localtionlabel->setFontPropagation( QWidget::NoChildren );
	localtionlabel->setPalettePropagation( QWidget::NoChildren );
	localtionlabel->setText( transl("Location:") );
	localtionlabel->setAlignment( 289 );
	localtionlabel->setMargin( -1 );

	Month = new QComboBox( FALSE, this, "ComboBox_3" );
	Month->setGeometry( 90, 10, 100, 30 );
	Month->setMinimumSize( 0, 0 );
	Month->setMaximumSize( 32767, 32767 );
	connect( Month, SIGNAL(activated(int)), SLOT(monthslot(int)) );
	Month->setFocusPolicy( QWidget::StrongFocus );
	Month->setBackgroundMode( QWidget::PaletteBackground );
	Month->setFontPropagation( QWidget::AllChildren );
	Month->setPalettePropagation( QWidget::AllChildren );
	Month->setSizeLimit( 5 );
	Month->setAutoResize( FALSE );
	Month->insertItem( transl("January") );
	Month->insertItem( transl("February") );
	Month->insertItem( transl("March") );
	Month->insertItem( transl("April") );
	Month->insertItem( transl("May") );
	Month->insertItem( transl("June") );
	Month->insertItem( transl("July") );
	Month->insertItem( transl("August") );
	Month->insertItem( transl("September") );
	Month->insertItem( transl("October") );
	Month->insertItem( transl("November") );
	Month->insertItem( transl("December") );

	TheDay = new myLineEdit( this, "LineEdit_14" );
	TheDay->setGeometry( 90, 40, 100, 30 );
	TheDay->setMinimumSize( 0, 0 );
	TheDay->setMaximumSize( 32767, 32767 );
	connect( TheDay, SIGNAL(returnPressed()), SLOT(dayslot()) );
	TheDay->setFocusPolicy( QWidget::StrongFocus );
	TheDay->setBackgroundMode( QWidget::PaletteBase );
	TheDay->setFontPropagation( QWidget::NoChildren );
	TheDay->setPalettePropagation( QWidget::NoChildren );
	TheDay->setText( "" );
	TheDay->setMaxLength( 32767 );
	TheDay->setEchoMode( myLineEdit::Normal );
	TheDay->setFrame( TRUE );

	Year = new myLineEdit( this, "LineEdit_15" );
	Year->setGeometry( 90, 70, 100, 30 );
	Year->setMinimumSize( 0, 0 );
	Year->setMaximumSize( 32767, 32767 );
	connect( Year, SIGNAL(returnPressed()), SLOT(yearslot()) );
	Year->setFocusPolicy( QWidget::StrongFocus );
	Year->setBackgroundMode( QWidget::PaletteBase );
	Year->setFontPropagation( QWidget::NoChildren );
	Year->setPalettePropagation( QWidget::NoChildren );
	Year->setText( "" );
	Year->setMaxLength( 32767 );
	Year->setEchoMode( myLineEdit::Normal );
	Year->setFrame( TRUE );

	Time = new myLineEdit( this, "LineEdit_16" );
	Time->setGeometry( 90, 100, 100, 30 );
	Time->setMinimumSize( 0, 0 );
	Time->setMaximumSize( 32767, 32767 );
	connect( Time, SIGNAL(returnPressed()), SLOT(timeslot()) );
	Time->setFocusPolicy( QWidget::StrongFocus );
	Time->setBackgroundMode( QWidget::PaletteBase );
	Time->setFontPropagation( QWidget::NoChildren );
	Time->setPalettePropagation( QWidget::NoChildren );
	Time->setText( "" );
	Time->setMaxLength( 32767 );
	Time->setEchoMode( myLineEdit::Normal );
	Time->setFrame( TRUE );

	Daylight = new QRadioButton( this, "RadioButton_1" );
	Daylight->setGeometry( 90, 130, 20, 30 );
	Daylight->setMinimumSize( 0, 0 );
	Daylight->setMaximumSize( 32767, 32767 );
	connect( Daylight, SIGNAL(toggled(bool)), SLOT(daylightslot(bool)) );
	Daylight->setFocusPolicy( QWidget::TabFocus );
	Daylight->setBackgroundMode( QWidget::PaletteBackground );
	Daylight->setFontPropagation( QWidget::NoChildren );
	Daylight->setPalettePropagation( QWidget::NoChildren );
	Daylight->setText( "" );
	Daylight->setAutoRepeat( FALSE );
	Daylight->setAutoResize( FALSE );

	LongHMS = new QRadioButton( this, "RadioButton_3" );
	LongHMS->setGeometry( 180, 130, 20, 30 );
	LongHMS->setMinimumSize( 0, 0 );
	LongHMS->setMaximumSize( 32767, 32767 );
	connect( LongHMS, SIGNAL(toggled(bool)), SLOT(longhmsslot(bool)) );
	LongHMS->setFocusPolicy( QWidget::TabFocus );
	LongHMS->setBackgroundMode( QWidget::PaletteBackground );
	LongHMS->setFontPropagation( QWidget::NoChildren );
	LongHMS->setPalettePropagation( QWidget::NoChildren );
	LongHMS->setText( "" );
	LongHMS->setAutoRepeat( FALSE );
	LongHMS->setAutoResize( FALSE );

	Timezone = new myLineEdit( this, "LineEdit_17" );
	Timezone->setGeometry( 90, 160, 100, 30 );
	Timezone->setMinimumSize( 0, 0 );
	Timezone->setMaximumSize( 32767, 32767 );
	connect( Timezone, SIGNAL(returnPressed()), SLOT(timezoneslot()) );
	Timezone->setFocusPolicy( QWidget::StrongFocus );
	Timezone->setBackgroundMode( QWidget::PaletteBase );
	Timezone->setFontPropagation( QWidget::NoChildren );
	Timezone->setPalettePropagation( QWidget::NoChildren );
	Timezone->setText( "" );
	Timezone->setMaxLength( 32767 );
	Timezone->setEchoMode( myLineEdit::Normal );
	Timezone->setFrame( TRUE );

	Longitude = new myLineEdit( this, "LineEdit_18" );
	Longitude->setGeometry( 90, 190, 100, 30 );
	Longitude->setMinimumSize( 0, 0 );
	Longitude->setMaximumSize( 32767, 32767 );
	connect( Longitude, SIGNAL(returnPressed()), SLOT(longitudeslot()) );
	Longitude->setFocusPolicy( QWidget::StrongFocus );
	Longitude->setBackgroundMode( QWidget::PaletteBase );
	Longitude->setFontPropagation( QWidget::NoChildren );
	Longitude->setPalettePropagation( QWidget::NoChildren );
	Longitude->setText( "" );
	Longitude->setMaxLength( 32767 );
	Longitude->setEchoMode( myLineEdit::Normal );
	Longitude->setFrame( TRUE );

	Latitude = new myLineEdit( this, "LineEdit_19" );
	Latitude->setGeometry( 90, 220, 100, 30 );
	Latitude->setMinimumSize( 0, 0 );
	Latitude->setMaximumSize( 32767, 32767 );
	connect( Latitude, SIGNAL(returnPressed()), SLOT(latitudeslot()) );
	Latitude->setFocusPolicy( QWidget::StrongFocus );
	Latitude->setBackgroundMode( QWidget::PaletteBase );
	Latitude->setFontPropagation( QWidget::NoChildren );
	Latitude->setPalettePropagation( QWidget::NoChildren );
	Latitude->setText( "" );
	Latitude->setMaxLength( 32767 );
	Latitude->setEchoMode( myLineEdit::Normal );
	Latitude->setFrame( TRUE );

	Name = new myLineEdit( this, "LineEdit_20" );
	Name->setGeometry( 90, 250, 220, 30 );
	Name->setMinimumSize( 0, 0 );
	Name->setMaximumSize( 32767, 32767 );
	connect( Name, SIGNAL(returnPressed()), SLOT(nameslot()) );
	Name->setFocusPolicy( QWidget::StrongFocus );
	Name->setBackgroundMode( QWidget::PaletteBase );
	Name->setFontPropagation( QWidget::NoChildren );
	Name->setPalettePropagation( QWidget::NoChildren );
	Name->setText( "" );
	Name->setMaxLength( 32767 );
	Name->setEchoMode( myLineEdit::Normal );
	Name->setFrame( TRUE );

	Location = new myLineEdit( this, "LineEdit_21" );
	Location->setGeometry( 90, 280, 220, 30 );
	Location->setMinimumSize( 0, 0 );
	Location->setMaximumSize( 32767, 32767 );
	connect( Location, SIGNAL(returnPressed()), SLOT(locationslot()) );
	Location->setFocusPolicy( QWidget::StrongFocus );
	Location->setBackgroundMode( QWidget::PaletteBase );
	Location->setFontPropagation( QWidget::NoChildren );
	Location->setPalettePropagation( QWidget::NoChildren );
	Location->setText( "" );
	Location->setMaxLength( 32767 );
	Location->setEchoMode( myLineEdit::Normal );
	Location->setFrame( TRUE );

	nowlabel = new QPushButton( this, "PushButton_11" );
	nowlabel->setGeometry( 210, 10, 100, 30 );
	nowlabel->setMinimumSize( 0, 0 );
	nowlabel->setMaximumSize( 32767, 32767 );
	connect( nowlabel, SIGNAL(clicked()), SLOT(nowslot()) );
	nowlabel->setFocusPolicy( QWidget::TabFocus );
	nowlabel->setBackgroundMode( QWidget::PaletteBackground );
	nowlabel->setFontPropagation( QWidget::NoChildren );
	nowlabel->setPalettePropagation( QWidget::NoChildren );
	nowlabel->setText( transl("Now") );
	nowlabel->setAutoRepeat( FALSE );
	nowlabel->setAutoResize( FALSE );

	previouslabel = new QPushButton( this, "PushButton_12" );
	previouslabel->setGeometry( 210, 50, 100, 30 );
	previouslabel->setMinimumSize( 0, 0 );
	previouslabel->setMaximumSize( 32767, 32767 );
	connect( previouslabel, SIGNAL(clicked()), SLOT(previousslot()) );
	previouslabel->setFocusPolicy( QWidget::TabFocus );
	previouslabel->setBackgroundMode( QWidget::PaletteBackground );
	previouslabel->setFontPropagation( QWidget::NoChildren );
	previouslabel->setPalettePropagation( QWidget::NoChildren );
	previouslabel->setText( transl("Previous") );
	previouslabel->setAutoRepeat( FALSE );
	previouslabel->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_13;
	qtarch_PushButton_13 = new QPushButton( this, "PushButton_13" );
	qtarch_PushButton_13->setGeometry( 210, 90, 100, 30 );
	qtarch_PushButton_13->setMinimumSize( 0, 0 );
	qtarch_PushButton_13->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_13, SIGNAL(clicked()), SLOT(timezonefileslot()) );
	qtarch_PushButton_13->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_13->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_13->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_13->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_13->setText( transl("Zoneinfo file") );
	qtarch_PushButton_13->setAutoRepeat( FALSE );
	qtarch_PushButton_13->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_16;
	qtarch_PushButton_16 = new QPushButton( this, "PushButton_16" );
	qtarch_PushButton_16->setGeometry( 237, 127, 38, 38 );
	qtarch_PushButton_16->setMinimumSize( 0, 0 );
	qtarch_PushButton_16->setMaximumSize( 38, 38 );
	{
	  extern QPixmap *kdeicon;
	  qtarch_PushButton_16->setPixmap( *kdeicon );
	  
	}
	connect( qtarch_PushButton_16, SIGNAL(clicked()), SLOT(settzslot()) );
	qtarch_PushButton_16->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_16->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_16->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_16->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_16->setAutoRepeat( FALSE );
	qtarch_PushButton_16->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_14;
	qtarch_PushButton_14 = new QPushButton( this, "PushButton_14" );
	qtarch_PushButton_14->setGeometry( 210, 170, 100, 30 );
	qtarch_PushButton_14->setMinimumSize( 0, 0 );
	qtarch_PushButton_14->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_14, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_14->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_14->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_14->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_14->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_14->setText( transl("Cancel") );
	qtarch_PushButton_14->setAutoRepeat( FALSE );
	qtarch_PushButton_14->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_15;
	qtarch_PushButton_15 = new QPushButton( this, "PushButton_15" );
	qtarch_PushButton_15->setGeometry( 210, 210, 100, 30 );
	qtarch_PushButton_15->setMinimumSize( 0, 0 );
	qtarch_PushButton_15->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_15, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_15->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_15->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_15->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_15->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_15->setText( transl("OK") );
	qtarch_PushButton_15->setAutoRepeat( FALSE );
	qtarch_PushButton_15->setAutoResize( FALSE );

	Errors = new QLabel( this, "Label_32" );
	Errors->setGeometry( 10, 320, 300, 30 );
	Errors->setMinimumSize( 0, 0 );
	Errors->setMaximumSize( 32767, 32767 );
	Errors->setFocusPolicy( QWidget::NoFocus );
	Errors->setBackgroundMode( QWidget::PaletteBackground );
	Errors->setFontPropagation( QWidget::NoChildren );
	Errors->setPalettePropagation( QWidget::NoChildren );
	Errors->setFrameStyle( 50 );
	Errors->setText( "" );
	Errors->setAlignment( 289 );
	Errors->setMargin( -1 );

	commentlabel = new QLabel( this, "Label_34" );
	commentlabel->setGeometry( 350, 10, 90, 30 );
	commentlabel->setMinimumSize( 0, 0 );
	commentlabel->setMaximumSize( 32767, 32767 );
	commentlabel->setFocusPolicy( QWidget::NoFocus );
	commentlabel->setBackgroundMode( QWidget::PaletteBackground );
	commentlabel->setFontPropagation( QWidget::NoChildren );
	commentlabel->setPalettePropagation( QWidget::NoChildren );
	commentlabel->setText( transl("Comment") );
	commentlabel->setAlignment( 289 );
	commentlabel->setMargin( -1 );

	Comment = new QMultiLineEdit( this, "MultiLineEdit_2" );
	Comment->setGeometry( 320, 50, 120, 300 );
	Comment->setMinimumSize( 0, 0 );
	Comment->setMaximumSize( 32767, 32767 );
	Comment->setFocusPolicy( QWidget::StrongFocus );
	Comment->setBackgroundMode( QWidget::PaletteBase );
	Comment->setFontPropagation( QWidget::SameFont );
	Comment->setPalettePropagation( QWidget::SameFont );
	Comment->insertLine( "" );
	Comment->setReadOnly( FALSE );
	Comment->setOverwriteMode( FALSE );

	resize( 450,360 );
	setMinimumSize( 450, 360 );
	setMaximumSize( 32767, 32767 );
}


AstroInfoData::~AstroInfoData()
{
}
void AstroInfoData::monthslot(int)
{
}
void AstroInfoData::dayslot()
{
}
void AstroInfoData::yearslot()
{
}
void AstroInfoData::timeslot()
{
}
void AstroInfoData::daylightslot(bool)
{
}
void AstroInfoData::longhmsslot(bool)
{
}
void AstroInfoData::timezoneslot()
{
}
void AstroInfoData::longitudeslot()
{
}
void AstroInfoData::latitudeslot()
{
}
void AstroInfoData::nameslot()
{
}
void AstroInfoData::locationslot()
{
}
void AstroInfoData::nowslot()
{
}
void AstroInfoData::previousslot()
{
}
void AstroInfoData::timezonefileslot()
{
}
void AstroInfoData::settzslot()
{
}
void AstroInfoData::cancelslot()
{
}
void AstroInfoData::okslot()
{
}
