/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroSetAspectsData.cpp
	Last generated: Fri Oct 22 14:36:00 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AstroSetAspectsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

AstroSetAspectsData::AstroSetAspectsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	a[0] = new AspectSet( this, "User_1" );
	a[0]->setGeometry( 10, 40, 280, 40 );
	a[0]->setMinimumSize( 0, 0 );
	a[0]->setMaximumSize( 32767, 32767 );
	a[0]->setFocusPolicy( QWidget::NoFocus );
	a[0]->setBackgroundMode( QWidget::PaletteBackground );
	a[0]->setFontPropagation( QWidget::NoChildren );
	a[0]->setPalettePropagation( QWidget::NoChildren );

	a[1] = new AspectSet( this, "User_2" );
	a[1]->setGeometry( 10, 80, 280, 40 );
	a[1]->setMinimumSize( 0, 0 );
	a[1]->setMaximumSize( 32767, 32767 );
	a[1]->setFocusPolicy( QWidget::NoFocus );
	a[1]->setBackgroundMode( QWidget::PaletteBackground );
	a[1]->setFontPropagation( QWidget::NoChildren );
	a[1]->setPalettePropagation( QWidget::NoChildren );

	a[2] = new AspectSet( this, "User_3" );
	a[2]->setGeometry( 10, 120, 280, 40 );
	a[2]->setMinimumSize( 0, 0 );
	a[2]->setMaximumSize( 32767, 32767 );
	a[2]->setFocusPolicy( QWidget::NoFocus );
	a[2]->setBackgroundMode( QWidget::PaletteBackground );
	a[2]->setFontPropagation( QWidget::NoChildren );
	a[2]->setPalettePropagation( QWidget::NoChildren );

	a[3] = new AspectSet( this, "User_4" );
	a[3]->setGeometry( 10, 160, 280, 40 );
	a[3]->setMinimumSize( 0, 0 );
	a[3]->setMaximumSize( 32767, 32767 );
	a[3]->setFocusPolicy( QWidget::NoFocus );
	a[3]->setBackgroundMode( QWidget::PaletteBackground );
	a[3]->setFontPropagation( QWidget::NoChildren );
	a[3]->setPalettePropagation( QWidget::NoChildren );

	a[4] = new AspectSet( this, "User_5" );
	a[4]->setGeometry( 10, 200, 280, 40 );
	a[4]->setMinimumSize( 0, 0 );
	a[4]->setMaximumSize( 32767, 32767 );
	a[4]->setFocusPolicy( QWidget::NoFocus );
	a[4]->setBackgroundMode( QWidget::PaletteBackground );
	a[4]->setFontPropagation( QWidget::NoChildren );
	a[4]->setPalettePropagation( QWidget::NoChildren );

	a[5] = new AspectSet( this, "User_6" );
	a[5]->setGeometry( 10, 240, 280, 40 );
	a[5]->setMinimumSize( 0, 0 );
	a[5]->setMaximumSize( 32767, 32767 );
	a[5]->setFocusPolicy( QWidget::NoFocus );
	a[5]->setBackgroundMode( QWidget::PaletteBackground );
	a[5]->setFontPropagation( QWidget::NoChildren );
	a[5]->setPalettePropagation( QWidget::NoChildren );

	a[6] = new AspectSet( this, "User_7" );
	a[6]->setGeometry( 10, 280, 280, 40 );
	a[6]->setMinimumSize( 0, 0 );
	a[6]->setMaximumSize( 32767, 32767 );
	a[6]->setFocusPolicy( QWidget::NoFocus );
	a[6]->setBackgroundMode( QWidget::PaletteBackground );
	a[6]->setFontPropagation( QWidget::NoChildren );
	a[6]->setPalettePropagation( QWidget::NoChildren );

	a[7] = new AspectSet( this, "User_8" );
	a[7]->setGeometry( 10, 320, 280, 40 );
	a[7]->setMinimumSize( 0, 0 );
	a[7]->setMaximumSize( 32767, 32767 );
	a[7]->setFocusPolicy( QWidget::NoFocus );
	a[7]->setBackgroundMode( QWidget::PaletteBackground );
	a[7]->setFontPropagation( QWidget::NoChildren );
	a[7]->setPalettePropagation( QWidget::NoChildren );

	a[8] = new AspectSet( this, "User_9" );
	a[8]->setGeometry( 10, 360, 280, 40 );
	a[8]->setMinimumSize( 0, 0 );
	a[8]->setMaximumSize( 32767, 32767 );
	a[8]->setFocusPolicy( QWidget::NoFocus );
	a[8]->setBackgroundMode( QWidget::PaletteBackground );
	a[8]->setFontPropagation( QWidget::NoChildren );
	a[8]->setPalettePropagation( QWidget::NoChildren );

	a[9] = new AspectSet( this, "User_10" );
	a[9]->setGeometry( 300, 40, 280, 40 );
	a[9]->setMinimumSize( 0, 0 );
	a[9]->setMaximumSize( 32767, 32767 );
	a[9]->setFocusPolicy( QWidget::NoFocus );
	a[9]->setBackgroundMode( QWidget::PaletteBackground );
	a[9]->setFontPropagation( QWidget::NoChildren );
	a[9]->setPalettePropagation( QWidget::NoChildren );

	a[10] = new AspectSet( this, "User_11" );
	a[10]->setGeometry( 300, 80, 280, 40 );
	a[10]->setMinimumSize( 0, 0 );
	a[10]->setMaximumSize( 32767, 32767 );
	a[10]->setFocusPolicy( QWidget::NoFocus );
	a[10]->setBackgroundMode( QWidget::PaletteBackground );
	a[10]->setFontPropagation( QWidget::NoChildren );
	a[10]->setPalettePropagation( QWidget::NoChildren );

	a[11] = new AspectSet( this, "User_12" );
	a[11]->setGeometry( 300, 120, 280, 40 );
	a[11]->setMinimumSize( 0, 0 );
	a[11]->setMaximumSize( 32767, 32767 );
	a[11]->setFocusPolicy( QWidget::NoFocus );
	a[11]->setBackgroundMode( QWidget::PaletteBackground );
	a[11]->setFontPropagation( QWidget::NoChildren );
	a[11]->setPalettePropagation( QWidget::NoChildren );

	a[12] = new AspectSet( this, "User_13" );
	a[12]->setGeometry( 300, 160, 280, 40 );
	a[12]->setMinimumSize( 0, 0 );
	a[12]->setMaximumSize( 32767, 32767 );
	a[12]->setFocusPolicy( QWidget::NoFocus );
	a[12]->setBackgroundMode( QWidget::PaletteBackground );
	a[12]->setFontPropagation( QWidget::NoChildren );
	a[12]->setPalettePropagation( QWidget::NoChildren );

	a[13] = new AspectSet( this, "User_14" );
	a[13]->setGeometry( 300, 200, 280, 40 );
	a[13]->setMinimumSize( 0, 0 );
	a[13]->setMaximumSize( 32767, 32767 );
	a[13]->setFocusPolicy( QWidget::NoFocus );
	a[13]->setBackgroundMode( QWidget::PaletteBackground );
	a[13]->setFontPropagation( QWidget::NoChildren );
	a[13]->setPalettePropagation( QWidget::NoChildren );

	a[14] = new AspectSet( this, "User_15" );
	a[14]->setGeometry( 300, 240, 280, 40 );
	a[14]->setMinimumSize( 0, 0 );
	a[14]->setMaximumSize( 32767, 32767 );
	a[14]->setFocusPolicy( QWidget::NoFocus );
	a[14]->setBackgroundMode( QWidget::PaletteBackground );
	a[14]->setFontPropagation( QWidget::NoChildren );
	a[14]->setPalettePropagation( QWidget::NoChildren );

	a[15] = new AspectSet( this, "User_16" );
	a[15]->setGeometry( 300, 280, 280, 40 );
	a[15]->setMinimumSize( 0, 0 );
	a[15]->setMaximumSize( 32767, 32767 );
	a[15]->setFocusPolicy( QWidget::NoFocus );
	a[15]->setBackgroundMode( QWidget::PaletteBackground );
	a[15]->setFontPropagation( QWidget::NoChildren );
	a[15]->setPalettePropagation( QWidget::NoChildren );

	a[16] = new AspectSet( this, "User_17" );
	a[16]->setGeometry( 300, 320, 280, 40 );
	a[16]->setMinimumSize( 0, 0 );
	a[16]->setMaximumSize( 32767, 32767 );
	a[16]->setFocusPolicy( QWidget::NoFocus );
	a[16]->setBackgroundMode( QWidget::PaletteBackground );
	a[16]->setFontPropagation( QWidget::NoChildren );
	a[16]->setPalettePropagation( QWidget::NoChildren );

	a[17] = new AspectSet( this, "User_18" );
	a[17]->setGeometry( 300, 360, 280, 40 );
	a[17]->setMinimumSize( 0, 0 );
	a[17]->setMaximumSize( 32767, 32767 );
	a[17]->setFocusPolicy( QWidget::NoFocus );
	a[17]->setBackgroundMode( QWidget::PaletteBackground );
	a[17]->setFontPropagation( QWidget::NoChildren );
	a[17]->setPalettePropagation( QWidget::NoChildren );

	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 10, 10, 280, 30 );
	qtarch_Label_1->setMinimumSize( 0, 0 );
	qtarch_Label_1->setMaximumSize( 32767, 32767 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( "                               Orb         Angle      Influ" );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 300, 10, 280, 30 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( "                               Orb         Angle      Influ" );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 10, 410, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(restrictallslot()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( transl("Restrict All") );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 120, 410, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 0, 0 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(unrestrictallslot()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( transl("Unrestrict All") );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_3;
	qtarch_PushButton_3 = new QPushButton( this, "PushButton_3" );
	qtarch_PushButton_3->setGeometry( 230, 410, 100, 30 );
	qtarch_PushButton_3->setMinimumSize( 0, 0 );
	qtarch_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_3, SIGNAL(clicked()), SLOT(togglemajorslot()) );
	qtarch_PushButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setText( transl("Toggle Majors") );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_4;
	qtarch_PushButton_4 = new QPushButton( this, "PushButton_4" );
	qtarch_PushButton_4->setGeometry( 370, 410, 100, 30 );
	qtarch_PushButton_4->setMinimumSize( 0, 0 );
	qtarch_PushButton_4->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_4, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setText( transl("Cancel") );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_5;
	qtarch_PushButton_5 = new QPushButton( this, "PushButton_5" );
	qtarch_PushButton_5->setGeometry( 480, 410, 100, 30 );
	qtarch_PushButton_5->setMinimumSize( 0, 0 );
	qtarch_PushButton_5->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_5, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_5->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_5->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_5->setText( transl("OK") );
	qtarch_PushButton_5->setAutoRepeat( FALSE );
	qtarch_PushButton_5->setAutoResize( FALSE );

	resize( 590,450 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


AstroSetAspectsData::~AstroSetAspectsData()
{
}
void AstroSetAspectsData::restrictallslot()
{
}
void AstroSetAspectsData::unrestrictallslot()
{
}
void AstroSetAspectsData::togglemajorslot()
{
}
void AstroSetAspectsData::cancelslot()
{
}
void AstroSetAspectsData::okslot()
{
}
