/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroObjectSetData.cpp
	Last generated: Sat Oct 23 14:39:10 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AstroObjectSetData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>

AstroObjectSetData::AstroObjectSetData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	o[0] = new ObjectSet( this, "User_1" );
	o[0]->setGeometry( 10, 40, 290, 40 );
	o[0]->setMinimumSize( 0, 0 );
	o[0]->setMaximumSize( 32767, 32767 );
	o[0]->setFocusPolicy( QWidget::NoFocus );
	o[0]->setBackgroundMode( QWidget::PaletteBackground );
	o[0]->setFontPropagation( QWidget::NoChildren );
	o[0]->setPalettePropagation( QWidget::NoChildren );

	o[1] = new ObjectSet( this, "User_2" );
	o[1]->setGeometry( 10, 80, 290, 40 );
	o[1]->setMinimumSize( 0, 0 );
	o[1]->setMaximumSize( 32767, 32767 );
	o[1]->setFocusPolicy( QWidget::NoFocus );
	o[1]->setBackgroundMode( QWidget::PaletteBackground );
	o[1]->setFontPropagation( QWidget::NoChildren );
	o[1]->setPalettePropagation( QWidget::NoChildren );

	o[2] = new ObjectSet( this, "User_3" );
	o[2]->setGeometry( 10, 120, 290, 40 );
	o[2]->setMinimumSize( 0, 0 );
	o[2]->setMaximumSize( 32767, 32767 );
	o[2]->setFocusPolicy( QWidget::NoFocus );
	o[2]->setBackgroundMode( QWidget::PaletteBackground );
	o[2]->setFontPropagation( QWidget::NoChildren );
	o[2]->setPalettePropagation( QWidget::NoChildren );

	o[3] = new ObjectSet( this, "User_4" );
	o[3]->setGeometry( 10, 160, 290, 40 );
	o[3]->setMinimumSize( 0, 0 );
	o[3]->setMaximumSize( 32767, 32767 );
	o[3]->setFocusPolicy( QWidget::NoFocus );
	o[3]->setBackgroundMode( QWidget::PaletteBackground );
	o[3]->setFontPropagation( QWidget::NoChildren );
	o[3]->setPalettePropagation( QWidget::NoChildren );

	o[4] = new ObjectSet( this, "User_5" );
	o[4]->setGeometry( 10, 200, 290, 40 );
	o[4]->setMinimumSize( 0, 0 );
	o[4]->setMaximumSize( 32767, 32767 );
	o[4]->setFocusPolicy( QWidget::NoFocus );
	o[4]->setBackgroundMode( QWidget::PaletteBackground );
	o[4]->setFontPropagation( QWidget::NoChildren );
	o[4]->setPalettePropagation( QWidget::NoChildren );

	o[5] = new ObjectSet( this, "User_6" );
	o[5]->setGeometry( 10, 240, 290, 40 );
	o[5]->setMinimumSize( 0, 0 );
	o[5]->setMaximumSize( 32767, 32767 );
	o[5]->setFocusPolicy( QWidget::NoFocus );
	o[5]->setBackgroundMode( QWidget::PaletteBackground );
	o[5]->setFontPropagation( QWidget::NoChildren );
	o[5]->setPalettePropagation( QWidget::NoChildren );

	o[6] = new ObjectSet( this, "User_7" );
	o[6]->setGeometry( 10, 280, 290, 40 );
	o[6]->setMinimumSize( 0, 0 );
	o[6]->setMaximumSize( 32767, 32767 );
	o[6]->setFocusPolicy( QWidget::NoFocus );
	o[6]->setBackgroundMode( QWidget::PaletteBackground );
	o[6]->setFontPropagation( QWidget::NoChildren );
	o[6]->setPalettePropagation( QWidget::NoChildren );

	o[7] = new ObjectSet( this, "User_8" );
	o[7]->setGeometry( 10, 320, 290, 40 );
	o[7]->setMinimumSize( 0, 0 );
	o[7]->setMaximumSize( 32767, 32767 );
	o[7]->setFocusPolicy( QWidget::NoFocus );
	o[7]->setBackgroundMode( QWidget::PaletteBackground );
	o[7]->setFontPropagation( QWidget::NoChildren );
	o[7]->setPalettePropagation( QWidget::NoChildren );

	o[8] = new ObjectSet( this, "User_9" );
	o[8]->setGeometry( 10, 360, 290, 40 );
	o[8]->setMinimumSize( 0, 0 );
	o[8]->setMaximumSize( 32767, 32767 );
	o[8]->setFocusPolicy( QWidget::NoFocus );
	o[8]->setBackgroundMode( QWidget::PaletteBackground );
	o[8]->setFontPropagation( QWidget::NoChildren );
	o[8]->setPalettePropagation( QWidget::NoChildren );

	o[9] = new ObjectSet( this, "User_10" );
	o[9]->setGeometry( 10, 400, 290, 40 );
	o[9]->setMinimumSize( 0, 0 );
	o[9]->setMaximumSize( 32767, 32767 );
	o[9]->setFocusPolicy( QWidget::NoFocus );
	o[9]->setBackgroundMode( QWidget::PaletteBackground );
	o[9]->setFontPropagation( QWidget::NoChildren );
	o[9]->setPalettePropagation( QWidget::NoChildren );

	o[10] = new ObjectSet( this, "User_11" );
	o[10]->setGeometry( 310, 40, 290, 40 );
	o[10]->setMinimumSize( 0, 0 );
	o[10]->setMaximumSize( 32767, 32767 );
	o[10]->setFocusPolicy( QWidget::NoFocus );
	o[10]->setBackgroundMode( QWidget::PaletteBackground );
	o[10]->setFontPropagation( QWidget::NoChildren );
	o[10]->setPalettePropagation( QWidget::NoChildren );

	o[11] = new ObjectSet( this, "User_12" );
	o[11]->setGeometry( 310, 80, 290, 40 );
	o[11]->setMinimumSize( 0, 0 );
	o[11]->setMaximumSize( 32767, 32767 );
	o[11]->setFocusPolicy( QWidget::NoFocus );
	o[11]->setBackgroundMode( QWidget::PaletteBackground );
	o[11]->setFontPropagation( QWidget::NoChildren );
	o[11]->setPalettePropagation( QWidget::NoChildren );

	o[12] = new ObjectSet( this, "User_13" );
	o[12]->setGeometry( 310, 120, 290, 40 );
	o[12]->setMinimumSize( 0, 0 );
	o[12]->setMaximumSize( 32767, 32767 );
	o[12]->setFocusPolicy( QWidget::NoFocus );
	o[12]->setBackgroundMode( QWidget::PaletteBackground );
	o[12]->setFontPropagation( QWidget::NoChildren );
	o[12]->setPalettePropagation( QWidget::NoChildren );

	o[13] = new ObjectSet( this, "User_14" );
	o[13]->setGeometry( 310, 160, 290, 40 );
	o[13]->setMinimumSize( 0, 0 );
	o[13]->setMaximumSize( 32767, 32767 );
	o[13]->setFocusPolicy( QWidget::NoFocus );
	o[13]->setBackgroundMode( QWidget::PaletteBackground );
	o[13]->setFontPropagation( QWidget::NoChildren );
	o[13]->setPalettePropagation( QWidget::NoChildren );

	o[13] = new ObjectSet( this, "User_15" );
	o[13]->setGeometry( 310, 160, 290, 40 );
	o[13]->setMinimumSize( 0, 0 );
	o[13]->setMaximumSize( 32767, 32767 );
	o[13]->setFocusPolicy( QWidget::NoFocus );
	o[13]->setBackgroundMode( QWidget::PaletteBackground );
	o[13]->setFontPropagation( QWidget::NoChildren );
	o[13]->setPalettePropagation( QWidget::NoChildren );

	o[13] = new ObjectSet( this, "User_16" );
	o[13]->setGeometry( 310, 160, 290, 40 );
	o[13]->setMinimumSize( 0, 0 );
	o[13]->setMaximumSize( 32767, 32767 );
	o[13]->setFocusPolicy( QWidget::NoFocus );
	o[13]->setBackgroundMode( QWidget::PaletteBackground );
	o[13]->setFontPropagation( QWidget::NoChildren );
	o[13]->setPalettePropagation( QWidget::NoChildren );

	o[14] = new ObjectSet( this, "User_17" );
	o[14]->setGeometry( 310, 200, 290, 40 );
	o[14]->setMinimumSize( 0, 0 );
	o[14]->setMaximumSize( 32767, 32767 );
	o[14]->setFocusPolicy( QWidget::NoFocus );
	o[14]->setBackgroundMode( QWidget::PaletteBackground );
	o[14]->setFontPropagation( QWidget::NoChildren );
	o[14]->setPalettePropagation( QWidget::NoChildren );

	o[15] = new ObjectSet( this, "User_18" );
	o[15]->setGeometry( 310, 240, 290, 40 );
	o[15]->setMinimumSize( 0, 0 );
	o[15]->setMaximumSize( 32767, 32767 );
	o[15]->setFocusPolicy( QWidget::NoFocus );
	o[15]->setBackgroundMode( QWidget::PaletteBackground );
	o[15]->setFontPropagation( QWidget::NoChildren );
	o[15]->setPalettePropagation( QWidget::NoChildren );

	o[16] = new ObjectSet( this, "User_19" );
	o[16]->setGeometry( 310, 280, 290, 40 );
	o[16]->setMinimumSize( 0, 0 );
	o[16]->setMaximumSize( 32767, 32767 );
	o[16]->setFocusPolicy( QWidget::NoFocus );
	o[16]->setBackgroundMode( QWidget::PaletteBackground );
	o[16]->setFontPropagation( QWidget::NoChildren );
	o[16]->setPalettePropagation( QWidget::NoChildren );

	o[17] = new ObjectSet( this, "User_20" );
	o[17]->setGeometry( 310, 320, 290, 40 );
	o[17]->setMinimumSize( 0, 0 );
	o[17]->setMaximumSize( 32767, 32767 );
	o[17]->setFocusPolicy( QWidget::NoFocus );
	o[17]->setBackgroundMode( QWidget::PaletteBackground );
	o[17]->setFontPropagation( QWidget::NoChildren );
	o[17]->setPalettePropagation( QWidget::NoChildren );

	o[18] = new ObjectSet( this, "User_21" );
	o[18]->setGeometry( 310, 360, 290, 40 );
	o[18]->setMinimumSize( 0, 0 );
	o[18]->setMaximumSize( 32767, 32767 );
	o[18]->setFocusPolicy( QWidget::NoFocus );
	o[18]->setBackgroundMode( QWidget::PaletteBackground );
	o[18]->setFontPropagation( QWidget::NoChildren );
	o[18]->setPalettePropagation( QWidget::NoChildren );

	o[19] = new ObjectSet( this, "User_22" );
	o[19]->setGeometry( 310, 400, 290, 40 );
	o[19]->setMinimumSize( 0, 0 );
	o[19]->setMaximumSize( 32767, 32767 );
	o[19]->setFocusPolicy( QWidget::NoFocus );
	o[19]->setBackgroundMode( QWidget::PaletteBackground );
	o[19]->setFontPropagation( QWidget::NoChildren );
	o[19]->setPalettePropagation( QWidget::NoChildren );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 10, 10, 290, 20 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( "                            Max Orb      Add    Influence" );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 310, 10, 290, 20 );
	qtarch_Label_3->setMinimumSize( 0, 0 );
	qtarch_Label_3->setMaximumSize( 32767, 32767 );
	qtarch_Label_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_3->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_3->setText( "                            Max Orb      Add    Influence" );
	qtarch_Label_3->setAlignment( 289 );
	qtarch_Label_3->setMargin( -1 );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 310, 450, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( transl("Cancel") );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 500, 450, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 0, 0 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( transl("OK") );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	resize( 610,490 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


AstroObjectSetData::~AstroObjectSetData()
{
}
void AstroObjectSetData::cancelslot()
{
}
void AstroObjectSetData::okslot()
{
}
