/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroProgressData.h
	Last generated: Sat Nov 6 16:01:24 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AstroProgressData_included
#define AstroProgressData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include "myLineEdit.h"
#include <qcombo.h>
#include "tr.h"

class AstroProgressData : public QDialog
{
    Q_OBJECT

public:

    AstroProgressData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AstroProgressData();

public slots:


protected slots:

    virtual void timeslot();
    virtual void okslot();
    virtual void nowslot();
    virtual void progsetslot(int);
    virtual void dayslot();
    virtual void cancelslot();
    virtual void degperdayslot(int);
    virtual void yearslot();

protected:
    QButtonGroup* ProgSet;
    QCheckBox* DoProg;
    QComboBox* Month;
    myLineEdit* TheDay;
    myLineEdit* Year;
    myLineEdit* Time;
    QComboBox* DegPerDay;

};

#endif // AstroProgressData_included
