/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroTransitsData.cpp
	Last generated: Wed Nov 3 15:23:50 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "AstroTransitsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qbttngrp.h>
#include <qpushbt.h>
#include <qradiobt.h>

AstroTransitsData::AstroTransitsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	SearchForHits = new QButtonGroup( this, "ButtonGroup_13" );
	SearchForHits->setGeometry( 250, 20, 160, 130 );
	SearchForHits->setMinimumSize( 0, 0 );
	SearchForHits->setMaximumSize( 32767, 32767 );
	connect( SearchForHits, SIGNAL(clicked(int)), SLOT(searchforhitsslot(int)) );
	SearchForHits->setFocusPolicy( QWidget::NoFocus );
	SearchForHits->setBackgroundMode( QWidget::PaletteBackground );
	SearchForHits->setFontPropagation( QWidget::NoChildren );
	SearchForHits->setPalettePropagation( QWidget::NoChildren );
	SearchForHits->setFrameStyle( 49 );
	SearchForHits->setTitle( transl("Search for hits over") );
	SearchForHits->setAlignment( 1 );

	QButtonGroup* qtarch_ButtonGroup_12;
	qtarch_ButtonGroup_12 = new QButtonGroup( this, "ButtonGroup_12" );
	qtarch_ButtonGroup_12->setGeometry( 10, 180, 180, 110 );
	qtarch_ButtonGroup_12->setMinimumSize( 0, 0 );
	qtarch_ButtonGroup_12->setMaximumSize( 32767, 32767 );
	qtarch_ButtonGroup_12->setFocusPolicy( QWidget::NoFocus );
	qtarch_ButtonGroup_12->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_ButtonGroup_12->setFontPropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_12->setPalettePropagation( QWidget::NoChildren );
	qtarch_ButtonGroup_12->setFrameStyle( 49 );
	qtarch_ButtonGroup_12->setTitle( transl("Do transit for") );
	qtarch_ButtonGroup_12->setAlignment( 1 );

	TransType = new QButtonGroup( this, "ButtonGroup_1" );
	TransType->setGeometry( 10, 10, 210, 130 );
	TransType->setMinimumSize( 0, 0 );
	TransType->setMaximumSize( 32767, 32767 );
	connect( TransType, SIGNAL(clicked(int)), SLOT(transtypeslot(int)) );
	TransType->setFocusPolicy( QWidget::NoFocus );
	TransType->setBackgroundMode( QWidget::PaletteBackground );
	TransType->setFontPropagation( QWidget::NoChildren );
	TransType->setPalettePropagation( QWidget::NoChildren );
	TransType->setFrameStyle( 49 );
	TransType->setTitle( transl("Transit Type") );
	TransType->setAlignment( 1 );

	QRadioButton* qtarch_RadioButton_1;
	qtarch_RadioButton_1 = new QRadioButton( this, "RadioButton_1" );
	qtarch_RadioButton_1->setGeometry( 20, 30, 190, 20 );
	qtarch_RadioButton_1->setMinimumSize( 0, 0 );
	qtarch_RadioButton_1->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_1->setText( transl("None") );
	qtarch_RadioButton_1->setAutoRepeat( FALSE );
	qtarch_RadioButton_1->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_2;
	qtarch_RadioButton_2 = new QRadioButton( this, "RadioButton_2" );
	qtarch_RadioButton_2->setGeometry( 20, 50, 190, 20 );
	qtarch_RadioButton_2->setMinimumSize( 0, 0 );
	qtarch_RadioButton_2->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_2->setText( transl("Transit to transit hits") );
	qtarch_RadioButton_2->setAutoRepeat( FALSE );
	qtarch_RadioButton_2->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_3;
	qtarch_RadioButton_3 = new QRadioButton( this, "RadioButton_3" );
	qtarch_RadioButton_3->setGeometry( 20, 70, 190, 20 );
	qtarch_RadioButton_3->setMinimumSize( 0, 0 );
	qtarch_RadioButton_3->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_3->setText( transl("Transit to transit influence") );
	qtarch_RadioButton_3->setAutoRepeat( FALSE );
	qtarch_RadioButton_3->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_4;
	qtarch_RadioButton_4 = new QRadioButton( this, "RadioButton_4" );
	qtarch_RadioButton_4->setGeometry( 20, 90, 190, 20 );
	qtarch_RadioButton_4->setMinimumSize( 0, 0 );
	qtarch_RadioButton_4->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_4->setText( transl("Transit to natal hits") );
	qtarch_RadioButton_4->setAutoRepeat( FALSE );
	qtarch_RadioButton_4->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_5;
	qtarch_RadioButton_5 = new QRadioButton( this, "RadioButton_5" );
	qtarch_RadioButton_5->setGeometry( 20, 110, 190, 20 );
	qtarch_RadioButton_5->setMinimumSize( 0, 0 );
	qtarch_RadioButton_5->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_5->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_5->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_5->setText( transl("Transit to natal influence") );
	qtarch_RadioButton_5->setAutoRepeat( FALSE );
	qtarch_RadioButton_5->setAutoResize( FALSE );

	Progress = new QCheckBox( this, "CheckBox_17" );
	Progress->setGeometry( 10, 150, 210, 20 );
	Progress->setMinimumSize( 0, 0 );
	Progress->setMaximumSize( 32767, 32767 );
	Progress->setFocusPolicy( QWidget::TabFocus );
	Progress->setBackgroundMode( QWidget::PaletteBackground );
	Progress->setFontPropagation( QWidget::NoChildren );
	Progress->setPalettePropagation( QWidget::NoChildren );
	Progress->setText( transl("Progress instead of transit") );
	Progress->setAutoRepeat( FALSE );
	Progress->setAutoResize( FALSE );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 20, 200, 70, 20 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( transl("Month") );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 20, 220, 70, 20 );
	qtarch_Label_3->setMinimumSize( 0, 0 );
	qtarch_Label_3->setMaximumSize( 32767, 32767 );
	qtarch_Label_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_3->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_3->setText( transl("Day") );
	qtarch_Label_3->setAlignment( 289 );
	qtarch_Label_3->setMargin( -1 );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 20, 240, 70, 20 );
	qtarch_Label_4->setMinimumSize( 0, 0 );
	qtarch_Label_4->setMaximumSize( 32767, 32767 );
	qtarch_Label_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_4->setText( transl("Year") );
	qtarch_Label_4->setAlignment( 289 );
	qtarch_Label_4->setMargin( -1 );

	QLabel* qtarch_Label_5;
	qtarch_Label_5 = new QLabel( this, "Label_5" );
	qtarch_Label_5->setGeometry( 20, 260, 70, 20 );
	qtarch_Label_5->setMinimumSize( 0, 0 );
	qtarch_Label_5->setMaximumSize( 32767, 32767 );
	qtarch_Label_5->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_5->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_5->setText( transl("Time") );
	qtarch_Label_5->setAlignment( 289 );
	qtarch_Label_5->setMargin( -1 );

	Month = new QComboBox( FALSE, this, "ComboBox_1" );
	Month->setGeometry( 90, 200, 90, 20 );
	Month->setMinimumSize( 0, 0 );
	Month->setMaximumSize( 32767, 32767 );
	Month->setFocusPolicy( QWidget::StrongFocus );
	Month->setBackgroundMode( QWidget::PaletteBackground );
	Month->setFontPropagation( QWidget::AllChildren );
	Month->setPalettePropagation( QWidget::AllChildren );
	Month->setSizeLimit( 10 );
	Month->setAutoResize( FALSE );

	TheDay = new myLineEdit( this, "LineEdit_2" );
	TheDay->setGeometry( 90, 220, 90, 20 );
	TheDay->setMinimumSize( 0, 0 );
	TheDay->setMaximumSize( 32767, 32767 );
	connect( TheDay, SIGNAL(returnPressed()), SLOT(dayslot()) );
	TheDay->setFocusPolicy( QWidget::StrongFocus );
	TheDay->setBackgroundMode( QWidget::PaletteBase );
	TheDay->setFontPropagation( QWidget::NoChildren );
	TheDay->setPalettePropagation( QWidget::NoChildren );
	TheDay->setText( "" );
	TheDay->setMaxLength( 32767 );
	TheDay->setEchoMode( myLineEdit::Normal );
	TheDay->setFrame( TRUE );

	Year = new myLineEdit( this, "LineEdit_3" );
	Year->setGeometry( 90, 240, 90, 20 );
	Year->setMinimumSize( 0, 0 );
	Year->setMaximumSize( 32767, 32767 );
	connect( Year, SIGNAL(returnPressed()), SLOT(yearslot()) );
	Year->setFocusPolicy( QWidget::StrongFocus );
	Year->setBackgroundMode( QWidget::PaletteBase );
	Year->setFontPropagation( QWidget::NoChildren );
	Year->setPalettePropagation( QWidget::NoChildren );
	Year->setText( "" );
	Year->setMaxLength( 32767 );
	Year->setEchoMode( myLineEdit::Normal );
	Year->setFrame( TRUE );

	Time = new myLineEdit( this, "LineEdit_4" );
	Time->setGeometry( 90, 260, 90, 20 );
	Time->setMinimumSize( 0, 0 );
	Time->setMaximumSize( 32767, 32767 );
	connect( Time, SIGNAL(returnPressed()), SLOT(timeslot()) );
	Time->setFocusPolicy( QWidget::StrongFocus );
	Time->setBackgroundMode( QWidget::PaletteBase );
	Time->setFontPropagation( QWidget::NoChildren );
	Time->setPalettePropagation( QWidget::NoChildren );
	Time->setText( "" );
	Time->setMaxLength( 32767 );
	Time->setEchoMode( myLineEdit::Normal );
	Time->setFrame( TRUE );

	QRadioButton* qtarch_RadioButton_17;
	qtarch_RadioButton_17 = new QRadioButton( this, "RadioButton_17" );
	qtarch_RadioButton_17->setGeometry( 260, 40, 130, 20 );
	qtarch_RadioButton_17->setMinimumSize( 0, 0 );
	qtarch_RadioButton_17->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_17->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_17->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_17->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_17->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_17->setText( transl("Given Day") );
	qtarch_RadioButton_17->setAutoRepeat( FALSE );
	qtarch_RadioButton_17->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_18;
	qtarch_RadioButton_18 = new QRadioButton( this, "RadioButton_18" );
	qtarch_RadioButton_18->setGeometry( 260, 60, 130, 20 );
	qtarch_RadioButton_18->setMinimumSize( 0, 0 );
	qtarch_RadioButton_18->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_18->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_18->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_18->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_18->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_18->setText( transl("Given month") );
	qtarch_RadioButton_18->setAutoRepeat( FALSE );
	qtarch_RadioButton_18->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_19;
	qtarch_RadioButton_19 = new QRadioButton( this, "RadioButton_19" );
	qtarch_RadioButton_19->setGeometry( 260, 80, 130, 20 );
	qtarch_RadioButton_19->setMinimumSize( 0, 0 );
	qtarch_RadioButton_19->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_19->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_19->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_19->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_19->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_19->setText( transl("Given year") );
	qtarch_RadioButton_19->setAutoRepeat( FALSE );
	qtarch_RadioButton_19->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_20;
	qtarch_RadioButton_20 = new QRadioButton( this, "RadioButton_20" );
	qtarch_RadioButton_20->setGeometry( 260, 100, 140, 20 );
	qtarch_RadioButton_20->setMinimumSize( 0, 0 );
	qtarch_RadioButton_20->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_20->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_20->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_20->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_20->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_20->setText( transl("Range of years") );
	qtarch_RadioButton_20->setAutoRepeat( FALSE );
	qtarch_RadioButton_20->setAutoResize( FALSE );

	QLabel* qtarch_Label_6;
	qtarch_Label_6 = new QLabel( this, "Label_6" );
	qtarch_Label_6->setGeometry( 260, 120, 110, 20 );
	qtarch_Label_6->setMinimumSize( 0, 0 );
	qtarch_Label_6->setMaximumSize( 32767, 32767 );
	qtarch_Label_6->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_6->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_6->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_6->setText( transl("Years to span") );
	qtarch_Label_6->setAlignment( 289 );
	qtarch_Label_6->setMargin( -1 );

	NbYears = new myLineEdit( this, "LineEdit_5" );
	NbYears->setGeometry( 370, 120, 30, 20 );
	NbYears->setMinimumSize( 0, 0 );
	NbYears->setMaximumSize( 32767, 32767 );
	connect( NbYears, SIGNAL(returnPressed()), SLOT(nbyearsslot()) );
	NbYears->setFocusPolicy( QWidget::StrongFocus );
	NbYears->setBackgroundMode( QWidget::PaletteBase );
	NbYears->setFontPropagation( QWidget::NoChildren );
	NbYears->setPalettePropagation( QWidget::NoChildren );
	NbYears->setText( "" );
	NbYears->setMaxLength( 32767 );
	NbYears->setEchoMode( myLineEdit::Normal );
	NbYears->setFrame( TRUE );

	DisplayReturns = new QCheckBox( this, "CheckBox_18" );
	DisplayReturns->setGeometry( 250, 150, 160, 20 );
	DisplayReturns->setMinimumSize( 0, 0 );
	DisplayReturns->setMaximumSize( 32767, 32767 );
	DisplayReturns->setFocusPolicy( QWidget::TabFocus );
	DisplayReturns->setBackgroundMode( QWidget::PaletteBackground );
	DisplayReturns->setFontPropagation( QWidget::NoChildren );
	DisplayReturns->setPalettePropagation( QWidget::NoChildren );
	DisplayReturns->setText( transl("Display returns only") );
	DisplayReturns->setAutoRepeat( FALSE );
	DisplayReturns->setAutoResize( FALSE );

	QLabel* qtarch_Label_7;
	qtarch_Label_7 = new QLabel( this, "Label_7" );
	qtarch_Label_7->setGeometry( 220, 170, 140, 20 );
	qtarch_Label_7->setMinimumSize( 0, 0 );
	qtarch_Label_7->setMaximumSize( 32767, 32767 );
	qtarch_Label_7->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_7->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_7->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_7->setText( transl("Searching Divisions:") );
	qtarch_Label_7->setAlignment( 289 );
	qtarch_Label_7->setMargin( -1 );

	Divisions = new myLineEdit( this, "LineEdit_6" );
	Divisions->setGeometry( 370, 170, 40, 20 );
	Divisions->setMinimumSize( 0, 0 );
	Divisions->setMaximumSize( 32767, 32767 );
	connect( Divisions, SIGNAL(returnPressed()), SLOT(divisionslot()) );
	Divisions->setFocusPolicy( QWidget::StrongFocus );
	Divisions->setBackgroundMode( QWidget::PaletteBase );
	Divisions->setFontPropagation( QWidget::NoChildren );
	Divisions->setPalettePropagation( QWidget::NoChildren );
	Divisions->setText( "" );
	Divisions->setMaxLength( 32767 );
	Divisions->setEchoMode( myLineEdit::Normal );
	Divisions->setFrame( TRUE );

	QPushButton* qtarch_PushButton_3;
	qtarch_PushButton_3 = new QPushButton( this, "PushButton_3" );
	qtarch_PushButton_3->setGeometry( 310, 200, 100, 30 );
	qtarch_PushButton_3->setMinimumSize( 0, 0 );
	qtarch_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_3, SIGNAL(clicked()), SLOT(nowslot()) );
	qtarch_PushButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setText( transl("Now") );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_4;
	qtarch_PushButton_4 = new QPushButton( this, "PushButton_4" );
	qtarch_PushButton_4->setGeometry( 200, 200, 100, 30 );
	qtarch_PushButton_4->setMinimumSize( 0, 0 );
	qtarch_PushButton_4->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_4, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setText( transl("Cancel") );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_5;
	qtarch_PushButton_5 = new QPushButton( this, "PushButton_5" );
	qtarch_PushButton_5->setGeometry( 310, 240, 100, 30 );
	qtarch_PushButton_5->setMinimumSize( 0, 0 );
	qtarch_PushButton_5->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_5, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_5->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_5->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_5->setText( transl("OK") );
	qtarch_PushButton_5->setAutoRepeat( FALSE );
	qtarch_PushButton_5->setAutoResize( FALSE );

	SearchForHits->insert( qtarch_RadioButton_17 );
	SearchForHits->insert( qtarch_RadioButton_18 );
	SearchForHits->insert( qtarch_RadioButton_19 );
	SearchForHits->insert( qtarch_RadioButton_20 );


	TransType->insert( qtarch_RadioButton_1 );
	TransType->insert( qtarch_RadioButton_2 );
	TransType->insert( qtarch_RadioButton_3 );
	TransType->insert( qtarch_RadioButton_4 );
	TransType->insert( qtarch_RadioButton_5 );

	resize( 420,300 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


AstroTransitsData::~AstroTransitsData()
{
}
void AstroTransitsData::searchforhitsslot(int)
{
}
void AstroTransitsData::transtypeslot(int)
{
}
void AstroTransitsData::dayslot()
{
}
void AstroTransitsData::yearslot()
{
}
void AstroTransitsData::timeslot()
{
}
void AstroTransitsData::nbyearsslot()
{
}
void AstroTransitsData::divisionslot()
{
}
void AstroTransitsData::nowslot()
{
}
void AstroTransitsData::cancelslot()
{
}
void AstroTransitsData::okslot()
{
}
