/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroCommandData.h
	Last generated: Sun Sep 26 14:48:27 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AstroCommandData_included
#define AstroCommandData_included

#include <qdialog.h>
#include "myLineEdit.h"
#include "tr.h"

class AstroCommandData : public QDialog
{
    Q_OBJECT

public:

    AstroCommandData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AstroCommandData();

public slots:


protected slots:

    virtual void okslot();
    virtual void cancelslot();

protected:
    myLineEdit* theline;

};

#endif // AstroCommandData_included
