/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroObjectSetData.h
	Last generated: Sat Oct 23 14:39:10 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AstroObjectSetData_included
#define AstroObjectSetData_included

#include <qdialog.h>
#include "ObjectSet.h"
#include "tr.h"

class AstroObjectSetData : public QDialog
{
    Q_OBJECT

public:

    AstroObjectSetData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AstroObjectSetData();

public slots:


protected slots:

    virtual void okslot();
    virtual void cancelslot();

protected:
    ObjectSet* o[20];
};

#endif // AstroObjectSetData_included
