/**********************************************************************

	--- Qt Architect generated file ---

	File: AstroInfoData.h
	Last generated: Mon Aug 28 14:52:53 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef AstroInfoData_included
#define AstroInfoData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qpushbt.h>
#include "myLineEdit.h"
#include <qradiobt.h>
#include <qcombo.h>
#include <qmlined.h>

class AstroInfoData : public QDialog
{
    Q_OBJECT

public:

    AstroInfoData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~AstroInfoData();

public slots:


protected slots:

    virtual void timeslot();
    virtual void monthslot(int);
    virtual void timezoneslot();
    virtual void nameslot();
    virtual void daylightslot(bool);
    virtual void okslot();
    virtual void settzslot();
    virtual void previousslot();
    virtual void nowslot();
    virtual void latitudeslot();
    virtual void locationslot();
    virtual void longitudeslot();
    virtual void dayslot();
    virtual void cancelslot();
    virtual void timezonefileslot();
    virtual void longhmsslot(bool);
    virtual void yearslot();

protected:
    QLabel* monthlabel;
    QLabel* daylabel;
    QLabel* yearlabel;
    QLabel* timelabel;
    QLabel* namelabel;
    QLabel* localtionlabel;
    QComboBox* Month;
    myLineEdit* TheDay;
    myLineEdit* Year;
    myLineEdit* Time;
    QRadioButton* Daylight;
    QRadioButton* LongHMS;
    myLineEdit* Timezone;
    myLineEdit* Longitude;
    myLineEdit* Latitude;
    myLineEdit* Name;
    myLineEdit* Location;
    QPushButton* nowlabel;
    QPushButton* previouslabel;
    QLabel* Errors;
    QLabel* commentlabel;
    QMultiLineEdit* Comment;

};

#endif // AstroInfoData_included
