/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: CalcSettingsData.cpp
	Last generated: Sun Nov 14 14:41:40 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "CalcSettingsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>
#include <qradiobt.h>
#include "config.h"

CalcSettingsData::CalcSettingsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	DispForm = new QButtonGroup( this, "ButtonGroup_2" );
	DispForm->setGeometry( 240, 70, 150, 90 );
	DispForm->setMinimumSize( 0, 0 );
	DispForm->setMaximumSize( 32767, 32767 );
	connect( DispForm, SIGNAL(clicked(int)), SLOT(displayformatslot(int)) );
	DispForm->setFocusPolicy( QWidget::NoFocus );
	DispForm->setBackgroundMode( QWidget::PaletteBackground );
	DispForm->setFontPropagation( QWidget::NoChildren );
	DispForm->setPalettePropagation( QWidget::NoChildren );
	DispForm->setFrameStyle( 49 );
	DispForm->setTitle( transl("Display Format") );
	DispForm->setAlignment( 1 );

	SolChartSett = new QButtonGroup( this, "ButtonGroup_1" );
	SolChartSett->setGeometry( 10, 140, 220, 120 );
	SolChartSett->setMinimumSize( 0, 0 );
	SolChartSett->setMaximumSize( 32767, 32767 );
	connect( SolChartSett, SIGNAL(clicked(int)), SLOT(solchartsettslot(int)) );
	SolChartSett->setFocusPolicy( QWidget::NoFocus );
	SolChartSett->setBackgroundMode( QWidget::PaletteBackground );
	SolChartSett->setFontPropagation( QWidget::NoChildren );
	SolChartSett->setPalettePropagation( QWidget::NoChildren );
	SolChartSett->setFrameStyle( 49 );
	SolChartSett->setTitle( transl("Solar Chart Setting") );
	SolChartSett->setAlignment( 1 );

	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 10, 10, 210, 20 );
	qtarch_Label_1->setMinimumSize( 0, 0 );
	qtarch_Label_1->setMaximumSize( 32767, 32767 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( transl("Zodiac Degree Offset/Ayanamsa:") );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );

	Ayanamsa = new QComboBox( FALSE, this, "ComboBox_1" );
	Ayanamsa->setGeometry( 230, 10, 80, 20 );
	Ayanamsa->setMinimumSize( 0, 0 );
	Ayanamsa->setMaximumSize( 32767, 32767 );
	connect( Ayanamsa, SIGNAL(highlighted(int)), SLOT(ayanamsaslot(int)) );
	Ayanamsa->setFocusPolicy( QWidget::StrongFocus );
	Ayanamsa->setBackgroundMode( QWidget::PaletteBackground );
	Ayanamsa->setFontPropagation( QWidget::AllChildren );
	Ayanamsa->setPalettePropagation( QWidget::AllChildren );
	Ayanamsa->setSizeLimit( 3 );
	Ayanamsa->setAutoResize( FALSE );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 10, 40, 150, 20 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( transl("Aspects To Consider:") );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	NbAspects = new myLineEdit( this, "LineEdit_1" );
	NbAspects->setGeometry( 180, 40, 50, 20 );
	NbAspects->setMinimumSize( 0, 0 );
	NbAspects->setMaximumSize( 32767, 32767 );
	connect( NbAspects, SIGNAL(returnPressed()), SLOT(nbaspslot()) );
	NbAspects->setFocusPolicy( QWidget::StrongFocus );
	NbAspects->setBackgroundMode( QWidget::PaletteBase );
	NbAspects->setFontPropagation( QWidget::NoChildren );
	NbAspects->setPalettePropagation( QWidget::NoChildren );
	NbAspects->setText( "" );
	NbAspects->setMaxLength( 32767 );
	NbAspects->setEchoMode( myLineEdit::Normal );
	NbAspects->setFrame( TRUE );

	QLabel* qtarch_Label_3;
	qtarch_Label_3 = new QLabel( this, "Label_3" );
	qtarch_Label_3->setGeometry( 10, 70, 160, 20 );
	qtarch_Label_3->setMinimumSize( 0, 0 );
	qtarch_Label_3->setMaximumSize( 32767, 32767 );
	qtarch_Label_3->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_3->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_3->setText( transl("Harmonic Chart Factor:") );
	qtarch_Label_3->setAlignment( 289 );
	qtarch_Label_3->setMargin( -1 );

	HarmChartFact = new myLineEdit( this, "LineEdit_2" );
	HarmChartFact->setGeometry( 180, 70, 50, 20 );
	HarmChartFact->setMinimumSize( 0, 0 );
	HarmChartFact->setMaximumSize( 32767, 32767 );
	connect( HarmChartFact, SIGNAL(returnPressed()), SLOT(harmchartfactslot()) );
	HarmChartFact->setFocusPolicy( QWidget::StrongFocus );
	HarmChartFact->setBackgroundMode( QWidget::PaletteBase );
	HarmChartFact->setFontPropagation( QWidget::NoChildren );
	HarmChartFact->setPalettePropagation( QWidget::NoChildren );
	HarmChartFact->setText( "" );
	HarmChartFact->setMaxLength( 32767 );
	HarmChartFact->setEchoMode( myLineEdit::Normal );
	HarmChartFact->setFrame( TRUE );

	QLabel* qtarch_Label_4;
	qtarch_Label_4 = new QLabel( this, "Label_4" );
	qtarch_Label_4->setGeometry( 10, 100, 110, 20 );
	qtarch_Label_4->setMinimumSize( 0, 0 );
	qtarch_Label_4->setMaximumSize( 32767, 32767 );
	qtarch_Label_4->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_4->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_4->setText( transl("Central Planet:") );
	qtarch_Label_4->setAlignment( 289 );
	qtarch_Label_4->setMargin( -1 );

	CentPlan = new QComboBox( FALSE, this, "ComboBox_2" );
	CentPlan->setGeometry( 130, 100, 100, 20 );
	CentPlan->setMinimumSize( 0, 0 );
	CentPlan->setMaximumSize( 32767, 32767 );
	connect( CentPlan, SIGNAL(highlighted(int)), SLOT(centplanslot(int)) );
	CentPlan->setFocusPolicy( QWidget::StrongFocus );
	CentPlan->setBackgroundMode( QWidget::PaletteBackground );
	CentPlan->setFontPropagation( QWidget::AllChildren );
	CentPlan->setPalettePropagation( QWidget::AllChildren );
	CentPlan->setSizeLimit( 10 );
	CentPlan->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_1;
	qtarch_RadioButton_1 = new QRadioButton( this, "RadioButton_1" );
	qtarch_RadioButton_1->setGeometry( 20, 160, 100, 20 );
	qtarch_RadioButton_1->setMinimumSize( 0, 0 );
	qtarch_RadioButton_1->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_1->setText( transl("None") );
	qtarch_RadioButton_1->setAutoRepeat( FALSE );
	qtarch_RadioButton_1->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_2;
	qtarch_RadioButton_2 = new QRadioButton( this, "RadioButton_2" );
	qtarch_RadioButton_2->setGeometry( 20, 180, 170, 30 );
	qtarch_RadioButton_2->setMinimumSize( 0, 0 );
	qtarch_RadioButton_2->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_2->setText( transl("Object On Ascendant") );
	qtarch_RadioButton_2->setAutoRepeat( FALSE );
	qtarch_RadioButton_2->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_3;
	qtarch_RadioButton_3 = new QRadioButton( this, "RadioButton_3" );
	qtarch_RadioButton_3->setGeometry( 20, 210, 180, 20 );
	qtarch_RadioButton_3->setMinimumSize( 0, 0 );
	qtarch_RadioButton_3->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_3->setText( transl("Object On Midheaven") );
	qtarch_RadioButton_3->setAutoRepeat( FALSE );
	qtarch_RadioButton_3->setAutoResize( FALSE );

	QLabel* qtarch_Label_5;
	qtarch_Label_5 = new QLabel( this, "Label_5" );
	qtarch_Label_5->setGeometry( 20, 230, 120, 20 );
	qtarch_Label_5->setMinimumSize( 0, 0 );
	qtarch_Label_5->setMaximumSize( 32767, 32767 );
	qtarch_Label_5->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_5->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_5->setText( transl("Use the Planet:") );
	qtarch_Label_5->setAlignment( 289 );
	qtarch_Label_5->setMargin( -1 );

	UsePlan = new QComboBox( FALSE, this, "ComboBox_3" );
	UsePlan->setGeometry( 120, 230, 100, 20 );
	UsePlan->setMinimumSize( 0, 0 );
	UsePlan->setMaximumSize( 32767, 32767 );
	connect( UsePlan, SIGNAL(highlighted(int)), SLOT(useplanslot(int)) );
	UsePlan->setFocusPolicy( QWidget::StrongFocus );
	UsePlan->setBackgroundMode( QWidget::PaletteBackground );
	UsePlan->setFontPropagation( QWidget::AllChildren );
	UsePlan->setPalettePropagation( QWidget::AllChildren );
	UsePlan->setSizeLimit( 10 );
	UsePlan->setAutoResize( FALSE );

	QLabel* qtarch_Label_6;
	qtarch_Label_6 = new QLabel( this, "Label_6" );
	qtarch_Label_6->setGeometry( 10, 270, 100, 20 );
	qtarch_Label_6->setMinimumSize( 0, 0 );
	qtarch_Label_6->setMaximumSize( 32767, 32767 );
	qtarch_Label_6->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_6->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_6->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_6->setText( transl("Text Columns:") );
	qtarch_Label_6->setAlignment( 289 );
	qtarch_Label_6->setMargin( -1 );

	TextCol = new myLineEdit( this, "LineEdit_3" );
	TextCol->setGeometry( 120, 270, 40, 20 );
	TextCol->setMinimumSize( 0, 0 );
	TextCol->setMaximumSize( 32767, 32767 );
	connect( TextCol, SIGNAL(returnPressed()), SLOT(textcolslot()) );
	TextCol->setFocusPolicy( QWidget::StrongFocus );
	TextCol->setBackgroundMode( QWidget::PaletteBase );
	TextCol->setFontPropagation( QWidget::NoChildren );
	TextCol->setPalettePropagation( QWidget::NoChildren );
	TextCol->setText( "" );
	TextCol->setMaxLength( 32767 );
	TextCol->setEchoMode( myLineEdit::Normal );
	TextCol->setFrame( TRUE );

#ifdef PLACALC
	Ephem = new QCheckBox( this, "CheckBox_1" );
	Ephem->setGeometry( 240, 40, 150, 20 );
	Ephem->setMinimumSize( 0, 0 );
	Ephem->setMaximumSize( 32767, 32767 );
	Ephem->setFocusPolicy( QWidget::TabFocus );
	Ephem->setBackgroundMode( QWidget::PaletteBackground );
	Ephem->setFontPropagation( QWidget::NoChildren );
	Ephem->setPalettePropagation( QWidget::NoChildren );
	Ephem->setText( transl("Use Ephemeris Files") );
	Ephem->setAutoRepeat( FALSE );
	Ephem->setAutoResize( FALSE );
#endif

	QRadioButton* qtarch_RadioButton_4;
	qtarch_RadioButton_4 = new QRadioButton( this, "RadioButton_4" );
	qtarch_RadioButton_4->setGeometry( 250, 90, 130, 20 );
	qtarch_RadioButton_4->setMinimumSize( 0, 0 );
	qtarch_RadioButton_4->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_4->setText( transl("Zodiac Position") );
	qtarch_RadioButton_4->setAutoRepeat( FALSE );
	qtarch_RadioButton_4->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_5;
	qtarch_RadioButton_5 = new QRadioButton( this, "RadioButton_5" );
	qtarch_RadioButton_5->setGeometry( 250, 110, 130, 20 );
	qtarch_RadioButton_5->setMinimumSize( 0, 0 );
	qtarch_RadioButton_5->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_5->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_5->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_5->setText( transl("Hours & Minutes") );
	qtarch_RadioButton_5->setAutoRepeat( FALSE );
	qtarch_RadioButton_5->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_6;
	qtarch_RadioButton_6 = new QRadioButton( this, "RadioButton_6" );
	qtarch_RadioButton_6->setGeometry( 250, 130, 130, 20 );
	qtarch_RadioButton_6->setMinimumSize( 0, 0 );
	qtarch_RadioButton_6->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_6->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_6->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_6->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_6->setText( transl("360 Degrees") );
	qtarch_RadioButton_6->setAutoRepeat( FALSE );
	qtarch_RadioButton_6->setAutoResize( FALSE );

	EquaPos = new QCheckBox( this, "CheckBox_2" );
	EquaPos->setGeometry( 240, 170, 100, 20 );
	EquaPos->setMinimumSize( 0, 0 );
	EquaPos->setMaximumSize( 32767, 32767 );
	EquaPos->setFocusPolicy( QWidget::TabFocus );
	EquaPos->setBackgroundMode( QWidget::PaletteBackground );
	EquaPos->setFontPropagation( QWidget::NoChildren );
	EquaPos->setPalettePropagation( QWidget::NoChildren );
	EquaPos->setText( transl("Equatorial Positions") );
	EquaPos->setAutoRepeat( FALSE );
	EquaPos->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 290, 220, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( transl("Cancel") );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 290, 260, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 0, 0 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( transl("OK") );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	DispForm->insert( qtarch_RadioButton_4 );
	DispForm->insert( qtarch_RadioButton_5 );
	DispForm->insert( qtarch_RadioButton_6 );

	SolChartSett->insert( qtarch_RadioButton_1 );
	SolChartSett->insert( qtarch_RadioButton_2 );
	SolChartSett->insert( qtarch_RadioButton_3 );

	resize( 400,300 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


CalcSettingsData::~CalcSettingsData()
{
}
void CalcSettingsData::displayformatslot(int)
{
}
void CalcSettingsData::solchartsettslot(int)
{
}
void CalcSettingsData::ayanamsaslot(int)
{
}
void CalcSettingsData::nbaspslot()
{
}
void CalcSettingsData::harmchartfactslot()
{
}
void CalcSettingsData::centplanslot(int)
{
}
void CalcSettingsData::useplanslot(int)
{
}
void CalcSettingsData::textcolslot()
{
}
void CalcSettingsData::cancelslot()
{
}
void CalcSettingsData::okslot()
{
}
