/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: CalcSettingsData.h
	Last generated: Sun Nov 14 14:41:40 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef CalcSettingsData_included
#define CalcSettingsData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include "myLineEdit.h"
#include <qcombo.h>
#include "tr.h"

class CalcSettingsData : public QDialog
{
    Q_OBJECT

public:

    CalcSettingsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~CalcSettingsData();

public slots:


protected slots:

    virtual void textcolslot();
    virtual void okslot();
    virtual void solchartsettslot(int);
    virtual void harmchartfactslot();
    virtual void nbaspslot();
    virtual void useplanslot(int);
    virtual void displayformatslot(int);
    virtual void cancelslot();
    virtual void ayanamsaslot(int);
    virtual void centplanslot(int);

protected:
    QButtonGroup* DispForm;
    QButtonGroup* SolChartSett;
    QComboBox* Ayanamsa;
    myLineEdit* NbAspects;
    myLineEdit* HarmChartFact;
    QComboBox* CentPlan;
    QComboBox* UsePlan;
    myLineEdit* TextCol;
    QCheckBox* Ephem;
    QCheckBox* EquaPos;

};

#endif // CalcSettingsData_included
