/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: ChartDetailsData.h
	Last generated: Sat Nov 13 16:01:11 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ChartDetailsData_included
#define ChartDetailsData_included

#include <qdialog.h>
#include <qlabel.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include "myLineEdit.h"
#include "tr.h"

class ChartDetailsData : public QDialog
{
    Q_OBJECT

public:

    ChartDetailsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ChartDetailsData();

public slots:


protected slots:

    virtual void steprateslot();
    virtual void nbarabpartslot();
    virtual void okslot();
    virtual void arabpartorderslot(int);
    virtual void starorderslot(int);
    virtual void wheelrowslot();
    virtual void cancelslot();

protected:
    QButtonGroup* ArabPartOrder;
    QButtonGroup* StarsOrder;
    QCheckBox* Velocit;
    myLineEdit* WheelRows;
    QCheckBox* Reverse;
    QCheckBox* ShowConf;
    QCheckBox* ShowsSummary;
    QCheckBox* MidpointSummary;
    QCheckBox* IncludesAsp;
    QCheckBox* PolarCenter;
    QCheckBox* ApproxPlac;
    QCheckBox* SignInfluence;
    myLineEdit* StepRate;
    QCheckBox* LatCross;
    QCheckBox* EntireYear;
    QLabel* ArabParts;
    myLineEdit* NbArabParts;
    QCheckBox* TermRevers;

};

#endif // ChartDetailsData_included
