/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: ChartDetailsData.cpp
	Last generated: Sat Nov 13 16:01:11 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ChartDetailsData.h"

#define Inherited QDialog

#include <qlabel.h>
#include <qpushbt.h>
#include <qradiobt.h>
#include "config.h"

ChartDetailsData::ChartDetailsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	ArabPartOrder = new QButtonGroup( this, "ButtonGroup_2" );
	ArabPartOrder->setGeometry( 340, 160, 150, 110 );
	ArabPartOrder->setMinimumSize( 0, 0 );
	ArabPartOrder->setMaximumSize( 32767, 32767 );
	connect( ArabPartOrder, SIGNAL(clicked(int)), SLOT(arabpartorderslot(int)) );
#ifdef ARABIC
	ArabPartOrder->setFocusPolicy( QWidget::NoFocus );
	ArabPartOrder->setBackgroundMode( QWidget::PaletteBackground );
	ArabPartOrder->setFontPropagation( QWidget::NoChildren );
	ArabPartOrder->setPalettePropagation( QWidget::NoChildren );
	ArabPartOrder->setFrameStyle( 49 );
	ArabPartOrder->setTitle( transl("Arabic parts ordering") );
	ArabPartOrder->setAlignment( 1 );
#endif

	StarsOrder = new QButtonGroup( this, "ButtonGroup_1" );
	StarsOrder->setGeometry( 340, 10, 150, 130 );
	StarsOrder->setMinimumSize( 0, 0 );
	StarsOrder->setMaximumSize( 32767, 32767 );
	connect( StarsOrder, SIGNAL(clicked(int)), SLOT(starorderslot(int)) );
	StarsOrder->setFocusPolicy( QWidget::NoFocus );
	StarsOrder->setBackgroundMode( QWidget::PaletteBackground );
	StarsOrder->setFontPropagation( QWidget::NoChildren );
	StarsOrder->setPalettePropagation( QWidget::NoChildren );
	StarsOrder->setFrameStyle( 49 );
	StarsOrder->setTitle( transl("Fixed stars ordering") );
	StarsOrder->setAlignment( 1 );

	Velocit = new QCheckBox( this, "CheckBox_1" );
	Velocit->setGeometry( 10, 10, 330, 20 );
	Velocit->setMinimumSize( 0, 0 );
	Velocit->setMaximumSize( 32767, 32767 );
	Velocit->setFocusPolicy( QWidget::TabFocus );
	Velocit->setBackgroundMode( QWidget::PaletteBackground );
	Velocit->setFontPropagation( QWidget::NoChildren );
	Velocit->setPalettePropagation( QWidget::NoChildren );
	Velocit->setText( transl("Text Listing Velocities Relative to Average Speed") );
	Velocit->setAutoRepeat( FALSE );
	Velocit->setAutoResize( FALSE );

	QLabel* qtarch_Label_1;
	qtarch_Label_1 = new QLabel( this, "Label_1" );
	qtarch_Label_1->setGeometry( 10, 30, 170, 20 );
	qtarch_Label_1->setMinimumSize( 0, 0 );
	qtarch_Label_1->setMaximumSize( 32767, 32767 );
	qtarch_Label_1->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_1->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_1->setText( transl("Text house wheel rows:") );
	qtarch_Label_1->setAlignment( 289 );
	qtarch_Label_1->setMargin( -1 );

	WheelRows = new myLineEdit( this, "LineEdit_1" );
	WheelRows->setGeometry( 170, 30, 40, 20 );
	WheelRows->setMinimumSize( 0, 0 );
	WheelRows->setMaximumSize( 32767, 32767 );
	connect( WheelRows, SIGNAL(returnPressed()), SLOT(wheelrowslot()) );
	WheelRows->setFocusPolicy( QWidget::StrongFocus );
	WheelRows->setBackgroundMode( QWidget::PaletteBase );
	WheelRows->setFontPropagation( QWidget::NoChildren );
	WheelRows->setPalettePropagation( QWidget::NoChildren );
	WheelRows->setText( "" );
	WheelRows->setMaxLength( 32767 );
	WheelRows->setEchoMode( myLineEdit::Normal );
	WheelRows->setFrame( TRUE );

	Reverse = new QCheckBox( this, "CheckBox_2" );
	Reverse->setGeometry( 10, 50, 320, 20 );
	Reverse->setMinimumSize( 0, 0 );
	Reverse->setMaximumSize( 32767, 32767 );
	Reverse->setFocusPolicy( QWidget::TabFocus );
	Reverse->setBackgroundMode( QWidget::PaletteBackground );
	Reverse->setFontPropagation( QWidget::NoChildren );
	Reverse->setPalettePropagation( QWidget::NoChildren );
	Reverse->setText( transl("Text house wheel reverse object order") );
	Reverse->setAutoRepeat( FALSE );
	Reverse->setAutoResize( FALSE );

	ShowConf = new QCheckBox( this, "CheckBox_3" );
	ShowConf->setGeometry( 10, 70, 320, 20 );
	ShowConf->setMinimumSize( 0, 0 );
	ShowConf->setMaximumSize( 32767, 32767 );
	ShowConf->setFocusPolicy( QWidget::TabFocus );
	ShowConf->setBackgroundMode( QWidget::PaletteBackground );
	ShowConf->setFontPropagation( QWidget::NoChildren );
	ShowConf->setPalettePropagation( QWidget::NoChildren );
	ShowConf->setText( transl("Text aspect grid shows aspect configurations") );
	ShowConf->setAutoRepeat( FALSE );
	ShowConf->setAutoResize( FALSE );

	ShowsSummary = new QCheckBox( this, "CheckBox_4" );
	ShowsSummary->setGeometry( 10, 90, 320, 20 );
	ShowsSummary->setMinimumSize( 0, 0 );
	ShowsSummary->setMaximumSize( 32767, 32767 );
	ShowsSummary->setFocusPolicy( QWidget::TabFocus );
	ShowsSummary->setBackgroundMode( QWidget::PaletteBackground );
	ShowsSummary->setFontPropagation( QWidget::NoChildren );
	ShowsSummary->setPalettePropagation( QWidget::NoChildren );
	ShowsSummary->setText( transl("Text aspect list shows aspect summary") );
	ShowsSummary->setAutoRepeat( FALSE );
	ShowsSummary->setAutoResize( FALSE );

	MidpointSummary = new QCheckBox( this, "CheckBox_5" );
	MidpointSummary->setGeometry( 10, 110, 320, 20 );
	MidpointSummary->setMinimumSize( 0, 0 );
	MidpointSummary->setMaximumSize( 32767, 32767 );
	MidpointSummary->setFocusPolicy( QWidget::TabFocus );
	MidpointSummary->setBackgroundMode( QWidget::PaletteBackground );
	MidpointSummary->setFontPropagation( QWidget::NoChildren );
	MidpointSummary->setPalettePropagation( QWidget::NoChildren );
	MidpointSummary->setText( transl("Text midpoint list shows midpoint summary") );
	MidpointSummary->setAutoRepeat( FALSE );
	MidpointSummary->setAutoResize( FALSE );

	IncludesAsp = new QCheckBox( this, "CheckBox_6" );
	IncludesAsp->setGeometry( 10, 130, 320, 20 );
	IncludesAsp->setMinimumSize( 0, 0 );
	IncludesAsp->setMaximumSize( 32767, 32767 );
	IncludesAsp->setFocusPolicy( QWidget::TabFocus );
	IncludesAsp->setBackgroundMode( QWidget::PaletteBackground );
	IncludesAsp->setFontPropagation( QWidget::NoChildren );
	IncludesAsp->setPalettePropagation( QWidget::NoChildren );
	IncludesAsp->setText( transl("Text midpoint list includes aspects to midpoints") );
	IncludesAsp->setAutoRepeat( FALSE );
	IncludesAsp->setAutoResize( FALSE );

	PolarCenter = new QCheckBox( this, "CheckBox_7" );
	PolarCenter->setGeometry( 10, 150, 320, 20 );
	PolarCenter->setMinimumSize( 0, 0 );
	PolarCenter->setMaximumSize( 32767, 32767 );
	PolarCenter->setFocusPolicy( QWidget::TabFocus );
	PolarCenter->setBackgroundMode( QWidget::PaletteBackground );
	PolarCenter->setFontPropagation( QWidget::NoChildren );
	PolarCenter->setPalettePropagation( QWidget::NoChildren );
	PolarCenter->setText( transl("Horizon charts with polar center") );
	PolarCenter->setAutoRepeat( FALSE );
	PolarCenter->setAutoResize( FALSE );

	ApproxPlac = new QCheckBox( this, "CheckBox_8" );
	ApproxPlac->setGeometry( 10, 170, 320, 20 );
	ApproxPlac->setMinimumSize( 0, 0 );
	ApproxPlac->setMaximumSize( 32767, 32767 );
	ApproxPlac->setFocusPolicy( QWidget::TabFocus );
	ApproxPlac->setBackgroundMode( QWidget::PaletteBackground );
	ApproxPlac->setFontPropagation( QWidget::NoChildren );
	ApproxPlac->setPalettePropagation( QWidget::NoChildren );
	ApproxPlac->setText( transl("Sector chart approximation with placidus cusps") );
	ApproxPlac->setAutoRepeat( FALSE );
	ApproxPlac->setAutoResize( FALSE );

	SignInfluence = new QCheckBox( this, "CheckBox_9" );
	SignInfluence->setGeometry( 10, 190, 320, 20 );
	SignInfluence->setMinimumSize( 0, 0 );
	SignInfluence->setMaximumSize( 32767, 32767 );
	SignInfluence->setFocusPolicy( QWidget::TabFocus );
	SignInfluence->setBackgroundMode( QWidget::PaletteBackground );
	SignInfluence->setFontPropagation( QWidget::NoChildren );
	SignInfluence->setPalettePropagation( QWidget::NoChildren );
	SignInfluence->setText( transl("Text influence chart shows sign influence too") );
	SignInfluence->setAutoRepeat( FALSE );
	SignInfluence->setAutoResize( FALSE );

	QLabel* qtarch_Label_2;
	qtarch_Label_2 = new QLabel( this, "Label_2" );
	qtarch_Label_2->setGeometry( 10, 210, 190, 20 );
	qtarch_Label_2->setMinimumSize( 0, 0 );
	qtarch_Label_2->setMaximumSize( 32767, 32767 );
	qtarch_Label_2->setFocusPolicy( QWidget::NoFocus );
	qtarch_Label_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_Label_2->setFontPropagation( QWidget::NoChildren );
	qtarch_Label_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_Label_2->setText( transl("Text Astro-Graph step rate:") );
	qtarch_Label_2->setAlignment( 289 );
	qtarch_Label_2->setMargin( -1 );

	StepRate = new myLineEdit( this, "LineEdit_2" );
	StepRate->setGeometry( 190, 210, 40, 20 );
	StepRate->setMinimumSize( 0, 0 );
	StepRate->setMaximumSize( 32767, 32767 );
	connect( StepRate, SIGNAL(returnPressed()), SLOT(steprateslot()) );
	StepRate->setFocusPolicy( QWidget::StrongFocus );
	StepRate->setBackgroundMode( QWidget::PaletteBase );
	StepRate->setFontPropagation( QWidget::NoChildren );
	StepRate->setPalettePropagation( QWidget::NoChildren );
	StepRate->setText( "" );
	StepRate->setMaxLength( 32767 );
	StepRate->setEchoMode( myLineEdit::Normal );
	StepRate->setFrame( TRUE );

	LatCross = new QCheckBox( this, "CheckBox_10" );
	LatCross->setGeometry( 10, 230, 320, 20 );
	LatCross->setMinimumSize( 0, 0 );
	LatCross->setMaximumSize( 32767, 32767 );
	LatCross->setFocusPolicy( QWidget::TabFocus );
	LatCross->setBackgroundMode( QWidget::PaletteBackground );
	LatCross->setFontPropagation( QWidget::NoChildren );
	LatCross->setPalettePropagation( QWidget::NoChildren );
	LatCross->setText( transl("Text Astro-Graph shows latitude crossings") );
	LatCross->setAutoRepeat( FALSE );
	LatCross->setAutoResize( FALSE );

	EntireYear = new QCheckBox( this, "CheckBox_11" );
	EntireYear->setGeometry( 10, 250, 320, 20 );
	EntireYear->setMinimumSize( 0, 0 );
	EntireYear->setMaximumSize( 32767, 32767 );
	EntireYear->setFocusPolicy( QWidget::TabFocus );
	EntireYear->setBackgroundMode( QWidget::PaletteBackground );
	EntireYear->setFontPropagation( QWidget::NoChildren );
	EntireYear->setPalettePropagation( QWidget::NoChildren );
	EntireYear->setText( transl("Text calendar for entire year") );
	EntireYear->setAutoRepeat( FALSE );
	EntireYear->setAutoResize( FALSE );
#ifdef ARABIC
	ArabParts = new QLabel( this, "Label_3" );
	ArabParts->setGeometry( 10, 270, 220, 20 );
	ArabParts->setMinimumSize( 0, 0 );
	ArabParts->setMaximumSize( 32767, 32767 );
	ArabParts->setFocusPolicy( QWidget::NoFocus );
	ArabParts->setBackgroundMode( QWidget::PaletteBackground );
	ArabParts->setFontPropagation( QWidget::NoChildren );
	ArabParts->setPalettePropagation( QWidget::NoChildren );
	ArabParts->setText( transl("Numer of arabic parts to display") );
	ArabParts->setAlignment( 289 );
	ArabParts->setMargin( -1 );

	NbArabParts = new myLineEdit( this, "LineEdit_3" );
	NbArabParts->setGeometry( 220, 270, 50, 20 );
	NbArabParts->setMinimumSize( 0, 0 );
	NbArabParts->setMaximumSize( 32767, 32767 );
	connect( NbArabParts, SIGNAL(returnPressed()), SLOT(nbarabpartslot()) );
	NbArabParts->setFocusPolicy( QWidget::StrongFocus );
	NbArabParts->setBackgroundMode( QWidget::PaletteBase );
	NbArabParts->setFontPropagation( QWidget::NoChildren );
	NbArabParts->setPalettePropagation( QWidget::NoChildren );
	NbArabParts->setText( "" );
	NbArabParts->setMaxLength( 32767 );
	NbArabParts->setEchoMode( myLineEdit::Normal );
	NbArabParts->setFrame( TRUE );

	TermRevers = new QCheckBox( this, "CheckBox_12" );
	TermRevers->setGeometry( 10, 290, 320, 20 );
	TermRevers->setMinimumSize( 0, 0 );
	TermRevers->setMaximumSize( 32767, 32767 );
	TermRevers->setFocusPolicy( QWidget::TabFocus );
	TermRevers->setBackgroundMode( QWidget::PaletteBackground );
	TermRevers->setFontPropagation( QWidget::NoChildren );
	TermRevers->setPalettePropagation( QWidget::NoChildren );
	TermRevers->setText( transl("Display arabic parts formulas with terms reversed") );
	TermRevers->setAutoRepeat( FALSE );
	TermRevers->setAutoResize( FALSE );
#endif
	QRadioButton* qtarch_RadioButton_1;
	qtarch_RadioButton_1 = new QRadioButton( this, "RadioButton_1" );
	qtarch_RadioButton_1->setGeometry( 350, 30, 100, 20 );
	qtarch_RadioButton_1->setMinimumSize( 0, 0 );
	qtarch_RadioButton_1->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_1->setText( transl("Default") );
	qtarch_RadioButton_1->setAutoRepeat( FALSE );
	qtarch_RadioButton_1->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_2;
	qtarch_RadioButton_2 = new QRadioButton( this, "RadioButton_2" );
	qtarch_RadioButton_2->setGeometry( 350, 50, 100, 20 );
	qtarch_RadioButton_2->setMinimumSize( 0, 0 );
	qtarch_RadioButton_2->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_2->setText( transl("By azimuth") );
	qtarch_RadioButton_2->setAutoRepeat( FALSE );
	qtarch_RadioButton_2->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_3;
	qtarch_RadioButton_3 = new QRadioButton( this, "RadioButton_3" );
	qtarch_RadioButton_3->setGeometry( 350, 70, 100, 20 );
	qtarch_RadioButton_3->setMinimumSize( 0, 0 );
	qtarch_RadioButton_3->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_3->setText( transl("By altitude") );
	qtarch_RadioButton_3->setAutoRepeat( FALSE );
	qtarch_RadioButton_3->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_4;
	qtarch_RadioButton_4 = new QRadioButton( this, "RadioButton_4" );
	qtarch_RadioButton_4->setGeometry( 350, 90, 100, 20 );
	qtarch_RadioButton_4->setMinimumSize( 0, 0 );
	qtarch_RadioButton_4->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_4->setText( transl("By name") );
	qtarch_RadioButton_4->setAutoRepeat( FALSE );
	qtarch_RadioButton_4->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_5;
	qtarch_RadioButton_5 = new QRadioButton( this, "RadioButton_5" );
	qtarch_RadioButton_5->setGeometry( 350, 110, 100, 20 );
	qtarch_RadioButton_5->setMinimumSize( 0, 0 );
	qtarch_RadioButton_5->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_5->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_5->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_5->setText( transl("By brightness") );
	qtarch_RadioButton_5->setAutoRepeat( FALSE );
	qtarch_RadioButton_5->setAutoResize( FALSE );
#ifdef ARABIC
	QRadioButton* qtarch_RadioButton_6;
	qtarch_RadioButton_6 = new QRadioButton( this, "RadioButton_6" );
	qtarch_RadioButton_6->setGeometry( 350, 180, 120, 20 );
	qtarch_RadioButton_6->setMinimumSize( 0, 0 );
	qtarch_RadioButton_6->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_6->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_6->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_6->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_6->setText( transl("Default") );
	qtarch_RadioButton_6->setAutoRepeat( FALSE );
	qtarch_RadioButton_6->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_7;
	qtarch_RadioButton_7 = new QRadioButton( this, "RadioButton_7" );
	qtarch_RadioButton_7->setGeometry( 350, 200, 120, 20 );
	qtarch_RadioButton_7->setMinimumSize( 0, 0 );
	qtarch_RadioButton_7->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_7->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_7->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_7->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_7->setText( transl("By Position") );
	qtarch_RadioButton_7->setAutoRepeat( FALSE );
	qtarch_RadioButton_7->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_8;
	qtarch_RadioButton_8 = new QRadioButton( this, "RadioButton_8" );
	qtarch_RadioButton_8->setGeometry( 350, 220, 120, 20 );
	qtarch_RadioButton_8->setMinimumSize( 0, 0 );
	qtarch_RadioButton_8->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_8->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_8->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_8->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_8->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_8->setText( transl("By name") );
	qtarch_RadioButton_8->setAutoRepeat( FALSE );
	qtarch_RadioButton_8->setAutoResize( FALSE );

	QRadioButton* qtarch_RadioButton_9;
	qtarch_RadioButton_9 = new QRadioButton( this, "RadioButton_9" );
	qtarch_RadioButton_9->setGeometry( 350, 240, 130, 20 );
	qtarch_RadioButton_9->setMinimumSize( 0, 0 );
	qtarch_RadioButton_9->setMaximumSize( 32767, 32767 );
	qtarch_RadioButton_9->setFocusPolicy( QWidget::TabFocus );
	qtarch_RadioButton_9->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_RadioButton_9->setFontPropagation( QWidget::NoChildren );
	qtarch_RadioButton_9->setPalettePropagation( QWidget::NoChildren );
	qtarch_RadioButton_9->setText( transl("By formula") );
	qtarch_RadioButton_9->setAutoRepeat( FALSE );
	qtarch_RadioButton_9->setAutoResize( FALSE );
#endif
	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 390, 280, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( transl("Cancel") );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 390, 320, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 0, 0 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( transl("OK") );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );
#ifdef ARABIC
	ArabPartOrder->insert( qtarch_RadioButton_6 );
	ArabPartOrder->insert( qtarch_RadioButton_7 );
	ArabPartOrder->insert( qtarch_RadioButton_8 );
	ArabPartOrder->insert( qtarch_RadioButton_9 );
#endif
	StarsOrder->insert( qtarch_RadioButton_1 );
	StarsOrder->insert( qtarch_RadioButton_2 );
	StarsOrder->insert( qtarch_RadioButton_3 );
	StarsOrder->insert( qtarch_RadioButton_4 );
	StarsOrder->insert( qtarch_RadioButton_5 );

	resize( 510,360 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ChartDetailsData::~ChartDetailsData()
{
}
void ChartDetailsData::arabpartorderslot(int)
{
}
void ChartDetailsData::starorderslot(int)
{
}
void ChartDetailsData::wheelrowslot()
{
}
void ChartDetailsData::steprateslot()
{
}
void ChartDetailsData::nbarabpartslot()
{
}
void ChartDetailsData::cancelslot()
{
}
void ChartDetailsData::okslot()
{
}
