/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: ColorVectorData.cpp
	Last generated: Sat Oct 16 14:49:47 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "ColorVectorData.h"

#define Inherited QWidget


ColorVectorData::ColorVectorData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, 0 )
{
	Table = new QButtonGroup( this, "ButtonGroup_1" );
	Table->setGeometry( 10, 10, 190, 350 );
	Table->setMinimumSize( 0, 0 );
	Table->setMaximumSize( 32767, 32767 );
	Table->setFocusPolicy( QWidget::NoFocus );
	Table->setBackgroundMode( QWidget::PaletteBackground );
	Table->setFontPropagation( QWidget::NoChildren );
	Table->setPalettePropagation( QWidget::NoChildren );
	Table->setFrameStyle( 49 );
	Table->setTitle( transl("Color Table") );
	Table->setAlignment( 1 );

	b[0] = new QRadioButton( this, "RadioButton_1" );
	b[0]->setGeometry( 60, 30, 130, 20 );
	b[0]->setMinimumSize( 0, 0 );
	b[0]->setMaximumSize( 32767, 32767 );
	b[0]->setFocusPolicy( QWidget::TabFocus );
	b[0]->setBackgroundMode( QWidget::PaletteBackground );
	b[0]->setFontPropagation( QWidget::NoChildren );
	b[0]->setPalettePropagation( QWidget::NoChildren );
	b[0]->setText( "" );
	b[0]->setAutoRepeat( FALSE );
	b[0]->setAutoResize( FALSE );

	b[1] = new QRadioButton( this, "RadioButton_2" );
	b[1]->setGeometry( 60, 50, 130, 20 );
	b[1]->setMinimumSize( 0, 0 );
	b[1]->setMaximumSize( 32767, 32767 );
	b[1]->setFocusPolicy( QWidget::TabFocus );
	b[1]->setBackgroundMode( QWidget::PaletteBackground );
	b[1]->setFontPropagation( QWidget::NoChildren );
	b[1]->setPalettePropagation( QWidget::NoChildren );
	b[1]->setText( "" );
	b[1]->setAutoRepeat( FALSE );
	b[1]->setAutoResize( FALSE );

	b[2] = new QRadioButton( this, "RadioButton_3" );
	b[2]->setGeometry( 60, 70, 130, 20 );
	b[2]->setMinimumSize( 0, 0 );
	b[2]->setMaximumSize( 32767, 32767 );
	b[2]->setFocusPolicy( QWidget::TabFocus );
	b[2]->setBackgroundMode( QWidget::PaletteBackground );
	b[2]->setFontPropagation( QWidget::NoChildren );
	b[2]->setPalettePropagation( QWidget::NoChildren );
	b[2]->setText( "" );
	b[2]->setAutoRepeat( FALSE );
	b[2]->setAutoResize( FALSE );

	b[3] = new QRadioButton( this, "RadioButton_4" );
	b[3]->setGeometry( 60, 90, 130, 20 );
	b[3]->setMinimumSize( 0, 0 );
	b[3]->setMaximumSize( 32767, 32767 );
	b[3]->setFocusPolicy( QWidget::TabFocus );
	b[3]->setBackgroundMode( QWidget::PaletteBackground );
	b[3]->setFontPropagation( QWidget::NoChildren );
	b[3]->setPalettePropagation( QWidget::NoChildren );
	b[3]->setText( "" );
	b[3]->setAutoRepeat( FALSE );
	b[3]->setAutoResize( FALSE );

	b[4] = new QRadioButton( this, "RadioButton_5" );
	b[4]->setGeometry( 60, 110, 130, 20 );
	b[4]->setMinimumSize( 0, 0 );
	b[4]->setMaximumSize( 32767, 32767 );
	b[4]->setFocusPolicy( QWidget::TabFocus );
	b[4]->setBackgroundMode( QWidget::PaletteBackground );
	b[4]->setFontPropagation( QWidget::NoChildren );
	b[4]->setPalettePropagation( QWidget::NoChildren );
	b[4]->setText( "" );
	b[4]->setAutoRepeat( FALSE );
	b[4]->setAutoResize( FALSE );

	b[5] = new QRadioButton( this, "RadioButton_6" );
	b[5]->setGeometry( 60, 130, 130, 20 );
	b[5]->setMinimumSize( 0, 0 );
	b[5]->setMaximumSize( 32767, 32767 );
	b[5]->setFocusPolicy( QWidget::TabFocus );
	b[5]->setBackgroundMode( QWidget::PaletteBackground );
	b[5]->setFontPropagation( QWidget::NoChildren );
	b[5]->setPalettePropagation( QWidget::NoChildren );
	b[5]->setText( "" );
	b[5]->setAutoRepeat( FALSE );
	b[5]->setAutoResize( FALSE );

	b[6] = new QRadioButton( this, "RadioButton_7" );
	b[6]->setGeometry( 60, 150, 130, 20 );
	b[6]->setMinimumSize( 0, 0 );
	b[6]->setMaximumSize( 32767, 32767 );
	b[6]->setFocusPolicy( QWidget::TabFocus );
	b[6]->setBackgroundMode( QWidget::PaletteBackground );
	b[6]->setFontPropagation( QWidget::NoChildren );
	b[6]->setPalettePropagation( QWidget::NoChildren );
	b[6]->setText( "" );
	b[6]->setAutoRepeat( FALSE );
	b[6]->setAutoResize( FALSE );

	b[7] = new QRadioButton( this, "RadioButton_8" );
	b[7]->setGeometry( 60, 170, 130, 20 );
	b[7]->setMinimumSize( 0, 0 );
	b[7]->setMaximumSize( 32767, 32767 );
	b[7]->setFocusPolicy( QWidget::TabFocus );
	b[7]->setBackgroundMode( QWidget::PaletteBackground );
	b[7]->setFontPropagation( QWidget::NoChildren );
	b[7]->setPalettePropagation( QWidget::NoChildren );
	b[7]->setText( "" );
	b[7]->setAutoRepeat( FALSE );
	b[7]->setAutoResize( FALSE );

	b[8] = new QRadioButton( this, "RadioButton_9" );
	b[8]->setGeometry( 60, 190, 130, 20 );
	b[8]->setMinimumSize( 0, 0 );
	b[8]->setMaximumSize( 32767, 32767 );
	b[8]->setFocusPolicy( QWidget::TabFocus );
	b[8]->setBackgroundMode( QWidget::PaletteBackground );
	b[8]->setFontPropagation( QWidget::NoChildren );
	b[8]->setPalettePropagation( QWidget::NoChildren );
	b[8]->setText( "" );
	b[8]->setAutoRepeat( FALSE );
	b[8]->setAutoResize( FALSE );

	b[9] = new QRadioButton( this, "RadioButton_10" );
	b[9]->setGeometry( 60, 210, 130, 20 );
	b[9]->setMinimumSize( 0, 0 );
	b[9]->setMaximumSize( 32767, 32767 );
	b[9]->setFocusPolicy( QWidget::TabFocus );
	b[9]->setBackgroundMode( QWidget::PaletteBackground );
	b[9]->setFontPropagation( QWidget::NoChildren );
	b[9]->setPalettePropagation( QWidget::NoChildren );
	b[9]->setText( "" );
	b[9]->setAutoRepeat( FALSE );
	b[9]->setAutoResize( FALSE );

	b[10] = new QRadioButton( this, "RadioButton_11" );
	b[10]->setGeometry( 60, 230, 130, 20 );
	b[10]->setMinimumSize( 0, 0 );
	b[10]->setMaximumSize( 32767, 32767 );
	b[10]->setFocusPolicy( QWidget::TabFocus );
	b[10]->setBackgroundMode( QWidget::PaletteBackground );
	b[10]->setFontPropagation( QWidget::NoChildren );
	b[10]->setPalettePropagation( QWidget::NoChildren );
	b[10]->setText( "" );
	b[10]->setAutoRepeat( FALSE );
	b[10]->setAutoResize( FALSE );

	b[11] = new QRadioButton( this, "RadioButton_12" );
	b[11]->setGeometry( 60, 250, 130, 20 );
	b[11]->setMinimumSize( 0, 0 );
	b[11]->setMaximumSize( 32767, 32767 );
	b[11]->setFocusPolicy( QWidget::TabFocus );
	b[11]->setBackgroundMode( QWidget::PaletteBackground );
	b[11]->setFontPropagation( QWidget::NoChildren );
	b[11]->setPalettePropagation( QWidget::NoChildren );
	b[11]->setText( "" );
	b[11]->setAutoRepeat( FALSE );
	b[11]->setAutoResize( FALSE );

	b[12] = new QRadioButton( this, "RadioButton_14" );
	b[12]->setGeometry( 60, 270, 130, 20 );
	b[12]->setMinimumSize( 0, 0 );
	b[12]->setMaximumSize( 32767, 32767 );
	b[12]->setFocusPolicy( QWidget::TabFocus );
	b[12]->setBackgroundMode( QWidget::PaletteBackground );
	b[12]->setFontPropagation( QWidget::NoChildren );
	b[12]->setPalettePropagation( QWidget::NoChildren );
	b[12]->setText( "" );
	b[12]->setAutoRepeat( FALSE );
	b[12]->setAutoResize( FALSE );

	b[13] = new QRadioButton( this, "RadioButton_15" );
	b[13]->setGeometry( 60, 290, 130, 20 );
	b[13]->setMinimumSize( 0, 0 );
	b[13]->setMaximumSize( 32767, 32767 );
	b[13]->setFocusPolicy( QWidget::TabFocus );
	b[13]->setBackgroundMode( QWidget::PaletteBackground );
	b[13]->setFontPropagation( QWidget::NoChildren );
	b[13]->setPalettePropagation( QWidget::NoChildren );
	b[13]->setText( "" );
	b[13]->setAutoRepeat( FALSE );
	b[13]->setAutoResize( FALSE );

	b[14] = new QRadioButton( this, "RadioButton_16" );
	b[14]->setGeometry( 60, 310, 130, 20 );
	b[14]->setMinimumSize( 0, 0 );
	b[14]->setMaximumSize( 32767, 32767 );
	b[14]->setFocusPolicy( QWidget::TabFocus );
	b[14]->setBackgroundMode( QWidget::PaletteBackground );
	b[14]->setFontPropagation( QWidget::NoChildren );
	b[14]->setPalettePropagation( QWidget::NoChildren );
	b[14]->setText( "" );
	b[14]->setAutoRepeat( FALSE );
	b[14]->setAutoResize( FALSE );

	b[15] = new QRadioButton( this, "RadioButton_17" );
	b[15]->setGeometry( 60, 330, 130, 20 );
	b[15]->setMinimumSize( 0, 0 );
	b[15]->setMaximumSize( 32767, 32767 );
	b[15]->setFocusPolicy( QWidget::TabFocus );
	b[15]->setBackgroundMode( QWidget::PaletteBackground );
	b[15]->setFontPropagation( QWidget::NoChildren );
	b[15]->setPalettePropagation( QWidget::NoChildren );
	b[15]->setText( "" );
	b[15]->setAutoRepeat( FALSE );
	b[15]->setAutoResize( FALSE );

	l[0] = new QLabel( this, "Label_17" );
	l[0]->setGeometry( 20, 30, 30, 20 );
	l[0]->setMinimumSize( 0, 0 );
	l[0]->setMaximumSize( 32767, 32767 );
	l[0]->setFocusPolicy( QWidget::NoFocus );
	l[0]->setBackgroundMode( QWidget::PaletteBackground );
	l[0]->setFontPropagation( QWidget::NoChildren );
	l[0]->setPalettePropagation( QWidget::NoChildren );
	l[0]->setFrameStyle( 50 );
	l[0]->setText( "" );
	l[0]->setAlignment( 289 );
	l[0]->setMargin( -1 );

	l[1] = new QLabel( this, "Label_18" );
	l[1]->setGeometry( 20, 50, 30, 20 );
	l[1]->setMinimumSize( 0, 0 );
	l[1]->setMaximumSize( 32767, 32767 );
	l[1]->setFocusPolicy( QWidget::NoFocus );
	l[1]->setBackgroundMode( QWidget::PaletteBackground );
	l[1]->setFontPropagation( QWidget::NoChildren );
	l[1]->setPalettePropagation( QWidget::NoChildren );
	l[1]->setFrameStyle( 50 );
	l[1]->setText( "" );
	l[1]->setAlignment( 289 );
	l[1]->setMargin( -1 );

	l[2] = new QLabel( this, "Label_19" );
	l[2]->setGeometry( 20, 70, 30, 20 );
	l[2]->setMinimumSize( 0, 0 );
	l[2]->setMaximumSize( 32767, 32767 );
	l[2]->setFocusPolicy( QWidget::NoFocus );
	l[2]->setBackgroundMode( QWidget::PaletteBackground );
	l[2]->setFontPropagation( QWidget::NoChildren );
	l[2]->setPalettePropagation( QWidget::NoChildren );
	l[2]->setFrameStyle( 50 );
	l[2]->setText( "" );
	l[2]->setAlignment( 289 );
	l[2]->setMargin( -1 );

	l[3] = new QLabel( this, "Label_20" );
	l[3]->setGeometry( 20, 90, 30, 20 );
	l[3]->setMinimumSize( 0, 0 );
	l[3]->setMaximumSize( 32767, 32767 );
	l[3]->setFocusPolicy( QWidget::NoFocus );
	l[3]->setBackgroundMode( QWidget::PaletteBackground );
	l[3]->setFontPropagation( QWidget::NoChildren );
	l[3]->setPalettePropagation( QWidget::NoChildren );
	l[3]->setFrameStyle( 50 );
	l[3]->setText( "" );
	l[3]->setAlignment( 289 );
	l[3]->setMargin( -1 );

	l[4] = new QLabel( this, "Label_21" );
	l[4]->setGeometry( 20, 110, 30, 20 );
	l[4]->setMinimumSize( 0, 0 );
	l[4]->setMaximumSize( 32767, 32767 );
	l[4]->setFocusPolicy( QWidget::NoFocus );
	l[4]->setBackgroundMode( QWidget::PaletteBackground );
	l[4]->setFontPropagation( QWidget::NoChildren );
	l[4]->setPalettePropagation( QWidget::NoChildren );
	l[4]->setFrameStyle( 50 );
	l[4]->setText( "" );
	l[4]->setAlignment( 289 );
	l[4]->setMargin( -1 );

	l[5] = new QLabel( this, "Label_22" );
	l[5]->setGeometry( 20, 130, 30, 20 );
	l[5]->setMinimumSize( 0, 0 );
	l[5]->setMaximumSize( 32767, 32767 );
	l[5]->setFocusPolicy( QWidget::NoFocus );
	l[5]->setBackgroundMode( QWidget::PaletteBackground );
	l[5]->setFontPropagation( QWidget::NoChildren );
	l[5]->setPalettePropagation( QWidget::NoChildren );
	l[5]->setFrameStyle( 50 );
	l[5]->setText( "" );
	l[5]->setAlignment( 289 );
	l[5]->setMargin( -1 );

	l[6] = new QLabel( this, "Label_23" );
	l[6]->setGeometry( 20, 150, 30, 20 );
	l[6]->setMinimumSize( 0, 0 );
	l[6]->setMaximumSize( 32767, 32767 );
	l[6]->setFocusPolicy( QWidget::NoFocus );
	l[6]->setBackgroundMode( QWidget::PaletteBackground );
	l[6]->setFontPropagation( QWidget::NoChildren );
	l[6]->setPalettePropagation( QWidget::NoChildren );
	l[6]->setFrameStyle( 50 );
	l[6]->setText( "" );
	l[6]->setAlignment( 289 );
	l[6]->setMargin( -1 );

	l[7] = new QLabel( this, "Label_24" );
	l[7]->setGeometry( 20, 170, 30, 20 );
	l[7]->setMinimumSize( 0, 0 );
	l[7]->setMaximumSize( 32767, 32767 );
	l[7]->setFocusPolicy( QWidget::NoFocus );
	l[7]->setBackgroundMode( QWidget::PaletteBackground );
	l[7]->setFontPropagation( QWidget::NoChildren );
	l[7]->setPalettePropagation( QWidget::NoChildren );
	l[7]->setFrameStyle( 50 );
	l[7]->setText( "" );
	l[7]->setAlignment( 289 );
	l[7]->setMargin( -1 );

	l[8] = new QLabel( this, "Label_25" );
	l[8]->setGeometry( 20, 190, 30, 20 );
	l[8]->setMinimumSize( 0, 0 );
	l[8]->setMaximumSize( 32767, 32767 );
	l[8]->setFocusPolicy( QWidget::NoFocus );
	l[8]->setBackgroundMode( QWidget::PaletteBackground );
	l[8]->setFontPropagation( QWidget::NoChildren );
	l[8]->setPalettePropagation( QWidget::NoChildren );
	l[8]->setFrameStyle( 50 );
	l[8]->setText( "" );
	l[8]->setAlignment( 289 );
	l[8]->setMargin( -1 );

	l[9] = new QLabel( this, "Label_26" );
	l[9]->setGeometry( 20, 210, 30, 20 );
	l[9]->setMinimumSize( 0, 0 );
	l[9]->setMaximumSize( 32767, 32767 );
	l[9]->setFocusPolicy( QWidget::NoFocus );
	l[9]->setBackgroundMode( QWidget::PaletteBackground );
	l[9]->setFontPropagation( QWidget::NoChildren );
	l[9]->setPalettePropagation( QWidget::NoChildren );
	l[9]->setFrameStyle( 50 );
	l[9]->setText( "" );
	l[9]->setAlignment( 289 );
	l[9]->setMargin( -1 );

	l[10] = new QLabel( this, "Label_27" );
	l[10]->setGeometry( 20, 230, 30, 20 );
	l[10]->setMinimumSize( 0, 0 );
	l[10]->setMaximumSize( 32767, 32767 );
	l[10]->setFocusPolicy( QWidget::NoFocus );
	l[10]->setBackgroundMode( QWidget::PaletteBackground );
	l[10]->setFontPropagation( QWidget::NoChildren );
	l[10]->setPalettePropagation( QWidget::NoChildren );
	l[10]->setFrameStyle( 50 );
	l[10]->setText( "" );
	l[10]->setAlignment( 289 );
	l[10]->setMargin( -1 );

	l[11] = new QLabel( this, "Label_28" );
	l[11]->setGeometry( 20, 250, 30, 20 );
	l[11]->setMinimumSize( 0, 0 );
	l[11]->setMaximumSize( 32767, 32767 );
	l[11]->setFocusPolicy( QWidget::NoFocus );
	l[11]->setBackgroundMode( QWidget::PaletteBackground );
	l[11]->setFontPropagation( QWidget::NoChildren );
	l[11]->setPalettePropagation( QWidget::NoChildren );
	l[11]->setFrameStyle( 50 );
	l[11]->setText( "" );
	l[11]->setAlignment( 289 );
	l[11]->setMargin( -1 );

	l[12] = new QLabel( this, "Label_29" );
	l[12]->setGeometry( 20, 270, 30, 20 );
	l[12]->setMinimumSize( 0, 0 );
	l[12]->setMaximumSize( 32767, 32767 );
	l[12]->setFocusPolicy( QWidget::NoFocus );
	l[12]->setBackgroundMode( QWidget::PaletteBackground );
	l[12]->setFontPropagation( QWidget::NoChildren );
	l[12]->setPalettePropagation( QWidget::NoChildren );
	l[12]->setFrameStyle( 50 );
	l[12]->setText( "" );
	l[12]->setAlignment( 289 );
	l[12]->setMargin( -1 );

	l[13] = new QLabel( this, "Label_30" );
	l[13]->setGeometry( 20, 290, 30, 20 );
	l[13]->setMinimumSize( 0, 0 );
	l[13]->setMaximumSize( 32767, 32767 );
	l[13]->setFocusPolicy( QWidget::NoFocus );
	l[13]->setBackgroundMode( QWidget::PaletteBackground );
	l[13]->setFontPropagation( QWidget::NoChildren );
	l[13]->setPalettePropagation( QWidget::NoChildren );
	l[13]->setFrameStyle( 50 );
	l[13]->setText( "" );
	l[13]->setAlignment( 289 );
	l[13]->setMargin( -1 );

	l[14] = new QLabel( this, "Label_31" );
	l[14]->setGeometry( 20, 310, 30, 20 );
	l[14]->setMinimumSize( 0, 0 );
	l[14]->setMaximumSize( 32767, 32767 );
	l[14]->setFocusPolicy( QWidget::NoFocus );
	l[14]->setBackgroundMode( QWidget::PaletteBackground );
	l[14]->setFontPropagation( QWidget::NoChildren );
	l[14]->setPalettePropagation( QWidget::NoChildren );
	l[14]->setFrameStyle( 50 );
	l[14]->setText( "" );
	l[14]->setAlignment( 289 );
	l[14]->setMargin( -1 );

	l[15] = new QLabel( this, "Label_32" );
	l[15]->setGeometry( 20, 330, 30, 20 );
	l[15]->setMinimumSize( 0, 0 );
	l[15]->setMaximumSize( 32767, 32767 );
	l[15]->setFocusPolicy( QWidget::NoFocus );
	l[15]->setBackgroundMode( QWidget::PaletteBackground );
	l[15]->setFontPropagation( QWidget::NoChildren );
	l[15]->setPalettePropagation( QWidget::NoChildren );
	l[15]->setFrameStyle( 50 );
	l[15]->setText( "" );
	l[15]->setAlignment( 289 );
	l[15]->setMargin( -1 );

	Table->insert( b[0] );
	Table->insert( b[1] );
	Table->insert( b[2] );
	Table->insert( b[3] );
	Table->insert( b[4] );
	Table->insert( b[5] );
	Table->insert( b[6] );
	Table->insert( b[7] );
	Table->insert( b[8] );
	Table->insert( b[9] );
	Table->insert( b[10] );
	Table->insert( b[11] );
	Table->insert( b[12] );
	Table->insert( b[13] );
	Table->insert( b[14] );
	Table->insert( b[15] );

	resize( 210,370 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


ColorVectorData::~ColorVectorData()
{
}
