/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: ColorVectorData.h
	Last generated: Sat Oct 16 14:49:47 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ColorVectorData_included
#define ColorVectorData_included

#include <qwidget.h>
#include <qlabel.h>
#include <qbttngrp.h>
#include <qradiobt.h>
#include "tr.h"

class ColorVectorData : public QWidget
{
    Q_OBJECT

public:

    ColorVectorData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ColorVectorData();

public slots:


protected slots:


protected:
    QButtonGroup* Table;
    QRadioButton* b[16];
    QLabel* l[16];

};

#endif // ColorVectorData_included
