/*
** Astrolog (Version 5.42J) File: data2.c
**
** Code changed by Valentin Abramov (valja@tartu.customs.ee)
**
** IMPORTANT NOTICE: The graphics database and chart display routines
** used in this program are Copyright (C) 1991-1998 by Walter D. Pullen
** (Astara@msn.com, http://www.magitech.com/~cruiser1/astrolog.htm).
** Permission is granted to freely use and distribute these routines
** provided one doesn't sell, restrict, or profit from them in any way.
** Modification is allowed provided these notices remain with any
** altered or edited versions of the program.
**
** The main planetary calculation routines used in this program have
** been Copyrighted and the core of this program is basically a
** conversion to C of the routines created by James Neely as listed in
** Michael Erlewine's 'Manual of Computer Programming for Astrologers',
** available from Matrix Software. The copyright gives us permission to
** use the routines for personal use but not to sell them or profit from
** them in any way.
**
** The PostScript code within the core graphics routines are programmed
** and Copyright (C) 1992-1993 by Brian D. Willoughby
** (brianw@sounds.wa.com). Conditions are identical to those above.
**
** The extended accurate ephemeris databases and formulas are from the
** calculation routines in the library SWISS EPHEMERIS and are programmed and
** copyright 1998 by Astrodienst AG.
** The use of that source code is subject to
** the Swiss Ephemeris Public License, available at
** http://www.astro.ch/swisseph. This copyright notice must not be
** changed or removed by any user of this program.
**
** Initial programming 8/28,30, 9/10,13,16,20,23, 10/3,6,7, 11/7,10,21/1991.
** X Window graphics initially programmed 10/23-29/1991.
** PostScript graphics initially programmed 11/29-30/1992.
** Last code change made 12/20/1998.
** Modifications from version 5.40 to 5.41 are by Alois Treindl.
** Modifications from version 5.41 to 5.42 are by Nicolas Scharnagl
*/

#include "astrolog.h"


/*
******************************************************************************
** Constellation Tables.
******************************************************************************
*/

#ifdef CONSTEL
CONST char * ARR szCnstlName[cCnstl+1] = {"",
        "Andromeda", "Antilia", "Apus", "Aquarius",
        "Aquila", "Ara", "Aries", "Auriga",
        "Bootes", "Caelum", "Camelopardalis", "Cancer",
        "Canes Venatici", "Canis Major", "Canis Minor", "Capricornus",
        "Carina", "Cassiopeia", "Centaurus", "Cepheus",
        "Cetus", "Chamaeleon", "Circinus", "Columba",
        "Coma Berenices", "Corona Australis", "Corona Borealis", "Corvus",
        "Crater", "Crux", "Cygnus", "Delphinus",
        "Dorado", "Draco", "Equuleus", "Eridanus",
        "Fornax", "Gemini", "Grus", "Hercules",
        "Horologium", "Hydra", "Hydrus", "Indus",
        "Lacerta", "Leo", "Leo Minor", "Lepus",
        "Libra", "Lupus", "Lynx", "Lyra",
        "Mensa", "Microscopium", "Monoceros", "Musca",
        "Norma", "Octans", "Ophiuchus", "Orion",
        "Pavo", "Pegasus", "Perseus", "Phoenix",
        "Pictor", "Pisces", "Piscis Austrinus", "Puppis",
        "Pyxis", "Reticulum", "Sagitta", "Sagittarius",
        "Scorpius", "Sculptor", "Scutum", "Serpens Caput/Cauda",
        "Sextans", "Taurus", "Telescopium", "Triangulum",
        "Triangulum Australe", "Tucana", "Ursa Major", "Ursa Minor",
        "Vela", "Virgo", "Volans", "Vulpecula"
                                         };

CONST char * ARR szCnstlAbbrev[cCnstl+1] = {"",
        "And", "Ant", "Aps", "Aqu", "Aql", "Ara", "Ari", "Aur",
        "Boo", "Cae", "Cam", "Cnc", "CVn", "CMa", "CMi", "Cap",
        "Car", "Cas", "Cen", "Cep", "Cet", "Cha", "Cir", "Col",
        "Com", "CrA", "CrB", "Crv", "Crt", "Cru", "Cyg", "Del",
        "Dor", "Dra", "Equ", "Eri", "For", "Gem", "Gru", "Her",
        "Hor", "Hya", "Hyi", "Ind", "Lac", "Leo", "LMi", "Lep",
        "Lib", "Lup", "Lyn", "Lyr", "Men", "Mic", "Mon", "Mus",
        "Nor", "Oct", "Oph", "Ori", "Pav", "Peg", "Per", "Phe",
        "Pic", "Psc", "PsA", "Pup", "Pyx", "Ret", "Sge", "Sgr",
        "Sco", "Scl", "Sct", "Ser", "Sex", "Tau", "Tel", "Tri",
        "TrA", "Tuc", "UMa", "UMi", "Vel", "Vir", "Vol", "Vul"
                                           };

#ifndef KDE
CONST char * ARR szCnstlMeaning[cCnstl+1] = {"",
        "Chained Maiden", "Air Pump", "Bird of Paradise", "Water Bearer",
        "Eagle", "Altar", "Ram", "Charioteer",
        "Herdsman", "Chisel", "Giraffe", "Crab",
        "Hunting Dogs", "Great Dog", "Little Dog", "Sea Goat",
        "Keel", "Queen", "Centaur", "King",
        "Sea Monster", "Chameleon", "Drawing Compass", "Dove",
        " Berenice's Hair", "Southern Crown", "Northern Crown", "Crow",
        "Cup", "Southern Cross", "Swan", "Dolphin",
        "Dolphinfish", "Dragon", "Little Horse", "River",
        "Furnace", "Twins", "Crane", "Strongman",
        "Clock", "Sea Serpent", "Water Snake", "Indian",
        "Lizard", "Lion", "Little Lion", "Hare",
        "Scales", "Wolf", "Lynx", "Lyre",
        "Table Mountain", "Microscope", "Unicorn", "Fly",
        "Level", "Octant", "Serpent Bearer", "Hunter",
        "Peacock", "Winged Horse", "Hero", "Phoenix",
        "Painter", "Fishes", "Southern Fish", "Stern",
        "Compass", "Net", "Arrow", "Archer",
        "Scorpion", "Sculptor", "Shield", " Head/Tail of the Snake",
        "Sextant", "Bull", "Telescope", "Triangle",
        "Southern Triangle", "Toucan", "Great Bear", "Little Bear",
        "Sail", "Virgin", "Flying Fish", "Fox"
                                            };
#endif
CONST char * ARR szCnstlGenitive[cCnstl+1] = {"",
        "", "", "2odis", "", "", "", "1tis", "",
        "2is", "", "", "2ri", "2um1orum", " is", " is", "",
        "", "", "", "", "", "tis", "", "",
        "", "", "", "", "is", "", "", "",
        "1us", "nis", "", "", "", "1orum", "1is", "2is",
        "", "", "", "", "", "nis", "nis0is", "2oris",
        "", "", "", "", "", "", "1tis", "",
        "", "1is", "", "is", "nis", "", "", "",
        "is", "2ium", "", "", "1dis", "", "", "",
        "", "is", "", "!1is", "1tis", "", "", "",
        "2i1is", "", " is", " is", "1orum", "1inis", "1tis", ""
                                             };
#endif /* CONSTEL */


/*
******************************************************************************
** Object Calculation Tables.
******************************************************************************
*/

#ifdef MATRIX
CONST byte rErrorCount[oPlu-oJup+1] = {11, 5, 4, 4, 4};
CONST byte rErrorOffset[oPlu-oJup+1] = {0, 72, 72+51, 72+51+42, 72+51+42+42};

CONST real ARR rErrorData[72+51+42*3] = {
    -.001,-.0005,.0045,.0051,581.7,-9.7,-.0005,2510.7,-12.5,-.0026,1313.7,-61.4,
    0.0013,2370.79,-24.6,-.0013,3599.3,37.7,-.001,2574.7,31.4,-.00096,6708.2,
    -114.5,-.0006,5499.4,-74.97,-.0013,1419,54.2,.0006,6339.3,-109,.0007,4824.5,
    -50.9,.0020,-.0134,.0127,-.0023,676.2,.9,.00045,2361.4,174.9,.0015,1427.5,
    -188.8,.0006,2110.1,153.6,.0014,3606.8,-57.7,-.0017,2540.2,121.7,-.00099,
    6704.8,-22.3,-.0006,5480.2,24.5,.00096,1651.3,-118.3,.0006,6310.8,-4.8,.0007,
    4826.6,36.2, /* Jupiter error */

    -.0009,.0037,0,.0134,1238.9,-16.4,-.00426,3040.9,-25.2,.0064,1835.3,36.1,
    -.0153,610.8,-44.2,-.0015,2480.5,-69.4,-.0014,.0026,0,.0111,1242.2,78.3,
    -.0045,3034.96,62.8,-.0066,1829.2,-51.5,-.0078,640.6,24.2,-.0016,2363.4,
    -141.4,.0006,-.0002,0,-.0005,1251.1,43.7,.0005,622.8,13.7,.0003,1824.7,-71.1,
    .0001,2997.1,78.2, /* Saturn error */

    -.0021,-.0159,0,.0299,422.3,-17.7,-.0049,3035.1,-31.3,-.0038,945.3,60.1,
    -.0023,1227,-4.99,.0134,-.02186,0,.0317,404.3,81.9,-.00495,3037.9,57.3,.004,
    993.5,-54.4,-.0018,1249.4,79.2,-.0003,.0005,0,.0005,352.5,-54.99,.0001,3027.5,
    54.2,-.0001,1150.3,-88, /* Uranus error */

    0.1832,-.6718,.2726,-.1923,175.7,31.8,.0122,542.1,189.6,.0027,1219.4,178.1,
    -.00496,3035.6,-31.3,-.1122,.166,-.0544,-.00496,3035.3,58.7,.0961,177.1,-68.8,
    -.0073,630.9,51,-.0025,1236.6,78,.00196,-.0119,.0111,.0001,3049.3,44.2,-.0002,
    893.9,48.5,.00007,1416.5,-25.2, /* Neptune error */

    -.0426,.073,-.029,.0371,372,-331.3,-.0049,3049.6,-39.2,-.0108,566.2,318.3,
    0.0003,1746.5,-238.3,-.0603,.5002,-.6126,.049,273.97,89.97,-.0049,3030.6,61.3,
    0.0027,1075.3,-28.1,-.0007,1402.3,20.3,.0145,-.0928,.1195,.0117,302.6,-77.3,
    0.00198,528.1,48.6,-.0002,1000.4,-46.1 /* Pluto error */
};

OE ARR rgoe[oVes+1+HypuranHi-HypuranLo] = {
    {358.4758,35999.0498,-.0002,.01675,-.4E-4,0,1,101.2208,1.7192,.00045,0,0,0,0,
        0,0}, /* Earth/Sun */
    {102.2794,149472.515,0,.205614,.2E-4,0,.3871,28.7538,.3703,.0001,47.1459,
     1.1852,0.0002,7.009,.00186,0}, /* Mercury */
    {212.6032,58517.8039,.0013,.00682,-.5E-4,0,.7233,54.3842,.5082,-.14E-2,
     75.7796,0.8999,.4E-3,3.3936,.1E-2,0}, /* Venus */
    {319.5294,19139.8585,.2E-3,.09331,.9E-4,0,1.5237,285.4318,1.0698,.1E-3,
     48.7864,0.77099,0,1.8503,-.7E-3,0}, /* Mars */

    {225.4928,3033.6879,0,.04838,-.2E-4,0,5.2029,273.393,1.3383,0,99.4198,1.0583,
     0,1.3097,-.52E-2,0}, /* Jupiter */
    {174.2153,1223.50796,0,.05423,-.2E-3,0,9.5525,338.9117,-.3167,0,112.8261,
     .8259,0,2.4908,-.0047,0}, /* Saturn */
    {74.1757,427.2742,0,.04682,.00042,0,19.2215,95.6863,2.0508,0,73.5222,.5242,0,
     0.7726,.1E-3,0}, /* Uranus */
    {30.13294,240.45516,0,.00913,-.00127,0,30.11375,284.1683,-21.6329,0,130.68415,
     1.1005,0,1.7794,-.0098,0}, /* Neptune */
    {229.781,145.1781,0,.24797,.002898,0,39.539,113.5366,.2086,0,108.944,1.3739,0,
     17.1514,-.0161,0}, /* Pluto */

    {34.6127752,713.5756219,0,.382270369,-.004694073,0,13.66975144,337.407213,
     2.163306646,0,208.1482658,1.247724355,0,6.911179715,.011236955,0}, /* Chiron */
    {108.2925,7820.36556,0,.0794314,0,0,2.7672273,71.0794444,0,0,80.23555556,
     1.3960111,0,10.59694444,0,0}, /* Ceres */
    {106.6641667,7806.531667,0,.2347096,0,0,2.7704955,310.166111,0,0,172.497222,
     1.39601111,0,34.81416667,0,0}, /* Pallas Athena */
    {267.685,8256.081111,0,.2562318,0,0,2.6689897,245.3752778,0,0,170.137777,
     1.396011111,.0003083333,13.01694444,0,0}, /* Juno */
    {138.7733333,9924.931111,0,.0902807,0,0,2.360723,149.6386111,0,0,103.2197222,
     1.396011111,.000308333,7.139444444,0,0}, /* Vesta */

    {104.5959,138.5369,0,0,0,0,40.99837, 0,0,0,0,0,0,0,0,0}, /* Cupido   */
    {337.4517,101.2176,0,0,0,0,50.667443,0,0,0,0,0,0,0,0,0}, /* Hades    */
    {104.0904,80.4057, 0,0,0,0,59.214362,0,0,0,0,0,0,0,0,0}, /* Zeus     */
    {17.7346, 70.3863, 0,0,0,0,64.816896,0,0,0,0,0,0,0,0,0}, /* Kronos   */
    {138.0354,62.5,    0,0,0,0,70.361652,0,0,0,0,0,0,0,0,0}, /* Apollon  */
    {-8.678,  58.3468, 0,0,0,0,73.736476,0,0,0,0,0,0,0,0,0}, /* Admetos  */
    {55.9826, 54.2986, 0,0,0,0,77.445895,0,0,0,0,0,0,0,0,0}, /* Vulkanus */
    {165.3595,48.6486, 0,0,0,0,83.493733,0,0,0,0,0,0,0,0,0}, /* Poseidon */
    {170.73,  51.05,   0,0,0,0,79.22663, 0,0,0,0,0,0,0,0,0}  /* Proserpina */
};
#endif /* MATRIX */

real ARR rStarBright[cStar+1] = {0,
                                 0.46, 2.02, 5.24, 5.09, 0.85, 0.08, 0.12, 1.64, 1.65, 1.70,
                                 0.50, 1.90, 1.98,-0.72, 1.93,-1.46, 1.50, 1.86, 1.58, 0.38,
                                 1.14, 1.82, 1.86, 1.68, 1.98, 1.35, 1.79, 1.58, 1.63, 1.25,
                                 1.77, 0.97, 1.86, 0.61,-0.04,-0.01, 0.96, 1.63, 1.87, 1.85,
                                 0.03, 0.77, 1.94, 1.25, 1.74, 1.16, 4.61,
                                 2.06, 2.83, 2.23, 2.29, 4.33, 2.25, 2.12, 2.23, 3.53, 4.25,
                                 2.37, 2.83, 2.27, 2.08, 2.75, 2.61, 2.23, 2.65, 2.08, 3.24,
                                 2.44, 3.68, 3.27, 2.42, 2.49, 9.99, 9.99, 9.99,9.99,9.99,9.99,9.99
                                };

real ARR rStarDist[cStar+1] = {0,   /*bogus values */
                               0.46, 2.02, 5.24, 5.09, 0.85, 0.08, 0.12, 1.64, 1.65, 1.70,
                               0.50, 1.90, 1.98,-0.72, 1.93,-1.46, 1.50, 1.86, 1.58, 0.38,
                               1.14, 1.82, 1.86, 1.68, 1.98, 1.35, 1.79, 1.58, 1.63, 1.25,
                               1.77, 0.97, 1.86, 0.61,-0.04,-0.01, 0.96, 1.63, 1.87, 1.85,
                               0.03, 0.77, 1.94, 1.25, 1.74, 1.16, 4.61,
                               2.06, 2.83, 2.23, 2.29, 4.33, 2.25, 2.12, 2.23, 3.53, 4.25,
                               2.37, 2.83, 2.27, 2.08, 2.75, 2.61, 2.23, 2.65, 2.08, 3.24,
                               2.44, 3.68, 3.27, 2.42, 2.49, 9.99, 9.99,9.99,9.99,9.99,9.99,9.99
                              };

CONST real ARR rStarData[cStarSmall*6] = {
    1,37,42.9,-57,14,12,   2,31,50.5, 89,15,51,   3,17,46.1,-62,34,32,
    3,49,11.1, 24, 8,12,   4,35,55.2, 16,30,33,   5,16,41.4, 45,59,53,
    5,14,32.3, -8,12, 6,   5,25, 7.9,  6,20,59,   5,26,17.5, 28,36,27,
    5,36,12.8, -1,12, 7,   5,55,10.3,  7,24,25,   5,59,31.7, 44,56,51,
    6,22,42.0,-17,57,21,   6,23,57.1,-52,41,45,   6,37,42.7, 16,23,57,
    6,45, 8.9,-16,42,58,   6,58,37.6,-28,58,20,   7, 8,23.5,-26,23,36,
    7,34,36.0, 31,53,19,   7,39,18.1,  5,13,30,   7,45,18.9, 28, 1,34,
    8, 9,32.0,-47,20,12,   8,22,30.8,-59,30,35,   9,13,12.0,-69,43, 2,
    9,27,35.2, -8,39,31,  10, 8,22.3, 11,58, 2,  11, 3,43.7, 61,45, 3,
    12,26,35.9,-63, 5,57,  12,31, 9.9,-57, 6,48,  12,47,43.2,-59,41,19,
    12,54, 1.7, 55,57,35,  13,25,11.6,-11, 9,41,  13,47,32.4, 49,18,48,
    14, 3,49.4,-60,22,23,  14,15,39.7, 19,10,57,  14,39,35.9,-60,50, 7,
    16,29,24.4,-26,25,55,  17,33,36.5,-37, 6,14,  17,37,19.2,-42,59,52,
    18,24,10.3,-34,23, 5,  18,36,56.3, 38,47, 1,  19,50,47.0,  8,52, 6,
    20,25,38.9,-56,44, 6,  20,41,25.9, 45,16,49,  22, 8,14.0,-46,57,40,
    22,57,39.0,-29,37,20,   0,42, 7.0, 41,16, 0,   0, 8,23.3, 29,05,26,
    0,13,14.0, 15,11, 1,   0,40,30.4, 56,32,15,   1, 9,43.9, 35,37,14,
    2, 2, 2.7,  2,45,51,   2, 3,54.0, 42,19,47,   3, 8,10.1, 40,57,20,
    5,32, 0.4,-0,-17,57,   7,20, 7.4, 21,58,56,   8,58,29.2, 11,51,28,
    11, 1,50.5, 56,22,57,  13, 2,10.6, 10,57,33,  13,23,55.5, 54,55,32,
    14,50,42.3, 74, 9,20,  14,50,52.7,-16, 2,30,  15,17, 0.4, -9,22,59,
    15,34,41.3, 26,42,53,  15,44,16.0,  6,25,32,  17,34,56.0, 12,33,36,
    19,30,43.3, 27,57,35,  21,18,34.8, 62,35, 8,  21,40, 5.5,-16,39,44,
    22,54,39.0,-15,49,15,  23, 3,46.5, 28, 4,58,  23, 4,45.7, 15,12,19,
    18, 5, 53.0, 30, 0, 25, 2,49,14.43,59,31,42.05,18,55,00.98,15,42,32.17,
    17,45,40.0383,-29, 0,28.069,    18,51,33.73 ,0,3,38.13,
    17,45,37.2 ,-28,56,10.22,  12,51,26.28 ,27,07,41.7
};

#ifdef INTERPRET
/*
******************************************************************************
** Interpretation Tables.
******************************************************************************
*/

char * ARR szMindPart[cObjInt+1] = {"earthy nature",
                                    "spirit, ego, image of self, and sense of aliveness",
                                    "emotional nature, moods, feelings, and caring tendencies",
                                    "thoughts, intellect, and communicative activity",
                                    "creativity, tendencies for affection and calmness, and relationship needs",
                                    "will, energy, activity, and aggressive, assertive tendencies",
                                    "enthusiastic, faithful, wise, expansive, spontaneous nature",
                                    "part of mind that is disciplined, respectful, and solitary",
                                    "individuality, desires for change, and tendency to go against social norms",
                                    "intuitive, spiritual, compassionate, psychic nature",
                                    "destiny, and capacity to transform the self and the outer world",
                                    "ability to help, heal, and teach others, and where one has much experience",
                                    "tendency to direct energy to instinctive, creative, reproductive goals",
                                    "tendency to direct energy away from emotional and into mental pursuits",
                                    "tendency to give away individual power for the benefit of a relationship",
                                    "capacity to direct creative energy into personal or devotional goals",
                                    "karmic goals, and best direction of evolutionary growth",
                                    "capacity to let go and accept their natural darker side",
                                    "capacity to let go and accept their natural darker side",
                                    "karmic fate and method of reception of energies",
                                    "generalized projected personality and outward appearance",
                                    "personality and outward appearance, as projected to the world",
                                    "", "", "", "", "", "", "", "",
                                    "view as seen in the eyes of others, reputation, and social standing",
                                    "", "",
                                    "place where opportunity and success can be found"
                                    ,"", "","",
#ifdef ASTEROIDS
                                    "secrets,things happening quickly,keeper of the wine", /* Centaurs */
                                    "glamourous capacity and perspective,barbie",
                                    "beauty of disillusion, gothic style",
                                    "outcast attitude",
                                    "misty state of mind,advice not listened to,kissing,radiating person",
                                    "origin of self, revelation,game of dominoes",
                                    "door to the nagual, the hidden self",
                                    "routine,modesty",
                                    "instability, madness, panic, invasion by something alien.",
                                    "Expression of self and ego through word and writing.  Positive: Excellent communication, articulate, precise.  Negative: Verbose, boastful, shallow in conversation.",
                                    "quest for being part in something great,Relational and professional attitudes based upon one another. I am what I am because of my career status or relationship ornament. Positive: Balance between relationship and work, money and sexuality. Negative: Object oriented, status seeking, mercenary in work ethics, stunned by glamour and beauty of partner.",
                                    "spirit of solitude,Conflict between ego and material possession, identity as a function of resources. Positive: confidence in inner resourcefulness, which allows for use of all talent. Negative: materialistic, avaricious, beliefs possessions equal identity.",
                                    "",
                                    "cyclonic energies,global circulation,sexual extremes", /* transneptunians */
                                    "sense of greatness,true mind,arrogance",
                                    "tendency for splendid isolation, a key to the nagual,peaceful tranquility",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "opportunity to transform the self and the outer world",
                                    "certain darker transformative qualities",
                                    "chaotic string",
                                    "",
                                    "enjoying wilderness,explaining nature",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "", /* End transneptunians */
                                    "plantlike persona",
                                    "inner psyche",
                                    "Fortuna",
                                    "Ariadne",
                                    "",
                                    "Pandora",
                                    "Eurydike",
                                    "Eris",
                                    "sense of a beautiful dawn",
                                    "",
                                    "Elektra",
                                    "",
                                    "philosophical side",
                                    "",
                                    "Cupido",
                                    "Hybris",
                                    "urge to do something",
                                    "learning to deal with the marginalized,the downtrodden,repression,paradise lost",
                                    "Aphrodite",
                                    "indicator of drastic change, peer pressure, danger and crisis",
                                    "promethian side",
                                    "indian love god",
                                    "feeling for one's own tribe or clan", /* End other asteroids */
                                    "Muse of Tragedy",
                                    "Muse of heroic poetry",
                                    "Muse of comedy",
                                    "Muse of music and lyric poetry",
                                    "Muse of astronomy and astrology",
                                    "Muse of singing and rhethoric",
                                    "Muse of song and dance",
                                    "Muse of choral dance and song",
                                    "Muse of history",
                                    "tendency to fly high", /* Apollos */
                                    "",
                                    "desire for confrontation",
                                    "apollonic side",
                                    "",
                                    "Daedalus",
                                    "Cerberus",
                                    "feeling of working in vain",
                                    "midas touch",
                                    "Bacchian attitude",
                                    "Adonis side",
                                    "capacity to endure pain",
                                    "point where ambition and nepotism would have disastrous consequences",
                                    "Orpheus",
                                    "dream",
                                    "heraklian side",
                                    "eros",
                                    "division of the heart into human and divine",
                                    "fallen or flawed heroism and capacity for resurrection and redemption",
                                    "smoking mirror,darkness,scheming; criminal, predatory or antisocial behavior",
                                    "unsympathic side",
                                    "quixotic side",
                                    "dionysian qualities",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
#endif
                                    "group associations and matters relating to art",
                                    "dark, secretive, past, shameful side",
                                    "fiery, creative, leadership tendencies",
                                    "lofty, extraordinary parts",
                                    "progressive, abundant energies",
                                    "intense, focused nature",
                                    "greatly forceful energies",
                                    "sudden recovery ability",
                                    "idealistic, honorable side"
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    ""
#ifdef ASTEROIDS
                                    ,"protective, subjective side, with confidence in raw talents and nurturing instincts",
                                    "",
                                    "charisma, inspiration, sending others out to fight, kamikaze assaults, assassins, crusades, jihads, threats and other negativity created by society itself, retribution upon (a) society for its misguided behavior",
                                    "renunciation, disownment, sacrifice, suicide, choosing death, destruction, murder, asceticism, revulsion, choosing the road less traveled, secret powers, plotting, intensity",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "structural weakness,The need to assert one's accomplishments (generally professional) in the interest of recognition.  Positive: sense of self accomplishment, legacy oriented, a mentor. Negative: solicitousness, bragging, indiscriminate flirting.",
                                    "balancing emotions and ego as a function of professional status.  ",
                                    "sense of value, self worth, economic freedom with spiritual emphasis.",
                                    "Use of complete compassion and forgiveness toward others.Positive: Understanding, compassionate, forgiving, tolerant. Negative: Full of guilt and shame - projected onto others.  ",
                                    "Maintaining a balance of individuality and others within the domestic environment.  Positive: Feeling accepted by family and close friends.  Negative: Portraying black sheep image. Isolated and sullen at home. Doing it for family to the extreme.",
                                    "Balance of emotional/nurturing give and take. Positive: Encouraging, nurturing, responsive. Negative: Whining, needy, clinging. Emotionally manipulates closeness, then withdraws from it.",
                                    "Need for relational support without reservation. Positive: Renders and receives in relationship in healthy balance. Negative: Co-dependent, turns intimate relationships into parent-child scenarios.",
                                    "cynism, knowing the score,the power of knowledge comes to light. Those who know rule the world.",
                                    "Perceptions of an abundant Universe. Positive: Generous,available and sharing. Negative: Greedy, hostile regarding work position and money earned. Desperately competitive.",
                                    "",
                                    "Acute relationship awareness. Ability to negotiate relationship conflicts.  Positive: Clarity in relationship communication. Honest, direct, self assured in interactions.  Negative: Clingy, dependent, holds back on communication based upon perceived reactions.",
                                    "desire machine",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "clarity, being true to oneself, being blasphemous, defaming,regardless of a potentiation of destructive energy,breakdown,collapse",
                                    "Cosmic picture vs. detail orientation. Abstract logic vs linear logic.  Positive: Balanced perspective of overviews combined with essential detail.  Negative: Picky, judgmental, cantankerously weird, ungrounded.",
                                    "tendency to check things out,obsessive curiosity and inquisitiveness, open-mindedness,hurdles,obstruction Positive: Questioning and open minded. Negative: Overly scrutinizing specializing in Pandora's box scenarios.",
                                    "Emotional intensity, passionate creativity, inspirational capacity.  Positive: Uplifting, stimulating, infinitely artistic and creative.  Negative: Addicted to emotional drama, emotionally controlling and manipulative.",
                                    "Quintessential grounding. Practicality without being buried by life's demands. Positive: willing to shoulder responsibility, effective in time/work management, grounded and with lofty visions and aims. Negative: materialistic, greedy, wasteful, resentful, inefficient in use of time,prone to laziness motivated by belief \"the world owes me.\"",
                                    "Quest for ultimate individuality. Confident in all aspects of self. Positive: Iron will and certainty of healthy eccentricity and imaginative ability. Negative: Weird just to be contentious. Overbearing ego. Sense of intellectual superiority.",
                                    "Perfection seeking, looking for Divine Order. Positive:  Accepting, tolerant and compassionate. Negative: Scrutinizing to a fault, viciously critical, intolerant, mean spirited practical jokes.",
                                    "",
                                    "Seeking kinship with those of great self reliance. Positive: Confident, giving and supportive. Strong sense of bond with those of similar spirit. Negative: Sullen, withdrawn but emotionally aggressive.",
                                    "quest for pure self expression. Positive: Clear, articulate, assertive, confident. Negative: Accusatory, meddlesome, laborious in conversation.",
                                    "",
                                    "Claiming of soul urge. Development of pure confidence and self assuredness. Positive: Strong, inspired, non-competitive, motivated. Negative: Possessive, insecure, ego proclaiming, pouting, fearful.",
                                    "Acceptance of whole and pure nurturing.  Positive: Acceptance of support and responsive to praise.  Negative: Rejecting of those attempting to help. Constant complaining about the lack of fundamental care in life.",
                                    "Primal sense of self. Developing a healthy self referential attitude.  Positive:  Confidence in raw talents.  Self assured nurturing instincts.  Negative:  Overly subconscious in motivations.  Subjective and projective.  Extremely protective.",
                                    "urge to establish self value regardless of relationship status. Positive:  Warm, supportive, nurturing in one to one relationship.  Negative:  Needy, self centered to a fault, showcase relationships.",
                                    "balance of individuality for the purpose of soul fulfillment,regardless of ego. Positive: Confident and self assured in expressing uniqueness and ingenuity.  Negative: Cranky weird, contentious, highly rebellious.",
                                    "urge to understand unresolved questions and mysteries through discussion. Positive: Highly insightful ability to ask questions. Negative: Incessant questioning and banal fixations.",
                                    "",
                                    "Complete, uninhibited self-expression. Positive: Innovative, confident, inspired, pleasantly odd. Negative: Narcissistic, self-absorbed, strange for shock value.",
                                    "Definition of absolute truth. Conviction to principle without zeal. Tolerance of all beliefs. Positive: open-minded and sharing especially in religious, philosophical matters, knows the ecstasy of knowing. Negative: zeal, fanaticism, religious intolerance, bigotry, social stupidity through biases.",
                                    "Creative weirdness at its best. Contemplative and deliberate in spiritual exercises. Positive: clear self-understanding through retreat and silence, willingness to share positive eccentricities. Negative: off the wall, contentious, arrogant and bitter.",
                                    "Seeking understanding of sacred and profane in balance.  Positive: Unique blend of linear and abstract minds. Negative: Mentally biased and opinionated with no tractability.",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "Highly questioning nature. Asks surface level questions seeking the greatest depth in the answer. Positive: Seeking, questioning unafraid of shadows. Negative: Diverting, avoiding, asks questions to answer a question.",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
#if 1
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
                                    "",
#endif
#endif
                                   };

char * ARR szDesc[cSign+1] = {"",
                              "forceful, energetic, direct, courageous",
                              "practical, often skeptical and stubborn",
                              "inquisitive, witty, perceptive, adaptable",
                              "introspective, emotional, protective",
                              "proud, gregarious, dramatic, dignified",
                              "analytical, critical, modest, helpful",
                              "affectionate, tolerant, often indecisive, appreciates beauty",
                              "penetrating, suspicious, introspective",
                              "jovial, open minded, loves freedom",
                              "industrious, practical, disciplined",
                              "progressive, erratic, revolutionary, idealistic, humanitarian, inventive",
                              "imaginative, other worldly, impressionable"
                             };

char * ARR szDesire[cSign+1] = {"",
                                "seeks adventure and challenge",
                                "loves serenity and inner peace",
                                "seeks out information",
                                "wants inner and outer security",
                                "desires self expression",
                                "works toward perfection",
                                "seeks balance, relationship, and calmness",
                                "desires to transform and remove outer masks",
                                "seeks meaning and new experience",
                                "works for solitude and personal integrity",
                                "desires individuality",
                                "seeks transcendence of self"
                               };

char * ARR szLifeArea[cSign+1] = {"",
                                  "establishment of personal identity",
                                  "self image, self worth, and material security",
                                  "communicating to and receiving from the environment",
                                  "imagination, fantasies, inner feelings, and domestic life",
                                  "finding joy, pleasure, and creative expression",
                                  "work and feeling talented and useful",
                                  "personal relationships and intimacy",
                                  "sex, death, the occult, and other hard to grasp topics",
                                  "changes, exploration, and the breaking of routine",
                                  "career, social stature, and destiny",
                                  "the future, life goals, and association with friends and groups",
                                  "things that disrupt or cause disassociation with the personality"
                                 };

char * ARR szInteract[cAspectInt+1] = {"",
                                       "is %sconnected and fused together with",
                                       "%sopposes and creates tension with",
                                       "is %sin conflict with",
                                       "is %sin harmony with",
                                       "has %sopportunity for growth, exchange, and harmony in relation with",
                                       "is %sdifferent from",
                                       "%sgets new perspectives in relation with",
                                       "%screates internal friction with",
                                       "%screates internal agitation with",
                                       "%screatively relates externally with",
                                       "%screatively relates internally with"
                                      };

char * ARR szTherefore[cAspectInt+1] = {"",
                                        "Both parts are prominent in their psyche", "Balance is needed",
                                        "Adaptation is required by both sides", "", "",
                                        "They can often relate in a discordant way", "", "", "", "", ""
                                       };

/* Modifier array makes the interpretation stronger for narrower orbs. */

char * ARR szModify[3][cAspectInt] =
{{"always ", "always ", "irreconcilably ", "always ", "much ",
        "completely ", "often ", "often ", "often ", "often ", "often "},
    {"", "", "", "", "", "", "", "", "", "", ""},
    {"somewhat ", "somewhat ", "somewhat ", "somewhat ", "some ", "somewhat ",
     "sometimes ", "sometimes ", "sometimes ", "sometimes ", "sometimes "}
};

char * ARR szSabian[nDegMax] = {
    "A woman has risen from the water; a seal has emerged also, and is embracing her.",
    "A comedian is entertaining a group of friends.",
    "A cameo shows the profile of a man that suggests the outline of his country.",
    "Two lovers are strolling through a secluded walk.",
    "A white triangle is seen; it has golden wings.",
    "A black square stands firmly, illumined red on one side.",
    "A man comes forward flushed with the successful and simultaneous expression of his talents in two separate realms.",
    "A large old-fashioned woman's hat is revealed with streamers flying in a stiff breeze from the east.",
    "A seer gazes intently into a crystal ball before him.",
    "A savant is revealed, a man who has created new forms for old symbols that have lost their meanings.",
    "The president of the republic, or the ruler of his country, is presented.",
    "A flock of white geese is seen in flight overhead.",
    "A bomb that has failed to explode is now safely hidden from discovery.",
    "A serpent is circling a man and a woman, who are very engrossed in each other.",
    "An Indian is silently but deftly weaving a basket in the light of the setting sun.",
    "Brightly clad brownies are seen dancing in the warm dying light.",
    "Two prim spinsters are quietly sitting together.",
    "An empty hammock hangs between two lovely trees.",
    "A magic carpet hovers over the depressing reality of every-day life in an industrial area.",
    "A young girl is seen feeding the swans in a sheltered public park.",
    "A pugilist, flushed with life and strength, is entering the ring.",
    "A handsome grilled gateway opens to the garden of all desired things.",
    "A woman clothed in the delicate tints of early summer is seen carrying a heavy and valuable yet veiled burden.",
    "An open window of an old-fashioned room is seen, the net curtain is blowing inward into the shape of a cornucopia.",
    "A double promise revealed by some suggestive event of both immediate or literal and sentimental significance.",
    "A man is seen burning to incandescent heat with the wealth of that which he has to give.",
    "A panorama of blending events out of the past shows the regaining of lost opportunity through the imagination.",
    "A large audience is seen, rejoicing in some disillusionment to which it has just been subjected.",
    "A celestial choir has risen to sing.",
    "A duck pond is revealed, on which a young brood of ducklings are disporting themselves.",
    "A clear mountain stream flows steadily through a rocky defile.",
    "A brilliant electrical display illuminates the heavens and the forests beneath.",
    "A beautiful expanse shows natural steps leading upward to a lawn of clover in full bloom.",
    "The rainbow's pot of gold is revealed in the midst of a shower of sparkling and flashing colors.",
    "A youthful widow, fresh and soul-cleansed from grief, kneels at a grave to receive the secret of eternal life.",
    "A delicate cantilever bridge is in process of construction across a high narrow gorge.",
    "Out of the past comes the \"woman of Samaria\" to draw water from Jacob's well.",
    "A sleigh, with all the suggestive warmth of the winter season, speeds over ground on which the snow is yet to fall.",
    "A Christmas tree, bending with its weight of gifts, is illumined at the end of a vast darkened hall.",
    "A pretty lass in Red Cross uniform is hurrying about the duties that a warm sympathy has dictated.",
    "A woman, cool in sunbonnet and simple garments, is leisurely watering long rows of flowers in full bloom.",
    "A quite youthful young couple is walking down a busy street, stopping to peer into every window with joyful glee.",
    "A man very cheerful in his working clothes is handling a mountain of baggage the best he can.",
    "Several children are splashing with delight in a receding tide, and at their feet are shellfish groping for shelter.",
    "A man in evening clothes, muffled to breast the storm through which he walks, yet wears his top hat rakishly.",
    "An old man is attempting, with a degree of success unsuspected by him, to reveal the Mysteries to a motley group.",
    "An imaginative battle is underway, between swords, the disciples of might, and torches, the disciples of enlightenment.",
    "A woman is holding a linen bag out of her window, to give it fresh air and sunshine.",
    "A newly formed continent is seen, fresh and green within its setting of interminable ocean.",
    "Light scurrying wisps of clouds are streaming in rapid movement across the sky.",
    "A moving finger points to the significant passages in a large open book.",
    "A white homing pigeon flies straight and fearlessly over a broad body of troubled water.",
    "A magnificent jewelry shop is revealed, containing every conceivable article of value or beauty.",
    "A mounted Indian brave rides proudly, with human scalps as trophies at his belt.",
    "A magnificent public park spreads its charm before the eye in a vista that awes the loftiest spirit.",
    "A Spanish gallant stands at the window grill of his love, serenading her with the softer melodies of night.",
    "A hopelessly withered old Indian woman, with a clear light persisting in beady eyes, is selling trinkets.",
    "A woman in middle life stands in rapt sudden realization of forgotten charms, in unexpected recovery of romance.",
    "Two garrulous cobblers are working side by side upon their ancient bench.",
    "A peacock parades its splendor on the quiet lawn of an old palace garden, in dignified silence.",
    "A glass-bottomed boat drifts silently and easily over a constantly shifting panorama of marine wonders.",
    "A nervous gentleman, dressed in an elaborate Santa Clause costume, is filling Christmas stockings furtively.",
    "An etching or rare beauty displays a charming court life at the garden of the Tuileries, under Louis XIV.",
    "A series of rooms in a hospitable house, opening one into the other, are decorated gaily with holly and mistletoe.",
    "A publication, devoted to some vital moment for human welfare, flaunts an attention-compelling cover.",
    "In flaring artificial light, amidst ghostly steam escaping through the rigging, grimy workmen are drilling for oil.",
    "An old fashioned well, still yielding the purest and coldest of waters, stands invitingly near a shade of trees.",
    "A great industrial plant is closed down, and around it mills a crowd of agitators and striking workmen.",
    "A medieval archer stands with the ease of one wholly sure of himself, bow in hand, his quiver filled with arrows.",
    "An airplane dives toward the earth as though falling, but rights and recovers itself with smooth gracefulness.",
    "A new real-estate subdivision is revealed with wide paved streets, ornamental lights and a few freshly-built houses.",
    "A little black slave girl of antebellum days, with crinkly hair and saucy eyes, demands her rights of her mistress.",
    "The great artist, a world famous pianist, sits at his instrument on the stage of a huge auditorium.",
    "Two people, at widely different points, are in conversation with each other by means of telepathy.",
    "Two Dutch children in their immaculate native costumes, are studying their lessons together.",
    "A woman agitator stands upon a platform, making an impassioned plea to a surrounding group of men.",
    "The head of a handsome youthful athlete slowly changes into a different type of beauty, the mature thinker.",
    "Standing apart from the passing stream of well-dressed shoppers, two Chinamen in San Francisco are talking Chinese.",
    "In the somber archives of a sedate museum a large archaic volume is somewhat conspicuously displayed.",
    "A self-service restaurant, the cafeteria such as originated in Los Angeles, displays its inviting steam tables.",
    "A throbbing mass of humanity have packed the confines of a city square; it is a labor demonstration.",
    "An old-fashioned \"harvest home\" festival is at its height, with flashing dancing couples crowding the barn floor.",
    "Three fledglings, secure in their nest high in the tree, already reveal the deep pride of their heritage.",
    "A group of carefree children, gaily dressed for their sport, are skating about a smoothly frozen backwoods pond.",
    "A gardener, with all of a mother's care for her child, is trimming a magnificent row of tropical palms.",
    "The winter frost has stolen through the woods, and given to the trees and underbrush a witching cosmic lacery.",
    "A young gypsy youth comes springing out of the forest, regarding the spreading vista before him with deep interest.",
    "A man is leaving a courtroom with mixed feelings of relief & determination; he has just passed through bankruptcy.",
    "High in a tree that has given only the faintest evidence of returning spring, a mocking bird delivers its repertoire.",
    "A typically American conceit is seen; a parade of bathing beauties before the judges and crowd at a seaside resort.",
    "A man upon a ship stands impatiently with a flag in his hands, ready to run it up in place of the one now flown.",
    "An alert and eager individual rests upon a magic carpet, observing a vast level vista over which he hovers motionless.",
    "Through the cold darkening depths of a Northern canyon a man all bundled up in furs leads a shaggy reindeer.",
    "In an imaginative tableau a hungry cat is seen arguing earnestly with the mouse who is to be her victim",
    "A man in an automobile, maddened by the lust for speed, races with a fast train and loses; he is killed.",
    "It is in the flush of spring, and innumerable wild or game birds are seen feathering their nests.",
    "In a fairy glade, in a quiet circle of moonlight, two of the little people are executing a fanciful dance.",
    "An imaginary land of rabbits is revealed, with its citizens faultlessly dressed and on dignified parade.",
    "A little miss, innocently devoid of any suggestion of clothing, leans over to catch a goldfish in a sparkling pond.",
    "A large and beautiful diamond, in the hand of the lapidary, is now to be cut to its full perfection.",
    "A clown is making merry, gently caricaturing all manners of human traits with his grimaces and pantomime.",
    "A slant-eyed Chinese woman is nursing a baby, and about the child is the glorious nimbus of divine incarnation.",
    "A hand, which is held out receptively, is remarkable for the suggestion of character in its prominent thumb.",
    "A very old man, whose feebleness adds strangely to his dignity, stands alone, facing the darkness in the northeast.",
    "A group of merry sluggish individuals are resting; they have over eaten most indiscreetly, and enjoyed it.",
    "A futuristic editorial office provides unconscious symbolism: table, manuscript, martial visitor; all are square.",
    "A huge precious stone is so cut that its principal facet mirrors the whole scene before it in sparkling miniature.",
    "On all sides is the bustle of the barnyard, and its life, old-fashioned and natural, a hen clucks among her chicks.",
    "A fragile miss, representative of proud old blood, is wed by a pompous priest to an eager youth of the new order.",
    "During the celebration of some fete the canals of Venice are crowded; in a gondola are serenaders, merry-making.",
    "The magnificent opera house, with its glittering audience, rests in silence; the prima donna is singing.",
    "A young woman, neatly attired in outing clothes, with eyes softened by dreaming, awaits a sailboat headed toward her.",
    "A serious little study group, a literary club, has met for social and intellectual fellowship in some member's home.",
    "Three castaways, a woman and two men, stand upon a bit of glorious sunlit land, facing the broad southern ocean.",
    "A leader of men, erect and fearless, suddenly finds thrown across his right shoulder an invisible mantle of power.",
    "The magnificent, luxurious library of some wealthy home is revealed; among the cushions several guests are reading.",
    "In a normally peaceful canyon, with wealthy secluded ranches, a furious storm seems to multiply its terrors.",
    "An American Indian girl, college trained but returned to her people, seeks to win their friendship for her lover.",
    "A Grecian pastoral allegory is seen; a peasant lass is mother of twins and these a Muse now weighs in golden scales.",
    "A \"Daughter of the American Revolution\" walks proudly to the rostrum; it is the meeting of some women's society.",
    "A fat and normally good-natured little man of affairs is bursting with determination to have his own way.",
    "Several children are having holiday together; an epidemic of mumps has given them new, not unpleasant fellowship.",
    "A woman of middle years is bobbing her hair for the first time; a look of rebellion melts to surprised anticipation.",
    "An elderly man in evening clothes, of poised and military bearing, stands alone before a lovely mounted moose head.",
    "Overhanging a vast canyon, but giving evidences of thousands of years of survival, are suggestive masses of granite.",
    "A sweet old-fashioned belle, and a pert and attractive little modern flapper, stand in mutual envy of each other.",
    "The night heavens are seen in their wonder, as on the desert when the moon is dark; the constellations are at play.",
    "A man of mean and low appearance, but with the burning fire of a great cause in his eyes, is stirring up discontent.",
    "In a scene of weird display and brilliant colors, glass-blowers produce, one-by-one, the marvels of their craft.",
    "Everywhere there is a sparkle, and nature is revealed in pastel colors; the early morning dew salutes the sunlight.",
    "Beneath a huge oak, which holds back the rising heat of noon, some children potter at their games in a great swing.",
    "Japanese lanterns, music from a string ensemble & an animated interweaving of colorful figures mark a garden party.",
    "A bit of green grass before a neatly flowered cottage by the sea supports a chair in which an old sea captain rocks.",
    "Seen in the form of a cherub, whispering soft coaxing words into every receptive ear, a human soul seeks expression.",
    "The great American carnival, the Mardi Gras at New Orleans, is seen with a wealth of floats, decorations and merriment.",
    "The sunshine floods the sleepy village street; a storm has left everything drenched, and wondrously refreshed.",
    "A volunteer church choir is seen during rehearsal, far more interested in social than musical elements of the occasion.",
    "An instructor in chemistry is conducting an experiment before his class, in the midst of a maze of apparatus.",
    "A clubhouse built upon a floating barge is gaily decorated, and crowded with revelers; the water reflects its lights.",
    "A group of prehistoric American Indians are seen in the course of an elaborate and impressive invocation to the sun.",
    "An unwitting allegory is enacted by a few chickens who have gotten at some fermented seed, and are happily intoxicated ",
    "A carrier pigeon comes swiftly through the early light of morning, and flutters to the feet of a group of fanciers.",
    "The scene is a circus, crowded with spectators, and in a moment of hush a bareback rider performs extraordinarily.",
    "A strange figure is revealed, outwardly unprepossessing, untidy, unkempt; he is a yogi of transcendent powers.",
    "A solitary camel crosses the desert with his rider; he is indifferent to the hazards of storm and lack of supplies.",
    "A perfect rainbow forms slowly in the summer rain as the sun begins to break through the rather thin cloud banks.",
    "Over at the eastern edge of night the streaks of dawn appear; gradually the mounting light wipes out the stars.",
    "Innumerable little birds have settled down upon one large tree; they chirp happily to each other in endless rows.",
    "A mermaiden has climbed to the rocky shore of a bleak coast, she awaits the prince who will bring her immortality.",
    "Into a letter is poured vital and confidential information; it is folded carefully, but the envelope is not sealed.",
    "A man's head is revealed; it is a portrait in which the artist has sought to idealize the best of human character.",
    "A simple but impressively large white cross has been set up in splendid isolation, up on top of a commanding eminence.",
    "A glorious vision unfolds over a little struggling family in the wilderness; two mighty angels bringing protection.",
    "A little black child is playing with white children; neither he nor they are aware of the racial difference.",
    "A man lies dreaming in the shade of an Irish countryside; his dream brings to him the playful \"little people\".",
    "Children's voices, and the smiles of elders; it is a merry-go-round with blatant music and unrestrained joyousness.",
    "The women's quarters of an Oriental palace are revealed; here are the bright and unafraid eyes of cloistered souls.",
    "A poor little rich girl, not above five years of age, is given, with much attendance, a first dancing lesson.",
    "An earnest but bizarre looking individual is painting upon a canvas; his art is futuristic and unintelligible.",
    "As if in a moment of vision a man is seen possessed of two heads; both of these look out and beyond the shadows.",
    "A beautiful boy is revealed; he is \"all boy\" in every way, but in him lives too the idealization of a wise mother.",
    "A bride rises laughing, youthfully radiant in her white, wishing to scold the groom who has snatched away her veil.",
    "A statesman stands before the mob; his \"strong hand\" can be seen in a transforming of hysteria into new enthusiasm.",
    "A large sheet of parchment is covered with finely lettered names and mysterious lines; it is a splendid family tree.",
    "A handkerchief, of the finest linen and oldest lace, lies folded near milady's mirror, by a bottle of rare perfume.",
    "The delighted children are crowded about a cage in the zoo; an orang-utan is sitting in a spot of afternoon sun.",
    "A vast display of cosmic force is seen in the eruption of a volcano; dust clouds, flowing lava, earth rumblings.",
    "Two giggling young girls are sitting facing each other, knees tightly touching, working a Ouija board on their laps.",
    "There is a colorful gallery, upon the warm summer day; in the clear blue water a swimming race nears its decision.",
    "A group of old-fashioned automobiles comprise a caravan of settlers on the move; a fresh enthusiasm marks the party",
    "A large cheerful but bare room holds two teams of fresh young girls engaged in a laughing contest of basketball.",
    "Upon rich velvet in a case, at an exhibition, is an exquisitely wrought miniature; a jewel-set royal coat-of-arms.",
    "A man, clad in gay colors of the circus, rushes into the barred arena, where unwilling animals await his bidding.",
    "A large book for children is open at a colored page; here Mary with her yellow curls leads an immaculate white lamb.",
    "A large glorious public building is seen set in a spacious park, before it a flag moves with the breezes at half-mast",
    "A highly ritualistic service is in process; officiating priests are automatons, a boy with a censer is rapt-eyed.",
    "In the luxurious quarters of a home furnished in delicate period style, elderly ladies are enjoying afternoon tea.",
    "A bald-headed man in uniform completely dominates an assembly of men: diplomats, scientists and industrialists.",
    "A scholar has just succeeded in deciphering an archaic manuscript; it holds an idea for which he has long sought.",
    "A suburbanite grins; an emergency call to the house of a neighbor frees him from some item of household drudgery.",
    "A symbolical painting is seen; a beautiful butterfly meeting sacrificial death through an impaling dart of wisdom.",
    "A new symphony is played by the orchestra; the music dramatizes racial progress from aspiration to realization.",
    "A new day dawns, and when the light permits the recognition of detail it can be seen that all things are changed.",
    "A group of students of higher truth, in summer conference, are seated about a camp fire in unconscious meditation.",
    "A teacher of the occult betrays his possession of the \"real knowledge\" by the inspiration of his gathered students.",
    "A pilgrim sits on a rustic bench, and one-by-one his ideals, in a sort of trance vision, take form before him.",
    "An eccentric old witch is feeding her chickens, and seeking to allay their fear of a hawk whom she has just tamed.",
    "In the depths of the woods is an abandoned farm, and in the deserted house a fireplace blazes merrily, mysteriously.",
    "Three \"Old Masters\" hang together in an art gallery; they have a room to themselves, and seem to hold converse.",
    "Placid waters are revealed, at the bottom of a narrow rapids; a canoe is rapidly and surely approaching safety.",
    "A kindly old professor, from his battered desk, looks out over his eyeglasses at a class eagerly awaiting his words.",
    "A workers' shift is finished, and the miners emerge from their grimy hole into daylight and life above ground.",
    "A children's birthday party is in progress, upon a side porch a group of youngsters are blowing soap bubbles.",
    "The courtyard of a Spanish hacienda in a tropical country is revealed; in its shade the master takes a noon siesta.",
    "An odd looking collection of machinery parts lie together; all are new, and ready to use, all are circular.",
    "The storms of the winter have washed away the boat-landing; some happy souls at the beach resort are building one.",
    "A retired sea-captain, still resplendent in his uniform, frequents the docks from which the world's commerce departs.",
    "Two men are placed under arrest and taken away to give an accounting for their acts before the tribunal of society.",
    "A gang of robbers are seen in hiding, ready and anxious to attack the heavily armed caravan just coming into sight.",
    "In a tiny room ridiculously cluttered with manuscripts and books sits a Jewish rabbi, at ease with self and world.",
    "It is a hot Sunday afternoon in summer, and upon the beach is a milling crowd, enjoying precious ocean freshness.",
    "A little child is laughing as the water is turned into an artistic little fountain, as the birds hurry to drink.",
    "Chanticleer mounts the corner post of the fence; never will the day again be greeted with the enthusiasm now born.",
    "A marvelously colored and figured butterfly is spread before the eyes; on its left side is an extra or third wing.",
    "A little boy, rebellious against school, watches a fluttering autumn leaf that seems to spell out his lesson for him ",
    "In an allegorical representation an eagle and a large white dove are revealed constantly changing into each other.",
    "Like a great soaring bird, a single brilliant spot in a bright sky, an aeroplane far overhead sails about calmly.",
    "A man stands alone in surrounding gloom; were his eyes open to spirit things he would see helping angels arriving.",
    "It is a seer's dream: Vast masses of humanity push forward in frantic effort to cross the black chasm to knowledge.",
    "The phrenologist is reading \"bumps\" for his clients; he explains three mounds of knowledge on a philosopher's head.",
    "A sight-seeing bus is threading its way through crowded city traffic; its occupants eagerly view the sights.",
    "What has been a handsome and valuable bottle lies broken and forgotten; a track of living perfume leads from it.",
    "At a clearing of pioneer days in the forest all the neighbors have gathered to assist in a happy house-raising.",
    "In an old-fashioned \"candle lighting service\" a youth gains for the first time a sense of the great \"other world.\"",
    "A massive rocky shore presents its unchanging face of the centuries to the furies and coaxing calms of the sea.",
    "Sutter's river empire of early California is seen; then all is swept away in the spectacular gold rush of 1849.",
    "A queer craft, equipped with special machinery, is the base of operations for courageous divers of the deep sea.",
    "A beautiful gem of a lake, set high in the mountains, is revealed in the silvery bathing light of a full moon.",
    "A dentist is hard at work; man-made porcelain replaces nature's enamel which consciousness has been unable to hold.",
    "A fellowship supper is served to a group of men brought together in reunion, to live again in forgotten moments.",
    "There is great excitement upon the narrow and treacherous beach; finally a drowning man is saved, brought ashore.",
    "A brilliant assembly of dignitaries is seen on a highly polished dance floor; it is an important embassy ball.",
    "In a rattle-trap old wooden barn an earnest man works in a maze of apparatus; invention at the point of success.",
    "Through a seemingly inaccessible mountainous country the telephone linemen carry their thin lines of communication.",
    "In unconscious occult symbolism a group of laughing, joyous children are playing upon five mounds of sand.",
    "A girl's face is revealed, of fine, delicate, aristocratic features; suddenly these break into a glorious smile.",
    "A woman is \"great with child\"; the remarkable thing is that she was impregnated by her own Spirit, her aspiration.",
    "A winding quiet road, carpeted by the falling leaves, leads through an old-fashioned woods rich in autumn color.",
    "A wise old parrot has been listening attentively to the conversation, and preening himself; now he begins to talk.",
    "An immensely tall entranceway is closed by heavy and dark velvet portieres; a woman in white draws these aside.",
    "A soldier runs the risk of court-martial in remaining \"absent without leave\", but a lovely miss clings to him.",
    "A group of hunters, protected by heavy clothing, are making their way out into the marsh to shoot wild ducks.",
    "A little white rabbit rests contentedly in his cage; before the eyes he metamorphoses into an elf in a fairy glade.",
    "A steady stream of people down a mountain side gives testimony to the power of the man who has there addressed them.",
    "An x-ray machine is in operation; by means of it a bit of fine diagnosis is made possible, and a life is preserved.",
    "A group of American Indians are making camp; as if by magic the teepees are erected, and home comfort established.",
    "Scintillating with the flash of the instruments and the colors of banners and uniforms, a military band is marching.",
    "A pageant of fairyland is made visible to mortal eyes; the king of the little people is welcomed to his domain.",
    "Flanked by the splendor of an Incan monarch's court a mother of captured princelets pleads archly for their lives.",
    "The town jester is in his element; it is Halloween and there is now justification for any and all his pranks.",
    "A group of elderly men in uniform, eyes bright with reminiscence, are gathered at a Grand Army of the Republic campfire.",
    "A quick wind is making sport with the sea; through sharp mist as far as sight reaches are scurrying whitecaps.",
    "Two men, lounging in the comfort of some old drawing room, smoking strong pipes, are playing a game of chess.",
    "A little child is learning to walk; near are the happy parents, wise enough to refuse unnecessary assistance.",
    "An owl is gravely perched high and deep in the shade of an old landmark of a tree, solitary on a point of land.",
    "There is a great display of colorful coming and going in a large concourse of people; it is a cricket game.",
    "A little fellow, sly and smiling, knocks at the door of the human heart; it is none other than cupid himself.",
    "In the caldron of the universe the rocks and world stuff are in the process of formation; the metals glint within.",
    "A mother is leading her children up a broad flight of steps, they enjoy the task of lifting little feet.",
    "In a pageant of progress a glorious little maid with golden hair enacts the part of a goddess of opportunity.",
    "An ugly old human figure is the carved representation of a god; near the left side is an ever-burning lamp.",
    "In a curious allegorical transformation a flag becomes an eagle, and the eagle becomes chanticleer triumphant.",
    "A wistful young woman, dressed in black, is surprised into a warm companionship to which she has felt alien.",
    "A vast panorama of sand and time is unfolding; the pyramids and sphinx in their glory rise before the eye.",
    "The time is at hand to determine whether winter shall end; the ground hog comes forth looking for its shadow.",
    "A peaceful scene is unfolded to view; a calm ocean, a single motionless ship, a few lazy soaring seagulls.",
    "An Easter sunrise service is about to begin at the suggestion of dawn; darkness surrenders the worshipers.",
    "Little children are playing upon the sultry beach; but each is protected from the glare by a tiny sunbonnet.",
    "The pelicans have been distressed by the intrusion of man; they are moving their habitat to places unknown.",
    "The pond has been deeply frozen for weeks; now the men and machinery are at work, cutting out the summer's ice.",
    "A child and a dog are having all the fun in the world, gravely attending to things in borrowed eyeglasses.",
    "A perfect bit of the old world is found in the new: A Chinese laundry has its shutters up and is now itself.",
    "Bathed in the slantwise western sun, with the statue of liberty beyond, Ellis Island welcomes the immigrants.",
    "The bluebird, as a sign of good luck and happiness, alights at the door of a little cottage on the highway.",
    "A chubby little rich boy rides upon a hobby horse of bright colors and wishes for hazards he may never know.",
    "The scene is an old-fashioned battle; in the hot hand-to-hand fighting a flag bearer distinguishes himself.",
    "A sculptor is at work in his studio, and under his skilled hands a lovely form slowly and surely takes shape.",
    "A splendidly built bridge, a heritage of unknown ages, still spans the beautiful and wildly primitive stream.",
    "A perspiring fat-boy is mowing the grass; he has discovered the handicap of flesh and is determined to lose it.",
    "A picture of regal pomp and glory reveals itself; it is sacerdotal, the Pope is holding audience in his palace.",
    "An Indian chief is standing before the assembled pow-wow of tribes; coldly, regally, he demands recognition.",
    "Three stained glass windows in an old cathedral are seen; the center one has been damaged by the bombardment.",
    "The human soul is visualized as a hovering spirit, eager and receptive to the lessons to be learned from life.",
    "A group of merry-makers are embarking in a large canoe on the magic little lantern-lit lake at the resort.",
    "An American Indian encampment rests by the side of a canoe-filled stream; on the shore a war dance commences.",
    "A dark archway in the forest leads to greater depths and darkness beyond; in its shade lie an even ten logs.",
    "A highly sophisticated ritual of magic is displayed, the central figure is a heavily veiled prophet of power.",
    "A huge living room in an old fashioned frame mansion is flooded with sunlight; the canaries are singing happily.",
    "There is a vast stretch of heavenly realm; across this comes, leisurely but surely, an angel carrying a harp.",
    "Upon the deck of an old fashioned sailing ship seamen are taming an albatross, who feeds from their hands.",
    "In a quiet and landscaped portion of a vast private estate a group of pheasants display their brilliant colors.",
    "A student of nature is lecturing; before each listener dancing pictures of distant wonders are conjured up.",
    "Back against the mountains towards the East, which fringe the roof of the world, a fire-worshiper is meditating.",
    "A vast pile of Mayan ruins in tropical America discloses a perfectly preserved bas-relief carved in the granite.",
    "It is the children's ward in the hospital; there is an abundance of toys, books and gifts for the youngsters.",
    "The high school grounds are alive with fresh new vitality, the boys and girls are seen in their gymnasium suits.",
    "A young woman, mature but long repressed, is surreptitiously bathing in the nude, finding a new release in spirit.",
    "From the proud new warship of Britannia, a token of her maritime power, flies the Union Jack in calm dignity.",
    "A little miss of about five has gone to the market with a huge shopping bag, quite as adult as anybody.",
    "There is no service in the church, but rising full and clear come the voices of the hidden choir in rehearsal.",
    "Excitement thrills the grandstands; it is the relay race and each runner springs into place with eagerness.",
    "The defeated general yields up his sword, but in failure he wins for his cause a dignity that is real success.",
    "The army is erect in a long faultless line, the resplendent officers confer upon a private two awards for bravery.",
    "The convent lies between great gnarled old trees, a very picture of peace; a woman approaches this sure haven.",
    "The little boys are welcomed to the store of the genial oriental rug dealer; here is rare fun in piled softness.",
    "In a little glade never trod by the foot of man, upon the mist of a waterfall, dances a care-free water-sprite.",
    "A party of anchorites are making a mountain pilgrimage; in view lie both the busy world and the quiet way ahead.",
    "A large aviary, built as a wing to a rural mansion, reveals a host of singing and contended feathered citizens.",
    "Afternoon tea is served in a gypsy parlor patronized by social butterflies; a young lady reads tea leaves.",
    "In the mahogany-paneled and magnificently furnished directors' room a secret business conference has begun.",
    "An old adobe mission rests in the shelter of the California hills, it seems as ancient as the mountains behind it.",
    "An unexpected thunderstorm breaks over the parched lands of the river empire, its terror is welcome relief.",
    "A deserter from the navy stands suddenly aware of a dawning truth: Freedom is never the result of compromise.",
    "A Hindu pundit, emerging from the sleepy and idle warmth of his hut, suddenly glows with a mystic healing power.",
    "In the land of shades a grave council of the ancestors of a man of world importance has been called to guide him.",
    "The stage is dimly lit for an allegorical representation, a solitary performer carries the thread of mystery.",
    "A fantasy is being presented by the children in an exclusive school.A huge egg cracks to reveal a cherubic miss.",
    "The fall-fashion display has opened in the leading stores; their windows reveal beautifully gowned wax figures.",
    "A student sits in quiet meditation; before his eyes a flag seems to form, then it slowly changes into an eagle.",
    "A man of real stature has been catapulted into ephemeral popularity; unspoiled, he plans further achievements.",
    "An artist has withdrawn from friends, and all accustomed haunts, to be alone with a new inspiration, just forming.",
    "A magnificent allegorical painting presents life as a broad stairway; the landings are various grades of life.",
    "Under the shade of the porch of an old-fashioned hotel, in a happy little village, hangs a sedate barometer.",
    "A long and heavy train climbs the steep mountain grade, at last a tunnel offers a shortcut to the other side.",
    "Two little love birds are sitting on a fence, singing to each other and advertising their happiness to the world.",
    "The active executive of a large corporation sits at his desk, immersed in the details of some business project.",
    "The master is sleeping in the little hut near the newly discovered gold mine, his faithful dog on guard.",
    "The masquerade has been long in progress, the laughing young ladies have at last forced the final male to unmask.",
    "On every hand are the still smoking embers, but the forest fire is out and the weary fighters are most jubilant.",
    "A large white dove circles about and about overhead, and then descends and proves to be a carrier with a message.",
    "A well-groomed, striking, conspicuously solitary guest leaves the room, a woman disappointed and disillusioned.",
    "A new carpet, deep and velvet-like, has been placed in the airy nursery, and the happy children revel upon it.",
    "A big trained bear is sitting upon a chair especially built for him, waving all four paws in grotesque fashion.",
    "A man, obviously of the world, has turned his back upon passion and is giving to people a deep undying wisdom.",
    "A butterfly is struggling to emerge from his chrysalis, it seems that the right wing is more perfectly formed.",
    "The battery man at the automobile service station has his hydrometer in hand, about to inspect a customer's car.",
    "In the quiet of afternoon, in the cool of an art connoisseur's library, an old pottery bowl holds fresh violets.",
    "The pioneer cottage is prepared for winter's rigors; a tree has been felled and sawed up for fuel, all is orderly.",
    "The beautifully winged insect has just come forth into glorious adult being upon completion of its metamorphosis.",
    "A mystic moon-lit field, near the site of a mystic and traditional Babylon, has sprung into delicate white bloom.",
    "The public market is thronged with people, and all are good-natured, hurried; it is late upon a Saturday afternoon.",
    "Almost as if possessed with man's intelligence, a tiny squirrel remains watchful on a limb, hidden from the hunters.",
    "A dull expanse of rocky formations turns out to be a petrified forest, an eternal record of a life lived long ago.",
    "The narrow isthmus between two summer resorts, both sparkling with life, safely carries the crowded holiday traffic.",
    "Through the spacious grounds of the church are strung Japanese lanterns; it is a bazaar of merry hearts and faces.",
    "All the traditional dignity of West Point is seen in the parade of officers-in-the-making under the setting sun.",
    "Over the strewn and irregular masses of stone at the shore is low-lying fog, but on one clear rock a cross rests.",
    "A trim and splendid young miss, at the camp of a semi-military organization for girls, blows her bugle triumphantly.",
    "A tiny jockey, from atop his magnificent horse, looks about him eagerly; the race starts, he becomes a god of speed.",
    "As a tiny fleck of dust in the sky, the aviator sails across the horizon, absolute master of these higher realms.",
    "A group of serious-eyed, earnest-faced men are seeking illumination; they are conducted into a massive sanctuary.",
    "A convocation of the Lodge of Initiates has brought the earth's glorious souls, in spirit, to examine candidates.",
    "In a still corner of the museum are the weapons of long ago, and in a glass case by itself a single venerable sword.",
    "A young lady from top of her coiffure to tip of her toes is regal, displays softer beauty of face above fox furs.",
    "An officer in unkept campaign uniform is preparing to drill his men, themselves in appearance quite worn for wear.",
    "In the sacred quiet, and the afternoon half-lights of the museum, a young art student drinks in pure inspiration.",
    "In the sunshine of the boulevard the promenade of wealth's Easter is seen, in poorer quarters is equally brave show.",
    "The celebrated revivalist has erected his huge tent, which is now warmed by music, lights and the smell of sawdust.",
    "The two, young man and old, have walked weary miles, but it is master and pupil, and therefore neither is fatigued.",
    "The window in the room of the farmhouse yields its view of soft purple fields; and table is set for a quiet supper.",
    "The child, strange to ranch life, has taken a violent fancy to a little white lamb; a wise Chinese servant smiles.",
    "Down the man-made mountain of industry, in allegorical representation, comes the prophet with tablets of new law.",
    "A huge hulk of a woman rests immobile; she is a spiritist medium, around her are entities forming and dissolving.",
    "The tiny island seems lost in the broad ocean, but its happy inhabitants have created a great world all their own.",
    "Ecclesiastical reform of a drastic nature is in progress, a priestcraft purged and purified opens a new ministry.",
    "The new moon just visible at sundown; to the lovers it is romantic only, to the philosopher it speaks of eternity.",
    "The harvest moon rises superbly in the east, and the light of day is shamed by the colors of an autumnal evening.",
    "Night has seemed light as day, and in the odd shadows of diffused whiteness the fertile fields appear quite alive.",
    "The scientist carefully adjusts the tiny prism, and by means of the divided rays of light makes his clever analysis.",
    "Nathaniel Hawthorne's conception of the Great Stone Face has been brought to fruition in a huge mountain carving."
};

#endif /* INTERPRET */

/* data2.c */
