/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: GraphSettingsData.h
	Last generated: Tue Nov 16 15:58:08 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef GraphSettingsData_included
#define GraphSettingsData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include "myLineEdit.h"
#include <qcombo.h>
#include "tr.h"

class GraphSettingsData : public QDialog
{
    Q_OBJECT

public:

    GraphSettingsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~GraphSettingsData();

public slots:


protected slots:

    virtual void vchartsizeslot();
    virtual void mapdegrotslot();
    virtual void globetiltslot();
    virtual void okslot();
    virtual void planetslot(int);
    virtual void hchartsizeslot();
    virtual void animdelslot();
    virtual void cancelslot();
    virtual void wheelchartslot(int);

protected:
    QButtonGroup* WheelChart;
    myLineEdit* HChartSize;
    myLineEdit* VChartSize;
    myLineEdit* MapDegRot;
    myLineEdit* GlobeTilt;
    QCheckBox* WorldMollewide;
    myLineEdit* AnimDel;
    QCheckBox* UpdateScreen;
    QComboBox* Planet;

};

#endif // GraphSettingsData_included
