/**********************************************************************

	--- Qt Architect generated file ---

	File: ObscureSettingsData.h
	Last generated: Thu Apr 27 15:06:08 2000

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef ObscureSettingsData_included
#define ObscureSettingsData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include "myLineEdit.h"
#include "tr.h"

class ObscureSettingsData : public QDialog
{
    Q_OBJECT

public:

    ObscureSettingsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~ObscureSettingsData();

public slots:


protected slots:

    virtual void plutslot(int);
    virtual void lilislot(int);
    virtual void okslot();
    virtual void caprslot(int);
    virtual void orientslot(int);
    virtual void uraslot(int);
    virtual void restslot(int);
    virtual void cancelslot();
    virtual void nbcellsslot();

protected:
    QButtonGroup* RisSetRestr;
    QButtonGroup* LiliGlyph;
    QButtonGroup* PlutGlyph;
    QButtonGroup* UraGlyph;
    QButtonGroup* CaprGlyph;
    QButtonGroup* PostOrient;
    QCheckBox* TrueNode;
    QCheckBox* D24H;
    QCheckBox* AmPm;
    QCheckBox* InsigCuspAsp;
    QCheckBox* RightMost;
    QCheckBox* OldStyle;
    QCheckBox* CuspPosi;
    QCheckBox* SignChange;
    QCheckBox* DirectChange;
    myLineEdit* NbCells;
    QCheckBox* RealFonts;
    QCheckBox* Rising;
    QCheckBox* Setting;
    QCheckBox* Zenith;
    QCheckBox* Nadir;
    QCheckBox* ZoneLess;

};

#endif // ObscureSettingsData_included
