/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: RestrictionsData.h
	Last generated: Sun Oct 24 13:59:31 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef RestrictionsData_included
#define RestrictionsData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include <qchkbox.h>
#include "tr.h"
extern "C"
{
#ifndef ASTROLOG
#include "astrolog.h"
#endif
}

class RestrictionsData : public QDialog
{
    Q_OBJECT

public:

    RestrictionsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~RestrictionsData();

public slots:


protected slots:

    virtual void toglecuspslot();
    virtual void housesslot(int);
    virtual void rplanslot(int);
    virtual void okslot();
    virtual void uranianslot(int);
    virtual void toggleminorslot();
    virtual void copyslot();
    virtual void rminobjslot(int);
    virtual void toggleuranslot();
    virtual void restrictallslot();
    virtual void cancelslot();
    virtual void unrestrictallslot();

protected:
    QCheckBox* r[uranHi];
    QButtonGroup* rPlan;
    QButtonGroup* rMinObj;
    QButtonGroup* rHouses;
    QButtonGroup* rUranians;

};

#endif // RestrictionsData_included


