/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: RestrictionsData.cpp
	Last generated: Sun Oct 24 13:59:31 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "RestrictionsData.h"

#define Inherited QDialog

#include <qpushbt.h>

RestrictionsData::RestrictionsData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	rPlan = new QButtonGroup( this, "ButtonGroup_1" );
	rPlan->setGeometry( 10, 10, 140, 230 );
	rPlan->setMinimumSize( 0, 0 );
	rPlan->setMaximumSize( 32767, 32767 );
	connect( rPlan, SIGNAL(clicked(int)), SLOT(rplanslot(int)) );
	rPlan->setFocusPolicy( QWidget::NoFocus );
	rPlan->setBackgroundMode( QWidget::PaletteBackground );
	rPlan->setFontPropagation( QWidget::NoChildren );
	rPlan->setPalettePropagation( QWidget::NoChildren );
	rPlan->setFrameStyle( 49 );
	rPlan->setTitle( transl("Planets") );
	rPlan->setAlignment( 1 );

	r[0] = new QCheckBox( this, "CheckBox_1" );
	r[0]->setGeometry( 20, 30, 120, 20 );
	r[0]->setMinimumSize( 0, 0 );
	r[0]->setMaximumSize( 32767, 32767 );
	r[0]->setFocusPolicy( QWidget::TabFocus );
	r[0]->setBackgroundMode( QWidget::PaletteBackground );
	r[0]->setFontPropagation( QWidget::NoChildren );
	r[0]->setPalettePropagation( QWidget::NoChildren );
	r[0]->setText( "" );
	r[0]->setAutoRepeat( FALSE );
	r[0]->setAutoResize( FALSE );

	r[1] = new QCheckBox( this, "CheckBox_2" );
	r[1]->setGeometry( 20, 50, 120, 20 );
	r[1]->setMinimumSize( 0, 0 );
	r[1]->setMaximumSize( 32767, 32767 );
	r[1]->setFocusPolicy( QWidget::TabFocus );
	r[1]->setBackgroundMode( QWidget::PaletteBackground );
	r[1]->setFontPropagation( QWidget::NoChildren );
	r[1]->setPalettePropagation( QWidget::NoChildren );
	r[1]->setText( "" );
	r[1]->setAutoRepeat( FALSE );
	r[1]->setAutoResize( FALSE );

	r[2] = new QCheckBox( this, "CheckBox_3" );
	r[2]->setGeometry( 20, 70, 120, 20 );
	r[2]->setMinimumSize( 0, 0 );
	r[2]->setMaximumSize( 32767, 32767 );
	r[2]->setFocusPolicy( QWidget::TabFocus );
	r[2]->setBackgroundMode( QWidget::PaletteBackground );
	r[2]->setFontPropagation( QWidget::NoChildren );
	r[2]->setPalettePropagation( QWidget::NoChildren );
	r[2]->setText( "" );
	r[2]->setAutoRepeat( FALSE );
	r[2]->setAutoResize( FALSE );

	r[3] = new QCheckBox( this, "CheckBox_4" );
	r[3]->setGeometry( 20, 90, 120, 20 );
	r[3]->setMinimumSize( 0, 0 );
	r[3]->setMaximumSize( 32767, 32767 );
	r[3]->setFocusPolicy( QWidget::TabFocus );
	r[3]->setBackgroundMode( QWidget::PaletteBackground );
	r[3]->setFontPropagation( QWidget::NoChildren );
	r[3]->setPalettePropagation( QWidget::NoChildren );
	r[3]->setText( "" );
	r[3]->setAutoRepeat( FALSE );
	r[3]->setAutoResize( FALSE );

	r[4] = new QCheckBox( this, "CheckBox_5" );
	r[4]->setGeometry( 20, 110, 120, 20 );
	r[4]->setMinimumSize( 0, 0 );
	r[4]->setMaximumSize( 32767, 32767 );
	r[4]->setFocusPolicy( QWidget::TabFocus );
	r[4]->setBackgroundMode( QWidget::PaletteBackground );
	r[4]->setFontPropagation( QWidget::NoChildren );
	r[4]->setPalettePropagation( QWidget::NoChildren );
	r[4]->setText( "" );
	r[4]->setAutoRepeat( FALSE );
	r[4]->setAutoResize( FALSE );

	r[5] = new QCheckBox( this, "CheckBox_6" );
	r[5]->setGeometry( 20, 130, 120, 20 );
	r[5]->setMinimumSize( 0, 0 );
	r[5]->setMaximumSize( 32767, 32767 );
	r[5]->setFocusPolicy( QWidget::TabFocus );
	r[5]->setBackgroundMode( QWidget::PaletteBackground );
	r[5]->setFontPropagation( QWidget::NoChildren );
	r[5]->setPalettePropagation( QWidget::NoChildren );
	r[5]->setText( "" );
	r[5]->setAutoRepeat( FALSE );
	r[5]->setAutoResize( FALSE );

	r[6] = new QCheckBox( this, "CheckBox_7" );
	r[6]->setGeometry( 20, 150, 120, 20 );
	r[6]->setMinimumSize( 0, 0 );
	r[6]->setMaximumSize( 32767, 32767 );
	r[6]->setFocusPolicy( QWidget::TabFocus );
	r[6]->setBackgroundMode( QWidget::PaletteBackground );
	r[6]->setFontPropagation( QWidget::NoChildren );
	r[6]->setPalettePropagation( QWidget::NoChildren );
	r[6]->setText( "" );
	r[6]->setAutoRepeat( FALSE );
	r[6]->setAutoResize( FALSE );

	r[7] = new QCheckBox( this, "CheckBox_8" );
	r[7]->setGeometry( 20, 170, 120, 20 );
	r[7]->setMinimumSize( 0, 0 );
	r[7]->setMaximumSize( 32767, 32767 );
	r[7]->setFocusPolicy( QWidget::TabFocus );
	r[7]->setBackgroundMode( QWidget::PaletteBackground );
	r[7]->setFontPropagation( QWidget::NoChildren );
	r[7]->setPalettePropagation( QWidget::NoChildren );
	r[7]->setText( "" );
	r[7]->setAutoRepeat( FALSE );
	r[7]->setAutoResize( FALSE );

	r[8] = new QCheckBox( this, "CheckBox_9" );
	r[8]->setGeometry( 20, 190, 120, 20 );
	r[8]->setMinimumSize( 0, 0 );
	r[8]->setMaximumSize( 32767, 32767 );
	r[8]->setFocusPolicy( QWidget::TabFocus );
	r[8]->setBackgroundMode( QWidget::PaletteBackground );
	r[8]->setFontPropagation( QWidget::NoChildren );
	r[8]->setPalettePropagation( QWidget::NoChildren );
	r[8]->setText( "" );
	r[8]->setAutoRepeat( FALSE );
	r[8]->setAutoResize( FALSE );

	r[9] = new QCheckBox( this, "CheckBox_10" );
	r[9]->setGeometry( 20, 210, 120, 20 );
	r[9]->setMinimumSize( 0, 0 );
	r[9]->setMaximumSize( 32767, 32767 );
	r[9]->setFocusPolicy( QWidget::TabFocus );
	r[9]->setBackgroundMode( QWidget::PaletteBackground );
	r[9]->setFontPropagation( QWidget::NoChildren );
	r[9]->setPalettePropagation( QWidget::NoChildren );
	r[9]->setText( "" );
	r[9]->setAutoRepeat( FALSE );
	r[9]->setAutoResize( FALSE );

	rMinObj = new QButtonGroup( this, "ButtonGroup_2" );
	rMinObj->setGeometry( 160, 10, 140, 230 );
	rMinObj->setMinimumSize( 0, 0 );
	rMinObj->setMaximumSize( 32767, 32767 );
	connect( rMinObj, SIGNAL(clicked(int)), SLOT(rminobjslot(int)) );
	rMinObj->setFocusPolicy( QWidget::NoFocus );
	rMinObj->setBackgroundMode( QWidget::PaletteBackground );
	rMinObj->setFontPropagation( QWidget::NoChildren );
	rMinObj->setPalettePropagation( QWidget::NoChildren );
	rMinObj->setFrameStyle( 49 );
	rMinObj->setTitle( transl("Minor Objects") );
	rMinObj->setAlignment( 1 );

	r[10] = new QCheckBox( this, "CheckBox_11" );
	r[10]->setGeometry( 170, 30, 120, 20 );
	r[10]->setMinimumSize( 0, 0 );
	r[10]->setMaximumSize( 32767, 32767 );
	r[10]->setFocusPolicy( QWidget::TabFocus );
	r[10]->setBackgroundMode( QWidget::PaletteBackground );
	r[10]->setFontPropagation( QWidget::NoChildren );
	r[10]->setPalettePropagation( QWidget::NoChildren );
	r[10]->setText( "" );
	r[10]->setAutoRepeat( FALSE );
	r[10]->setAutoResize( FALSE );

	r[11] = new QCheckBox( this, "CheckBox_12" );
	r[11]->setGeometry( 170, 50, 120, 20 );
	r[11]->setMinimumSize( 0, 0 );
	r[11]->setMaximumSize( 32767, 32767 );
	r[11]->setFocusPolicy( QWidget::TabFocus );
	r[11]->setBackgroundMode( QWidget::PaletteBackground );
	r[11]->setFontPropagation( QWidget::NoChildren );
	r[11]->setPalettePropagation( QWidget::NoChildren );
	r[11]->setText( "" );
	r[11]->setAutoRepeat( FALSE );
	r[11]->setAutoResize( FALSE );

	r[12] = new QCheckBox( this, "CheckBox_13" );
	r[12]->setGeometry( 170, 70, 120, 20 );
	r[12]->setMinimumSize( 0, 0 );
	r[12]->setMaximumSize( 32767, 32767 );
	r[12]->setFocusPolicy( QWidget::TabFocus );
	r[12]->setBackgroundMode( QWidget::PaletteBackground );
	r[12]->setFontPropagation( QWidget::NoChildren );
	r[12]->setPalettePropagation( QWidget::NoChildren );
	r[12]->setText( "" );
	r[12]->setAutoRepeat( FALSE );
	r[12]->setAutoResize( FALSE );

	r[13] = new QCheckBox( this, "CheckBox_14" );
	r[13]->setGeometry( 170, 90, 120, 20 );
	r[13]->setMinimumSize( 0, 0 );
	r[13]->setMaximumSize( 32767, 32767 );
	r[13]->setFocusPolicy( QWidget::TabFocus );
	r[13]->setBackgroundMode( QWidget::PaletteBackground );
	r[13]->setFontPropagation( QWidget::NoChildren );
	r[13]->setPalettePropagation( QWidget::NoChildren );
	r[13]->setText( "" );
	r[13]->setAutoRepeat( FALSE );
	r[13]->setAutoResize( FALSE );

	r[14] = new QCheckBox( this, "CheckBox_15" );
	r[14]->setGeometry( 170, 110, 120, 20 );
	r[14]->setMinimumSize( 0, 0 );
	r[14]->setMaximumSize( 32767, 32767 );
	r[14]->setFocusPolicy( QWidget::TabFocus );
	r[14]->setBackgroundMode( QWidget::PaletteBackground );
	r[14]->setFontPropagation( QWidget::NoChildren );
	r[14]->setPalettePropagation( QWidget::NoChildren );
	r[14]->setText( "" );
	r[14]->setAutoRepeat( FALSE );
	r[14]->setAutoResize( FALSE );

	r[15] = new QCheckBox( this, "CheckBox_16" );
	r[15]->setGeometry( 170, 130, 120, 20 );
	r[15]->setMinimumSize( 0, 0 );
	r[15]->setMaximumSize( 32767, 32767 );
	r[15]->setFocusPolicy( QWidget::TabFocus );
	r[15]->setBackgroundMode( QWidget::PaletteBackground );
	r[15]->setFontPropagation( QWidget::NoChildren );
	r[15]->setPalettePropagation( QWidget::NoChildren );
	r[15]->setText( "" );
	r[15]->setAutoRepeat( FALSE );
	r[15]->setAutoResize( FALSE );

	r[16] = new QCheckBox( this, "CheckBox_17" );
	r[16]->setGeometry( 170, 150, 120, 20 );
	r[16]->setMinimumSize( 0, 0 );
	r[16]->setMaximumSize( 32767, 32767 );
	r[16]->setFocusPolicy( QWidget::TabFocus );
	r[16]->setBackgroundMode( QWidget::PaletteBackground );
	r[16]->setFontPropagation( QWidget::NoChildren );
	r[16]->setPalettePropagation( QWidget::NoChildren );
	r[16]->setText( "" );
	r[16]->setAutoRepeat( FALSE );
	r[16]->setAutoResize( FALSE );

	r[17] = new QCheckBox( this, "CheckBox_18" );
	r[17]->setGeometry( 170, 170, 120, 20 );
	r[17]->setMinimumSize( 0, 0 );
	r[17]->setMaximumSize( 32767, 32767 );
	r[17]->setFocusPolicy( QWidget::TabFocus );
	r[17]->setBackgroundMode( QWidget::PaletteBackground );
	r[17]->setFontPropagation( QWidget::NoChildren );
	r[17]->setPalettePropagation( QWidget::NoChildren );
	r[17]->setText( "" );
	r[17]->setAutoRepeat( FALSE );
	r[17]->setAutoResize( FALSE );

	r[18] = new QCheckBox( this, "CheckBox_19" );
	r[18]->setGeometry( 170, 190, 120, 20 );
	r[18]->setMinimumSize( 0, 0 );
	r[18]->setMaximumSize( 32767, 32767 );
	r[18]->setFocusPolicy( QWidget::TabFocus );
	r[18]->setBackgroundMode( QWidget::PaletteBackground );
	r[18]->setFontPropagation( QWidget::NoChildren );
	r[18]->setPalettePropagation( QWidget::NoChildren );
	r[18]->setText( "" );
	r[18]->setAutoRepeat( FALSE );
	r[18]->setAutoResize( FALSE );

	rHouses = new QButtonGroup( this, "ButtonGroup_3" );
	rHouses->setGeometry( 310, 10, 140, 270 );
	rHouses->setMinimumSize( 0, 0 );
	rHouses->setMaximumSize( 32767, 32767 );
	connect( rHouses, SIGNAL(clicked(int)), SLOT(housesslot(int)) );
	rHouses->setFocusPolicy( QWidget::NoFocus );
	rHouses->setBackgroundMode( QWidget::PaletteBackground );
	rHouses->setFontPropagation( QWidget::NoChildren );
	rHouses->setPalettePropagation( QWidget::NoChildren );
	rHouses->setFrameStyle( 49 );
	rHouses->setTitle( transl("Houses") );
	rHouses->setAlignment( 1 );

	r[19] = new QCheckBox( this, "CheckBox_21" );
	r[19]->setGeometry( 170, 210, 120, 20 );
	r[19]->setMinimumSize( 0, 0 );
	r[19]->setMaximumSize( 32767, 32767 );
	r[19]->setFocusPolicy( QWidget::TabFocus );
	r[19]->setBackgroundMode( QWidget::PaletteBackground );
	r[19]->setFontPropagation( QWidget::NoChildren );
	r[19]->setPalettePropagation( QWidget::NoChildren );
	r[19]->setText( "" );
	r[19]->setAutoRepeat( FALSE );
	r[19]->setAutoResize( FALSE );

	r[20] = new QCheckBox( this, "CheckBox_22" );
	r[20]->setGeometry( 320, 30, 120, 20 );
	r[20]->setMinimumSize( 0, 0 );
	r[20]->setMaximumSize( 32767, 32767 );
	r[20]->setFocusPolicy( QWidget::TabFocus );
	r[20]->setBackgroundMode( QWidget::PaletteBackground );
	r[20]->setFontPropagation( QWidget::NoChildren );
	r[20]->setPalettePropagation( QWidget::NoChildren );
	r[20]->setText( "" );
	r[20]->setAutoRepeat( FALSE );
	r[20]->setAutoResize( FALSE );

	r[21] = new QCheckBox( this, "CheckBox_23" );
	r[21]->setGeometry( 320, 50, 120, 20 );
	r[21]->setMinimumSize( 0, 0 );
	r[21]->setMaximumSize( 32767, 32767 );
	r[21]->setFocusPolicy( QWidget::TabFocus );
	r[21]->setBackgroundMode( QWidget::PaletteBackground );
	r[21]->setFontPropagation( QWidget::NoChildren );
	r[21]->setPalettePropagation( QWidget::NoChildren );
	r[21]->setText( "" );
	r[21]->setAutoRepeat( FALSE );
	r[21]->setAutoResize( FALSE );

	r[22] = new QCheckBox( this, "CheckBox_24" );
	r[22]->setGeometry( 320, 70, 120, 20 );
	r[22]->setMinimumSize( 0, 0 );
	r[22]->setMaximumSize( 32767, 32767 );
	r[22]->setFocusPolicy( QWidget::TabFocus );
	r[22]->setBackgroundMode( QWidget::PaletteBackground );
	r[22]->setFontPropagation( QWidget::NoChildren );
	r[22]->setPalettePropagation( QWidget::NoChildren );
	r[22]->setText( "" );
	r[22]->setAutoRepeat( FALSE );
	r[22]->setAutoResize( FALSE );

	r[23] = new QCheckBox( this, "CheckBox_25" );
	r[23]->setGeometry( 320, 90, 120, 20 );
	r[23]->setMinimumSize( 0, 0 );
	r[23]->setMaximumSize( 32767, 32767 );
	r[23]->setFocusPolicy( QWidget::TabFocus );
	r[23]->setBackgroundMode( QWidget::PaletteBackground );
	r[23]->setFontPropagation( QWidget::NoChildren );
	r[23]->setPalettePropagation( QWidget::NoChildren );
	r[23]->setText( "" );
	r[23]->setAutoRepeat( FALSE );
	r[23]->setAutoResize( FALSE );

	r[24] = new QCheckBox( this, "CheckBox_26" );
	r[24]->setGeometry( 320, 110, 120, 20 );
	r[24]->setMinimumSize( 0, 0 );
	r[24]->setMaximumSize( 32767, 32767 );
	r[24]->setFocusPolicy( QWidget::TabFocus );
	r[24]->setBackgroundMode( QWidget::PaletteBackground );
	r[24]->setFontPropagation( QWidget::NoChildren );
	r[24]->setPalettePropagation( QWidget::NoChildren );
	r[24]->setText( "" );
	r[24]->setAutoRepeat( FALSE );
	r[24]->setAutoResize( FALSE );

	r[25] = new QCheckBox( this, "CheckBox_27" );
	r[25]->setGeometry( 320, 130, 120, 20 );
	r[25]->setMinimumSize( 0, 0 );
	r[25]->setMaximumSize( 32767, 32767 );
	r[25]->setFocusPolicy( QWidget::TabFocus );
	r[25]->setBackgroundMode( QWidget::PaletteBackground );
	r[25]->setFontPropagation( QWidget::NoChildren );
	r[25]->setPalettePropagation( QWidget::NoChildren );
	r[25]->setText( "" );
	r[25]->setAutoRepeat( FALSE );
	r[25]->setAutoResize( FALSE );

	r[26] = new QCheckBox( this, "CheckBox_28" );
	r[26]->setGeometry( 320, 150, 120, 20 );
	r[26]->setMinimumSize( 0, 0 );
	r[26]->setMaximumSize( 32767, 32767 );
	r[26]->setFocusPolicy( QWidget::TabFocus );
	r[26]->setBackgroundMode( QWidget::PaletteBackground );
	r[26]->setFontPropagation( QWidget::NoChildren );
	r[26]->setPalettePropagation( QWidget::NoChildren );
	r[26]->setText( "" );
	r[26]->setAutoRepeat( FALSE );
	r[26]->setAutoResize( FALSE );

	r[27] = new QCheckBox( this, "CheckBox_29" );
	r[27]->setGeometry( 320, 170, 120, 20 );
	r[27]->setMinimumSize( 0, 0 );
	r[27]->setMaximumSize( 32767, 32767 );
	r[27]->setFocusPolicy( QWidget::TabFocus );
	r[27]->setBackgroundMode( QWidget::PaletteBackground );
	r[27]->setFontPropagation( QWidget::NoChildren );
	r[27]->setPalettePropagation( QWidget::NoChildren );
	r[27]->setText( "" );
	r[27]->setAutoRepeat( FALSE );
	r[27]->setAutoResize( FALSE );

	r[28] = new QCheckBox( this, "CheckBox_30" );
	r[28]->setGeometry( 320, 190, 120, 20 );
	r[28]->setMinimumSize( 0, 0 );
	r[28]->setMaximumSize( 32767, 32767 );
	r[28]->setFocusPolicy( QWidget::TabFocus );
	r[28]->setBackgroundMode( QWidget::PaletteBackground );
	r[28]->setFontPropagation( QWidget::NoChildren );
	r[28]->setPalettePropagation( QWidget::NoChildren );
	r[28]->setText( "" );
	r[28]->setAutoRepeat( FALSE );
	r[28]->setAutoResize( FALSE );

	r[29] = new QCheckBox( this, "CheckBox_31" );
	r[29]->setGeometry( 320, 210, 120, 20 );
	r[29]->setMinimumSize( 0, 0 );
	r[29]->setMaximumSize( 32767, 32767 );
	r[29]->setFocusPolicy( QWidget::TabFocus );
	r[29]->setBackgroundMode( QWidget::PaletteBackground );
	r[29]->setFontPropagation( QWidget::NoChildren );
	r[29]->setPalettePropagation( QWidget::NoChildren );
	r[29]->setText( "" );
	r[29]->setAutoRepeat( FALSE );
	r[29]->setAutoResize( FALSE );

	r[30] = new QCheckBox( this, "CheckBox_32" );
	r[30]->setGeometry( 320, 230, 120, 20 );
	r[30]->setMinimumSize( 0, 0 );
	r[30]->setMaximumSize( 32767, 32767 );
	r[30]->setFocusPolicy( QWidget::TabFocus );
	r[30]->setBackgroundMode( QWidget::PaletteBackground );
	r[30]->setFontPropagation( QWidget::NoChildren );
	r[30]->setPalettePropagation( QWidget::NoChildren );
	r[30]->setText( "" );
	r[30]->setAutoRepeat( FALSE );
	r[30]->setAutoResize( FALSE );

	r[31] = new QCheckBox( this, "CheckBox_33" );
	r[31]->setGeometry( 320, 250, 120, 20 );
	r[31]->setMinimumSize( 0, 0 );
	r[31]->setMaximumSize( 32767, 32767 );
	r[31]->setFocusPolicy( QWidget::TabFocus );
	r[31]->setBackgroundMode( QWidget::PaletteBackground );
	r[31]->setFontPropagation( QWidget::NoChildren );
	r[31]->setPalettePropagation( QWidget::NoChildren );
	r[31]->setText( "" );
	r[31]->setAutoRepeat( FALSE );
	r[31]->setAutoResize( FALSE );

	rUranians = new QButtonGroup( this, "ButtonGroup_4" );
	rUranians->setGeometry( 460, 10, 440, 330 );
	rUranians->setMinimumSize( 0, 0 );
	rUranians->setMaximumSize( 32767, 32767 );
	connect( rUranians, SIGNAL(clicked(int)), SLOT(uranianslot(int)) );
	rUranians->setFocusPolicy( QWidget::NoFocus );
	rUranians->setBackgroundMode( QWidget::PaletteBackground );
	rUranians->setFontPropagation( QWidget::NoChildren );
	rUranians->setPalettePropagation( QWidget::NoChildren );
	rUranians->setFrameStyle( 49 );
	rUranians->setTitle( transl("Asteroids") );
	rUranians->setAlignment( 1 );

	r[32] = new QCheckBox( this, "CheckBox_35" );
	r[32]->setGeometry( 470, 30, 120, 20 );
	r[32]->setMinimumSize( 0, 0 );
	r[32]->setMaximumSize( 32767, 32767 );
	r[32]->setFocusPolicy( QWidget::TabFocus );
	r[32]->setBackgroundMode( QWidget::PaletteBackground );
	r[32]->setFontPropagation( QWidget::NoChildren );
	r[32]->setPalettePropagation( QWidget::NoChildren );
	r[32]->setText( "" );
	r[32]->setAutoRepeat( FALSE );
	r[32]->setAutoResize( FALSE );

	r[33] = new QCheckBox( this, "CheckBox_36" );
	r[33]->setGeometry( 470, 50, 120, 20 );
	r[33]->setMinimumSize( 0, 0 );
	r[33]->setMaximumSize( 32767, 32767 );
	r[33]->setFocusPolicy( QWidget::TabFocus );
	r[33]->setBackgroundMode( QWidget::PaletteBackground );
	r[33]->setFontPropagation( QWidget::NoChildren );
	r[33]->setPalettePropagation( QWidget::NoChildren );
	r[33]->setText( "" );
	r[33]->setAutoRepeat( FALSE );
	r[33]->setAutoResize( FALSE );

	r[34] = new QCheckBox( this, "CheckBox_37" );
	r[34]->setGeometry( 470, 70, 120, 20 );
	r[34]->setMinimumSize( 0, 0 );
	r[34]->setMaximumSize( 32767, 32767 );
	r[34]->setFocusPolicy( QWidget::TabFocus );
	r[34]->setBackgroundMode( QWidget::PaletteBackground );
	r[34]->setFontPropagation( QWidget::NoChildren );
	r[34]->setPalettePropagation( QWidget::NoChildren );
	r[34]->setText( "" );
	r[34]->setAutoRepeat( FALSE );
	r[34]->setAutoResize( FALSE );

	r[35] = new QCheckBox( this, "CheckBox_38" );
	r[35]->setGeometry( 470, 90, 120, 20 );
	r[35]->setMinimumSize( 0, 0 );
	r[35]->setMaximumSize( 32767, 32767 );
	r[35]->setFocusPolicy( QWidget::TabFocus );
	r[35]->setBackgroundMode( QWidget::PaletteBackground );
	r[35]->setFontPropagation( QWidget::NoChildren );
	r[35]->setPalettePropagation( QWidget::NoChildren );
	r[35]->setText( "" );
	r[35]->setAutoRepeat( FALSE );
	r[35]->setAutoResize( FALSE );

	r[36] = new QCheckBox( this, "CheckBox_39" );
	r[36]->setGeometry( 470, 110, 120, 20 );
	r[36]->setMinimumSize( 0, 0 );
	r[36]->setMaximumSize( 32767, 32767 );
	r[36]->setFocusPolicy( QWidget::TabFocus );
	r[36]->setBackgroundMode( QWidget::PaletteBackground );
	r[36]->setFontPropagation( QWidget::NoChildren );
	r[36]->setPalettePropagation( QWidget::NoChildren );
	r[36]->setText( "" );
	r[36]->setAutoRepeat( FALSE );
	r[36]->setAutoResize( FALSE );

	r[37] = new QCheckBox( this, "CheckBox_40" );
	r[37]->setGeometry( 470, 130, 120, 20 );
	r[37]->setMinimumSize( 0, 0 );
	r[37]->setMaximumSize( 32767, 32767 );
	r[37]->setFocusPolicy( QWidget::TabFocus );
	r[37]->setBackgroundMode( QWidget::PaletteBackground );
	r[37]->setFontPropagation( QWidget::NoChildren );
	r[37]->setPalettePropagation( QWidget::NoChildren );
	r[37]->setText( "" );
	r[37]->setAutoRepeat( FALSE );
	r[37]->setAutoResize( FALSE );

	r[38] = new QCheckBox( this, "CheckBox_41" );
	r[38]->setGeometry( 470, 150, 120, 20 );
	r[38]->setMinimumSize( 0, 0 );
	r[38]->setMaximumSize( 32767, 32767 );
	r[38]->setFocusPolicy( QWidget::TabFocus );
	r[38]->setBackgroundMode( QWidget::PaletteBackground );
	r[38]->setFontPropagation( QWidget::NoChildren );
	r[38]->setPalettePropagation( QWidget::NoChildren );
	r[38]->setText( "" );
	r[38]->setAutoRepeat( FALSE );
	r[38]->setAutoResize( FALSE );

	r[39] = new QCheckBox( this, "CheckBox_42" );
	r[39]->setGeometry( 470, 170, 120, 20 );
	r[39]->setMinimumSize( 0, 0 );
	r[39]->setMaximumSize( 32767, 32767 );
	r[39]->setFocusPolicy( QWidget::TabFocus );
	r[39]->setBackgroundMode( QWidget::PaletteBackground );
	r[39]->setFontPropagation( QWidget::NoChildren );
	r[39]->setPalettePropagation( QWidget::NoChildren );
	r[39]->setText( "" );
	r[39]->setAutoRepeat( FALSE );
	r[39]->setAutoResize( FALSE );

	r[40] = new QCheckBox( this, "CheckBox_43" );
	r[40]->setGeometry( 470,190, 120, 20 );
	r[40]->setMinimumSize( 0, 0 );
	r[40]->setMaximumSize( 32767, 32767 );
	r[40]->setFocusPolicy( QWidget::TabFocus );
	r[40]->setBackgroundMode( QWidget::PaletteBackground );
	r[40]->setFontPropagation( QWidget::NoChildren );
	r[40]->setPalettePropagation( QWidget::NoChildren );
	r[40]->setText( "" );
	r[40]->setAutoRepeat( FALSE );
	r[40]->setAutoResize( FALSE );

	r[41] = new QCheckBox( this, "CheckBox_44" );
	r[41]->setGeometry( 470,210, 120, 20 );
	r[41]->setMinimumSize( 0, 0 );
	r[41]->setMaximumSize( 32767, 32767 );
	r[41]->setFocusPolicy( QWidget::TabFocus );
	r[41]->setBackgroundMode( QWidget::PaletteBackground );
	r[41]->setFontPropagation( QWidget::NoChildren );
	r[41]->setPalettePropagation( QWidget::NoChildren );
	r[41]->setText( "" );
	r[41]->setAutoRepeat( FALSE );
	r[41]->setAutoResize( FALSE );

	r[42] = new QCheckBox( this, "CheckBox_45" );
	r[42]->setGeometry( 470,230, 120, 20 );
	r[42]->setMinimumSize( 0, 0 );
	r[42]->setMaximumSize( 32767, 32767 );
	r[42]->setFocusPolicy( QWidget::TabFocus );
	r[42]->setBackgroundMode( QWidget::PaletteBackground );
	r[42]->setFontPropagation( QWidget::NoChildren );
	r[42]->setPalettePropagation( QWidget::NoChildren );
	r[42]->setText( "" );
	r[42]->setAutoRepeat( FALSE );
	r[42]->setAutoResize( FALSE );

	r[43] = new QCheckBox( this, "CheckBox_46" );
	r[43]->setGeometry( 470,250, 120, 20 );
	r[43]->setMinimumSize( 0, 0 );
	r[43]->setMaximumSize( 32767, 32767 );
	r[43]->setFocusPolicy( QWidget::TabFocus );
	r[43]->setBackgroundMode( QWidget::PaletteBackground );
	r[43]->setFontPropagation( QWidget::NoChildren );
	r[43]->setPalettePropagation( QWidget::NoChildren );
	r[43]->setText( "" );
	r[43]->setAutoRepeat( FALSE );
	r[43]->setAutoResize( FALSE );

	r[44] = new QCheckBox( this, "CheckBox_47" );
	r[44]->setGeometry( 470, 270, 120, 20 );
	r[44]->setMinimumSize( 0, 0 );
	r[44]->setMaximumSize( 32767, 32767 );
	r[44]->setFocusPolicy( QWidget::TabFocus );
	r[44]->setBackgroundMode( QWidget::PaletteBackground );
	r[44]->setFontPropagation( QWidget::NoChildren );
	r[44]->setPalettePropagation( QWidget::NoChildren );
	r[44]->setText( "" );
	r[44]->setAutoRepeat( FALSE );
	r[44]->setAutoResize( FALSE );

	r[45] = new QCheckBox( this, "CheckBox_48" );
	r[45]->setGeometry( 470, 290, 120, 20 );
	r[45]->setMinimumSize( 0, 0 );
	r[45]->setMaximumSize( 32767, 32767 );
	r[45]->setFocusPolicy( QWidget::TabFocus );
	r[45]->setBackgroundMode( QWidget::PaletteBackground );
	r[45]->setFontPropagation( QWidget::NoChildren );
	r[45]->setPalettePropagation( QWidget::NoChildren );
	r[45]->setText( "" );
	r[45]->setAutoRepeat( FALSE );
	r[45]->setAutoResize( FALSE );

	r[46] = new QCheckBox( this, "CheckBox_49" );
	r[46]->setGeometry( 470, 310, 120, 20 );
	r[46]->setMinimumSize( 0, 0 );
	r[46]->setMaximumSize( 32767, 32767 );
	r[46]->setFocusPolicy( QWidget::TabFocus );
	r[46]->setBackgroundMode( QWidget::PaletteBackground );
	r[46]->setFontPropagation( QWidget::NoChildren );
	r[46]->setPalettePropagation( QWidget::NoChildren );
	r[46]->setText( "" );
	r[46]->setAutoRepeat( FALSE );
	r[46]->setAutoResize( FALSE );

	r[47] = new QCheckBox( this, "CheckBox_50" );
	r[47]->setGeometry( 620, 30, 120, 20 );
	r[47]->setMinimumSize( 0, 0 );
	r[47]->setMaximumSize( 32767, 32767 );
	r[47]->setFocusPolicy( QWidget::TabFocus );
	r[47]->setBackgroundMode( QWidget::PaletteBackground );
	r[47]->setFontPropagation( QWidget::NoChildren );
	r[47]->setPalettePropagation( QWidget::NoChildren );
	r[47]->setText( "" );
	r[47]->setAutoRepeat( FALSE );
	r[47]->setAutoResize( FALSE );

	r[48] = new QCheckBox( this, "CheckBox_51" );
	r[48]->setGeometry( 620, 50, 120, 20 );
	r[48]->setMinimumSize( 0, 0 );
	r[48]->setMaximumSize( 32767, 32767 );
	r[48]->setFocusPolicy( QWidget::TabFocus );
	r[48]->setBackgroundMode( QWidget::PaletteBackground );
	r[48]->setFontPropagation( QWidget::NoChildren );
	r[48]->setPalettePropagation( QWidget::NoChildren );
	r[48]->setText( "" );
	r[48]->setAutoRepeat( FALSE );
	r[48]->setAutoResize( FALSE );

	r[49] = new QCheckBox( this, "CheckBox_52" );
	r[49]->setGeometry( 620, 70, 120, 20 );
	r[49]->setMinimumSize( 0, 0 );
	r[49]->setMaximumSize( 32767, 32767 );
	r[49]->setFocusPolicy( QWidget::TabFocus );
	r[49]->setBackgroundMode( QWidget::PaletteBackground );
	r[49]->setFontPropagation( QWidget::NoChildren );
	r[49]->setPalettePropagation( QWidget::NoChildren );
	r[49]->setText( "" );
	r[49]->setAutoRepeat( FALSE );
	r[49]->setAutoResize( FALSE );

	r[50] = new QCheckBox( this, "CheckBox_53" );
	r[50]->setGeometry( 620, 90, 120, 20 );
	r[50]->setMinimumSize( 0, 0 );
	r[50]->setMaximumSize( 32767, 32767 );
	r[50]->setFocusPolicy( QWidget::TabFocus );
	r[50]->setBackgroundMode( QWidget::PaletteBackground );
	r[50]->setFontPropagation( QWidget::NoChildren );
	r[50]->setPalettePropagation( QWidget::NoChildren );
	r[50]->setText( "" );
	r[50]->setAutoRepeat( FALSE );
	r[50]->setAutoResize( FALSE );

	r[51] = new QCheckBox( this, "CheckBox_54" );
	r[51]->setGeometry( 620,110, 120, 20 );
	r[51]->setMinimumSize( 0, 0 );
	r[51]->setMaximumSize( 32767, 32767 );
	r[51]->setFocusPolicy( QWidget::TabFocus );
	r[51]->setBackgroundMode( QWidget::PaletteBackground );
	r[51]->setFontPropagation( QWidget::NoChildren );
	r[51]->setPalettePropagation( QWidget::NoChildren );
	r[51]->setText( "" );
	r[51]->setAutoRepeat( FALSE );
	r[51]->setAutoResize( FALSE );

	r[52] = new QCheckBox( this, "CheckBox_55" );
	r[52]->setGeometry( 620,130, 120, 20 );
	r[52]->setMinimumSize( 0, 0 );
	r[52]->setMaximumSize( 32767, 32767 );
	r[52]->setFocusPolicy( QWidget::TabFocus );
	r[52]->setBackgroundMode( QWidget::PaletteBackground );
	r[52]->setFontPropagation( QWidget::NoChildren );
	r[52]->setPalettePropagation( QWidget::NoChildren );
	r[52]->setText( "" );
	r[52]->setAutoRepeat( FALSE );
	r[52]->setAutoResize( FALSE );

	r[53] = new QCheckBox( this, "CheckBox_56" );
	r[53]->setGeometry( 620,150, 120, 20 );
	r[53]->setMinimumSize( 0, 0 );
	r[53]->setMaximumSize( 32767, 32767 );
	r[53]->setFocusPolicy( QWidget::TabFocus );
	r[53]->setBackgroundMode( QWidget::PaletteBackground );
	r[53]->setFontPropagation( QWidget::NoChildren );
	r[53]->setPalettePropagation( QWidget::NoChildren );
	r[53]->setText( "" );
	r[53]->setAutoRepeat( FALSE );
	r[53]->setAutoResize( FALSE );

	r[54] = new QCheckBox( this, "CheckBox_57" );
	r[54]->setGeometry( 620, 170, 120, 20 );
	r[54]->setMinimumSize( 0, 0 );
	r[54]->setMaximumSize( 32767, 32767 );
	r[54]->setFocusPolicy( QWidget::TabFocus );
	r[54]->setBackgroundMode( QWidget::PaletteBackground );
	r[54]->setFontPropagation( QWidget::NoChildren );
	r[54]->setPalettePropagation( QWidget::NoChildren );
	r[54]->setText( "" );
	r[54]->setAutoRepeat( FALSE );
	r[54]->setAutoResize( FALSE );

	r[55] = new QCheckBox( this, "CheckBox_58" );
	r[55]->setGeometry( 620, 190, 120, 20 );
	r[55]->setMinimumSize( 0, 0 );
	r[55]->setMaximumSize( 32767, 32767 );
	r[55]->setFocusPolicy( QWidget::TabFocus );
	r[55]->setBackgroundMode( QWidget::PaletteBackground );
	r[55]->setFontPropagation( QWidget::NoChildren );
	r[55]->setPalettePropagation( QWidget::NoChildren );
	r[55]->setText( "" );
	r[55]->setAutoRepeat( FALSE );
	r[55]->setAutoResize( FALSE );

	r[56] = new QCheckBox( this, "CheckBox_59" );
	r[56]->setGeometry( 620, 210, 120, 20 );
	r[56]->setMinimumSize( 0, 0 );
	r[56]->setMaximumSize( 32767, 32767 );
	r[56]->setFocusPolicy( QWidget::TabFocus );
	r[56]->setBackgroundMode( QWidget::PaletteBackground );
	r[56]->setFontPropagation( QWidget::NoChildren );
	r[56]->setPalettePropagation( QWidget::NoChildren );
	r[56]->setText( "" );
	r[56]->setAutoRepeat( FALSE );
	r[56]->setAutoResize( FALSE );

	r[57] = new QCheckBox( this, "CheckBox_60" );
	r[57]->setGeometry( 620, 230, 120, 20 );
	r[57]->setMinimumSize( 0, 0 );
	r[57]->setMaximumSize( 32767, 32767 );
	r[57]->setFocusPolicy( QWidget::TabFocus );
	r[57]->setBackgroundMode( QWidget::PaletteBackground );
	r[57]->setFontPropagation( QWidget::NoChildren );
	r[57]->setPalettePropagation( QWidget::NoChildren );
	r[57]->setText( "" );
	r[57]->setAutoRepeat( FALSE );
	r[57]->setAutoResize( FALSE );

	r[58] = new QCheckBox( this, "CheckBox_61" );
	r[58]->setGeometry( 620, 250, 120, 20 );
	r[58]->setMinimumSize( 0, 0 );
	r[58]->setMaximumSize( 32767, 32767 );
	r[58]->setFocusPolicy( QWidget::TabFocus );
	r[58]->setBackgroundMode( QWidget::PaletteBackground );
	r[58]->setFontPropagation( QWidget::NoChildren );
	r[58]->setPalettePropagation( QWidget::NoChildren );
	r[58]->setText( "" );
	r[58]->setAutoRepeat( FALSE );
	r[58]->setAutoResize( FALSE );

	r[59] = new QCheckBox( this, "CheckBox_62" );
	r[59]->setGeometry( 620, 270, 120, 20 );
	r[59]->setMinimumSize( 0, 0 );
	r[59]->setMaximumSize( 32767, 32767 );
	r[59]->setFocusPolicy( QWidget::TabFocus );
	r[59]->setBackgroundMode( QWidget::PaletteBackground );
	r[59]->setFontPropagation( QWidget::NoChildren );
	r[59]->setPalettePropagation( QWidget::NoChildren );
	r[59]->setText( "" );
	r[59]->setAutoRepeat( FALSE );
	r[59]->setAutoResize( FALSE );

	r[60] = new QCheckBox( this, "CheckBox_63" );
	r[60]->setGeometry( 620, 290, 120, 20 );
	r[60]->setMinimumSize( 0, 0 );
	r[60]->setMaximumSize( 32767, 32767 );
	r[60]->setFocusPolicy( QWidget::TabFocus );
	r[60]->setBackgroundMode( QWidget::PaletteBackground );
	r[60]->setFontPropagation( QWidget::NoChildren );
	r[60]->setPalettePropagation( QWidget::NoChildren );
	r[60]->setText( "" );
	r[60]->setAutoRepeat( FALSE );
	r[60]->setAutoResize( FALSE );

	r[61] = new QCheckBox( this, "CheckBox_64" );
	r[61]->setGeometry( 620, 310, 120, 20 );
	r[61]->setMinimumSize( 0, 0 );
	r[61]->setMaximumSize( 32767, 32767 );
	r[61]->setFocusPolicy( QWidget::TabFocus );
	r[61]->setBackgroundMode( QWidget::PaletteBackground );
	r[61]->setFontPropagation( QWidget::NoChildren );
	r[61]->setPalettePropagation( QWidget::NoChildren );
	r[61]->setText( "" );
	r[61]->setAutoRepeat( FALSE );
	r[61]->setAutoResize( FALSE );

	r[62] = new QCheckBox( this, "CheckBox_65" );
	r[62]->setGeometry( 770, 30, 120, 20 );
	r[62]->setMinimumSize( 0, 0 );
	r[62]->setMaximumSize( 32767, 32767 );
	r[62]->setFocusPolicy( QWidget::TabFocus );
	r[62]->setBackgroundMode( QWidget::PaletteBackground );
	r[62]->setFontPropagation( QWidget::NoChildren );
	r[62]->setPalettePropagation( QWidget::NoChildren );
	r[62]->setText( "" );
	r[62]->setAutoRepeat( FALSE );
	r[62]->setAutoResize( FALSE );

	r[63] = new QCheckBox( this, "CheckBox_66" );
	r[63]->setGeometry( 770, 50, 120, 20 );
	r[63]->setMinimumSize( 0, 0 );
	r[63]->setMaximumSize( 32767, 32767 );
	r[63]->setFocusPolicy( QWidget::TabFocus );
	r[63]->setBackgroundMode( QWidget::PaletteBackground );
	r[63]->setFontPropagation( QWidget::NoChildren );
	r[63]->setPalettePropagation( QWidget::NoChildren );
	r[63]->setText( "" );
	r[63]->setAutoRepeat( FALSE );
	r[63]->setAutoResize( FALSE );

	r[64] = new QCheckBox( this, "CheckBox_67" );
	r[64]->setGeometry( 770, 70, 120, 20 );
	r[64]->setMinimumSize( 0, 0 );
	r[64]->setMaximumSize( 32767, 32767 );
	r[64]->setFocusPolicy( QWidget::TabFocus );
	r[64]->setBackgroundMode( QWidget::PaletteBackground );
	r[64]->setFontPropagation( QWidget::NoChildren );
	r[64]->setPalettePropagation( QWidget::NoChildren );
	r[64]->setText( "" );
	r[64]->setAutoRepeat( FALSE );
	r[64]->setAutoResize( FALSE );

	r[65] = new QCheckBox( this, "CheckBox_68" );
	r[65]->setGeometry( 770, 90, 120, 20 );
	r[65]->setMinimumSize( 0, 0 );
	r[65]->setMaximumSize( 32767, 32767 );
	r[65]->setFocusPolicy( QWidget::TabFocus );
	r[65]->setBackgroundMode( QWidget::PaletteBackground );
	r[65]->setFontPropagation( QWidget::NoChildren );
	r[65]->setPalettePropagation( QWidget::NoChildren );
	r[65]->setText( "" );
	r[65]->setAutoRepeat( FALSE );
	r[65]->setAutoResize( FALSE );

	r[66] = new QCheckBox( this, "CheckBox_69" );
	r[66]->setGeometry( 770, 110, 120, 20 );
	r[66]->setMinimumSize( 0, 0 );
	r[66]->setMaximumSize( 32767, 32767 );
	r[66]->setFocusPolicy( QWidget::TabFocus );
	r[66]->setBackgroundMode( QWidget::PaletteBackground );
	r[66]->setFontPropagation( QWidget::NoChildren );
	r[66]->setPalettePropagation( QWidget::NoChildren );
	r[66]->setText( "" );
	r[66]->setAutoRepeat( FALSE );
	r[66]->setAutoResize( FALSE );

	r[67] = new QCheckBox( this, "CheckBox_70" );
	r[67]->setGeometry( 770, 130, 120, 20 );
	r[67]->setMinimumSize( 0, 0 );
	r[67]->setMaximumSize( 32767, 32767 );
	r[67]->setFocusPolicy( QWidget::TabFocus );
	r[67]->setBackgroundMode( QWidget::PaletteBackground );
	r[67]->setFontPropagation( QWidget::NoChildren );
	r[67]->setPalettePropagation( QWidget::NoChildren );
	r[67]->setText( "" );
	r[67]->setAutoRepeat( FALSE );
	r[67]->setAutoResize( FALSE );

	r[68] = new QCheckBox( this, "CheckBox_71" );
	r[68]->setGeometry( 770, 150, 120, 20 );
	r[68]->setMinimumSize( 0, 0 );
	r[68]->setMaximumSize( 32767, 32767 );
	r[68]->setFocusPolicy( QWidget::TabFocus );
	r[68]->setBackgroundMode( QWidget::PaletteBackground );
	r[68]->setFontPropagation( QWidget::NoChildren );
	r[68]->setPalettePropagation( QWidget::NoChildren );
	r[68]->setText( "" );
	r[68]->setAutoRepeat( FALSE );
	r[68]->setAutoResize( FALSE );

	r[69] = new QCheckBox( this, "CheckBox_72" );
	r[69]->setGeometry( 770, 170, 120, 20 );
	r[69]->setMinimumSize( 0, 0 );
	r[69]->setMaximumSize( 32767, 32767 );
	r[69]->setFocusPolicy( QWidget::TabFocus );
	r[69]->setBackgroundMode( QWidget::PaletteBackground );
	r[69]->setFontPropagation( QWidget::NoChildren );
	r[69]->setPalettePropagation( QWidget::NoChildren );
	r[69]->setText( "" );
	r[69]->setAutoRepeat( FALSE );
	r[69]->setAutoResize( FALSE );

	r[70] = new QCheckBox( this, "CheckBox_73" );
	r[70]->setGeometry( 770, 190, 120, 20 );
	r[70]->setMinimumSize( 0, 0 );
	r[70]->setMaximumSize( 32767, 32767 );
	r[70]->setFocusPolicy( QWidget::TabFocus );
	r[70]->setBackgroundMode( QWidget::PaletteBackground );
	r[70]->setFontPropagation( QWidget::NoChildren );
	r[70]->setPalettePropagation( QWidget::NoChildren );
	r[70]->setText( "" );
	r[70]->setAutoRepeat( FALSE );
	r[70]->setAutoResize( FALSE );

	r[71] = new QCheckBox( this, "CheckBox_74" );
	r[71]->setGeometry( 770, 210, 120, 20 );
	r[71]->setMinimumSize( 0, 0 );
	r[71]->setMaximumSize( 32767, 32767 );
	r[71]->setFocusPolicy( QWidget::TabFocus );
	r[71]->setBackgroundMode( QWidget::PaletteBackground );
	r[71]->setFontPropagation( QWidget::NoChildren );
	r[71]->setPalettePropagation( QWidget::NoChildren );
	r[71]->setText( "" );
	r[71]->setAutoRepeat( FALSE );
	r[71]->setAutoResize( FALSE );

	r[72] = new QCheckBox( this, "CheckBox_75" );
	r[72]->setGeometry( 770, 230, 120, 20 );
	r[72]->setMinimumSize( 0, 0 );
	r[72]->setMaximumSize( 32767, 32767 );
	r[72]->setFocusPolicy( QWidget::TabFocus );
	r[72]->setBackgroundMode( QWidget::PaletteBackground );
	r[72]->setFontPropagation( QWidget::NoChildren );
	r[72]->setPalettePropagation( QWidget::NoChildren );
	r[72]->setText( "" );
	r[72]->setAutoRepeat( FALSE );
	r[72]->setAutoResize( FALSE );

	r[73] = new QCheckBox( this, "CheckBox_76" );
	r[73]->setGeometry( 770, 250, 120, 20 );
	r[73]->setMinimumSize( 0, 0 );
	r[73]->setMaximumSize( 32767, 32767 );
	r[73]->setFocusPolicy( QWidget::TabFocus );
	r[73]->setBackgroundMode( QWidget::PaletteBackground );
	r[73]->setFontPropagation( QWidget::NoChildren );
	r[73]->setPalettePropagation( QWidget::NoChildren );
	r[73]->setText( "" );
	r[73]->setAutoRepeat( FALSE );
	r[73]->setAutoResize( FALSE );

	r[74] = new QCheckBox( this, "CheckBox_77" );
	r[74]->setGeometry( 770, 270, 120, 20 );
	r[74]->setMinimumSize( 0, 0 );
	r[74]->setMaximumSize( 32767, 32767 );
	r[74]->setFocusPolicy( QWidget::TabFocus );
	r[74]->setBackgroundMode( QWidget::PaletteBackground );
	r[74]->setFontPropagation( QWidget::NoChildren );
	r[74]->setPalettePropagation( QWidget::NoChildren );
	r[74]->setText( "" );
	r[74]->setAutoRepeat( FALSE );
	r[74]->setAutoResize( FALSE );

	r[75] = new QCheckBox( this, "CheckBox_78" );
	r[75]->setGeometry( 770, 290, 120, 20 );
	r[75]->setMinimumSize( 0, 0 );
	r[75]->setMaximumSize( 32767, 32767 );
	r[75]->setFocusPolicy( QWidget::TabFocus );
	r[75]->setBackgroundMode( QWidget::PaletteBackground );
	r[75]->setFontPropagation( QWidget::NoChildren );
	r[75]->setPalettePropagation( QWidget::NoChildren );
	r[75]->setText( "" );
	r[75]->setAutoRepeat( FALSE );
	r[75]->setAutoResize( FALSE );

	r[76] = new QCheckBox( this, "CheckBox_79" );
	r[76]->setGeometry( 770, 310, 120, 20 );
	r[76]->setMinimumSize( 0, 0 );
	r[76]->setMaximumSize( 32767, 32767 );
	r[76]->setFocusPolicy( QWidget::TabFocus );
	r[76]->setBackgroundMode( QWidget::PaletteBackground );
	r[76]->setFontPropagation( QWidget::NoChildren );
	r[76]->setPalettePropagation( QWidget::NoChildren );
	r[76]->setText( "" );
	r[76]->setAutoRepeat( FALSE );
	r[76]->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_1;
	qtarch_PushButton_1 = new QPushButton( this, "PushButton_1" );
	qtarch_PushButton_1->setGeometry( 910, 10, 100, 30 );
	qtarch_PushButton_1->setMinimumSize( 0, 0 );
	qtarch_PushButton_1->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_1, SIGNAL(clicked()), SLOT(restrictallslot()) );
	qtarch_PushButton_1->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_1->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_1->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_1->setText( transl("Restrict All") );
	qtarch_PushButton_1->setAutoRepeat( FALSE );
	qtarch_PushButton_1->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_2;
	qtarch_PushButton_2 = new QPushButton( this, "PushButton_2" );
	qtarch_PushButton_2->setGeometry( 910, 50, 100, 30 );
	qtarch_PushButton_2->setMinimumSize( 0, 0 );
	qtarch_PushButton_2->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_2, SIGNAL(clicked()), SLOT(unrestrictallslot()) );
	qtarch_PushButton_2->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_2->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_2->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_2->setText( transl("Unrestrict All") );
	qtarch_PushButton_2->setAutoRepeat( FALSE );
	qtarch_PushButton_2->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_3;
	qtarch_PushButton_3 = new QPushButton( this, "PushButton_3" );
	qtarch_PushButton_3->setGeometry( 910, 90, 100, 30 );
	qtarch_PushButton_3->setMinimumSize( 0, 0 );
	qtarch_PushButton_3->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_3, SIGNAL(clicked()), SLOT(toggleminorslot()) );
	qtarch_PushButton_3->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_3->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_3->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_3->setText( transl("Toggle Minors") );
	qtarch_PushButton_3->setAutoRepeat( FALSE );
	qtarch_PushButton_3->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_4;
	qtarch_PushButton_4 = new QPushButton( this, "PushButton_4" );
	qtarch_PushButton_4->setGeometry( 910, 130, 100, 30 );
	qtarch_PushButton_4->setMinimumSize( 0, 0 );
	qtarch_PushButton_4->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_4, SIGNAL(clicked()), SLOT(toglecuspslot()) );
	qtarch_PushButton_4->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_4->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_4->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_4->setText( transl("Toggle Cusps") );
	qtarch_PushButton_4->setAutoRepeat( FALSE );
	qtarch_PushButton_4->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_5;
	qtarch_PushButton_5 = new QPushButton( this, "PushButton_5" );
	qtarch_PushButton_5->setGeometry( 910, 170, 100, 30 );
	qtarch_PushButton_5->setMinimumSize( 0, 0 );
	qtarch_PushButton_5->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_5, SIGNAL(clicked()), SLOT(toggleuranslot()) );
	qtarch_PushButton_5->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_5->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_5->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_5->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_5->setText( transl("Toggle Uran") );
	qtarch_PushButton_5->setAutoRepeat( FALSE );
	qtarch_PushButton_5->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_6;
	qtarch_PushButton_6 = new QPushButton( this, "PushButton_6" );
	qtarch_PushButton_6->setGeometry( 910, 210, 100, 30 );
	qtarch_PushButton_6->setMinimumSize( 0, 0 );
	qtarch_PushButton_6->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_6, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_6->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_6->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_6->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_6->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_6->setText( transl("Cancel") );
	qtarch_PushButton_6->setAutoRepeat( FALSE );
	qtarch_PushButton_6->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_7;
	qtarch_PushButton_7 = new QPushButton( this, "PushButton_7" );
	qtarch_PushButton_7->setGeometry( 910, 250, 100, 30 );
	qtarch_PushButton_7->setMinimumSize( 0, 0 );
	qtarch_PushButton_7->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_7, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_7->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_7->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_7->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_7->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_7->setText( transl("OK") );
	qtarch_PushButton_7->setAutoRepeat( FALSE );
	qtarch_PushButton_7->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_8;
	qtarch_PushButton_8 = new QPushButton( this, "PushButton_8" );
	qtarch_PushButton_8->setGeometry( 10, 250, 290, 30 );
	qtarch_PushButton_8->setMinimumSize( 0, 0 );
	qtarch_PushButton_8->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_8, SIGNAL(clicked()), SLOT(copyslot()) );
	qtarch_PushButton_8->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_8->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_8->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_8->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_8->setText( transl("Copy from Other Restriction Set") );
	qtarch_PushButton_8->setAutoRepeat( FALSE );
	qtarch_PushButton_8->setAutoResize( FALSE );

	rPlan->insert( r[0] );
	rPlan->insert( r[1] );
	rPlan->insert( r[2] );
	rPlan->insert( r[3] );
	rPlan->insert( r[4] );
	rPlan->insert( r[5] );
	rPlan->insert( r[6] );
	rPlan->insert( r[7] );
	rPlan->insert( r[8] );
	rPlan->insert( r[9] );

	rMinObj->insert( r[10] );
	rMinObj->insert( r[11] );
	rMinObj->insert( r[12] );
	rMinObj->insert( r[13] );
	rMinObj->insert( r[14] );
	rMinObj->insert( r[15] );
	rMinObj->insert( r[16] );
	rMinObj->insert( r[17] );
	rMinObj->insert( r[18] );
	rMinObj->insert( r[19] );

	rHouses->insert( r[20] );
	rHouses->insert( r[21] );
	rHouses->insert( r[22] );
	rHouses->insert( r[23] );
	rHouses->insert( r[24] );
	rHouses->insert( r[25] );
	rHouses->insert( r[26] );
	rHouses->insert( r[27] );
	rHouses->insert( r[28] );
	rHouses->insert( r[29] );
	rHouses->insert( r[30] );
	rHouses->insert( r[31] );

	rUranians->insert( r[32] );
	rUranians->insert( r[33] );
	rUranians->insert( r[34] );
	rUranians->insert( r[35] );
	rUranians->insert( r[36] );
	rUranians->insert( r[37] );
	rUranians->insert( r[38] );
	rUranians->insert( r[39] );
	rUranians->insert( r[40] );
	rUranians->insert( r[41] );
	rUranians->insert( r[42] );
	rUranians->insert( r[43] );
	rUranians->insert( r[44] );
	rUranians->insert( r[45] );
	rUranians->insert( r[46] );
	rUranians->insert( r[47] );
	rUranians->insert( r[48] );
	rUranians->insert( r[49] );
	rUranians->insert( r[50] );
	rUranians->insert( r[51] );
	rUranians->insert( r[52] );
	rUranians->insert( r[53] );
	rUranians->insert( r[54] );
	rUranians->insert( r[55] );
	rUranians->insert( r[56] );
	rUranians->insert( r[57] );
	rUranians->insert( r[58] );
	rUranians->insert( r[59] );
	rUranians->insert( r[60] );
	rUranians->insert( r[61] );
	rUranians->insert( r[62] );
	rUranians->insert( r[63] );
	rUranians->insert( r[64] );
	rUranians->insert( r[65] );
	rUranians->insert( r[66] );
	rUranians->insert( r[67] );
	rUranians->insert( r[68] );
	rUranians->insert( r[69] );
	rUranians->insert( r[70] );
	rUranians->insert( r[71] );
	rUranians->insert( r[72] );
	rUranians->insert( r[73] );
	rUranians->insert( r[74] );
	rUranians->insert( r[75] );
	rUranians->insert( r[76] );

	resize( 1020,340 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


RestrictionsData::~RestrictionsData()
{
}
void RestrictionsData::rplanslot(int)
{
}
void RestrictionsData::rminobjslot(int)
{
}
void RestrictionsData::housesslot(int)
{
}
void RestrictionsData::uranianslot(int)
{
}
void RestrictionsData::restrictallslot()
{
}
void RestrictionsData::unrestrictallslot()
{
}
void RestrictionsData::toggleminorslot()
{
}
void RestrictionsData::toglecuspslot()
{
}
void RestrictionsData::toggleuranslot()
{
}
void RestrictionsData::cancelslot()
{
}
void RestrictionsData::okslot()
{
}
void RestrictionsData::copyslot()
{
}
