/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: SetAstroColorData.cpp
	Last generated: Sat Oct 16 14:28:43 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#include <qpixmap.h>
#include <qlayout.h>
#include "SetAstroColorData.h"

#define Inherited QDialog

#include <qpushbt.h>

SetAstroColorData::SetAstroColorData
(
	QWidget* parent,
	const char* name
)
	:
	Inherited( parent, name, TRUE, 0 )
{
	cv = new ColorVector( this, "User_1" );
	cv->setGeometry( 20, 10, 210, 380 );
	cv->setMinimumSize( 0, 0 );
	cv->setMaximumSize( 32767, 32767 );
	cv->setFocusPolicy( QWidget::NoFocus );
	cv->setBackgroundMode( QWidget::PaletteBackground );
	cv->setFontPropagation( QWidget::NoChildren );
	cv->setPalettePropagation( QWidget::NoChildren );

	ColorList = new QListBox( this, "ListBox_2" );
	ColorList->setGeometry( 240, 30, 120, 240 );
	ColorList->setMinimumSize( 0, 0 );
	ColorList->setMaximumSize( 32767, 32767 );
	connect( ColorList, SIGNAL(selected(int)), SLOT(colorlistslot(int)) );
	ColorList->setFocusPolicy( QWidget::StrongFocus );
	ColorList->setBackgroundMode( QWidget::PaletteBase );
	ColorList->setFontPropagation( QWidget::SameFont );
	ColorList->setPalettePropagation( QWidget::SameFont );
	ColorList->setFrameStyle( 51 );
	ColorList->setLineWidth( 2 );
	ColorList->setDragSelect( FALSE );
	ColorList->setMultiSelection( FALSE );

	QPushButton* qtarch_PushButton_23;
	qtarch_PushButton_23 = new QPushButton( this, "PushButton_23" );
	qtarch_PushButton_23->setGeometry( 240, 290, 120, 30 );
	qtarch_PushButton_23->setMinimumSize( 0, 0 );
	qtarch_PushButton_23->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_23, SIGNAL(clicked()), SLOT(okslot()) );
	qtarch_PushButton_23->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_23->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_23->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_23->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_23->setText( transl("OK") );
	qtarch_PushButton_23->setAutoRepeat( FALSE );
	qtarch_PushButton_23->setAutoResize( FALSE );

	QPushButton* qtarch_PushButton_24;
	qtarch_PushButton_24 = new QPushButton( this, "PushButton_24" );
	qtarch_PushButton_24->setGeometry( 240, 340, 120, 30 );
	qtarch_PushButton_24->setMinimumSize( 0, 0 );
	qtarch_PushButton_24->setMaximumSize( 32767, 32767 );
	connect( qtarch_PushButton_24, SIGNAL(clicked()), SLOT(cancelslot()) );
	qtarch_PushButton_24->setFocusPolicy( QWidget::TabFocus );
	qtarch_PushButton_24->setBackgroundMode( QWidget::PaletteBackground );
	qtarch_PushButton_24->setFontPropagation( QWidget::NoChildren );
	qtarch_PushButton_24->setPalettePropagation( QWidget::NoChildren );
	qtarch_PushButton_24->setText( transl("Cancel") );
	qtarch_PushButton_24->setAutoRepeat( FALSE );
	qtarch_PushButton_24->setAutoResize( FALSE );

	resize( 380,410 );
	setMinimumSize( 0, 0 );
	setMaximumSize( 32767, 32767 );
}


SetAstroColorData::~SetAstroColorData()
{
}
void SetAstroColorData::colorlistslot(int)
{
}
void SetAstroColorData::okslot()
{
}
void SetAstroColorData::cancelslot()
{
}
