/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: SetColorsData.h
	Last generated: Mon Oct 18 15:14:38 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef SetColorsData_included
#define SetColorsData_included

#include <qdialog.h>
#include <qbttngrp.h>
#include "ColorVector.h"
#include <qradiobt.h>
#include "tr.h"

class SetColorsData : public QDialog
{
    Q_OBJECT

public:

    SetColorsData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~SetColorsData();

public slots:


protected slots:

    virtual void okslot();
    virtual void cancelslot();
    virtual void elementsslot(int);
    virtual void aspectsslot(int);

protected:
    QButtonGroup* Aspects;
    QButtonGroup* Elements;
    ColorVector* cv;
    QRadioButton* e[4];
    QRadioButton* a[18];
    
};

#endif // SetColorsData_included
