/*****************************************************************************
 * This software is distributed under the terms of the General Public License.
 *
 * Program :        kastrolog 5.4-2
 * Authors : see the AUTHORS file
 * E-Mail  : Llyra@altavista.com
*****************************************************************************/ 


/**********************************************************************

	--- Qt Architect generated file ---

	File: StarRestrictData.h
	Last generated: Mon Oct 25 13:54:25 1999

	DO NOT EDIT!!!  This file will be automatically
	regenerated by qtarch.  All changes will be lost.

 *********************************************************************/

#ifndef StarRestrictData_included
#define StarRestrictData_included

#include <qdialog.h>
#include <qchkbox.h>
#include "tr.h"

class StarRestrictData : public QDialog
{
    Q_OBJECT

public:

    StarRestrictData
    (
        QWidget* parent = NULL,
        const char* name = NULL
    );

    virtual ~StarRestrictData();

public slots:


protected slots:

    virtual void okslot();
    virtual void restrictslot();
    virtual void unrestrictslot();
    virtual void cancelslot();

protected:
    QCheckBox* s[47];    
};

#endif // StarRestrictData_included
